{
  "hash": "c1ee09895f0653bf52e3e1e6cbf38bfd",
  "result": {
    "engine": "knitr",
    "markdown": "# Simulation example {#sec-ex4}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Load packages\nlibrary(ggdag)\nlibrary(dagitty)\nlibrary(rstanarm)\nlibrary(tidybayes)\nlibrary(ggdist)\nlibrary(tidyverse)\nlibrary(gt)\nlibrary(rstan)\n```\n:::\n\n\n\n\n## Data-generating process\n\nThe data-generating process is described via the directed acyclic graph (DAG) in @fig-DAG.ex4-1. In this DAG, relative humidity $(\\text{H})$ influences respiratory irritation $(\\text{R})$ both directly and indirectly, passing through microbial aerosol $(\\text{M})$. Additionally, respiratory irritation $(\\text{R})$ influences absence $(\\text{A})$ directly.\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\ndag_coords.ex4 <-\n  data.frame(name = c('M', 'H', 'A', 'R'),\n             x = c(1, 3.5, 6, 6),\n             y = c(3, 2, 1, 3))\n\nDAG.ex4 <-\n  dagify(M ~ H,\n         R ~ H + M,\n         A ~ R,\n         coords = dag_coords.ex4)\n\nnode_labels <- c(\n  M = 'bold(M)', \n  H = 'bold(H)', \n  A = 'bold(A)', \n  R = 'bold(R)'\n)\n\nggplot(data = DAG.ex4, aes(x = x, y = y, xend = xend, yend = yend)) +\n  geom_dag_text(aes(label = node_labels[name]),\n                parse = TRUE,\n                colour = 'black',\n                size = 10,\n                family = 'mono') +\n  geom_dag_edges(arrow_directed = grid::arrow(length = grid::unit(10, 'pt'), type = 'open'),\n                 edge_colour = 'black',\n                 family = 'mono',\n                 fontface = 'bold') +\n  annotate('text', x = 1, y = 3.3, label = 'microbial aerosol', \n           size = 4, hjust = 0.5, colour = 'grey50') +\n  annotate('text', x = 3.5, y = 1.7, label = 'relative humidity', \n           size = 4, hjust = 0.5, colour = 'grey50') +\n  annotate('text', x = 6, y = 3.3, label = 'respiratory irritation', \n           size = 4, hjust = 0.7, colour = 'grey50') +\n  annotate('text', x = 6, y = 0.7, label = 'absence', \n           size = 4, hjust = 0.6, colour = 'grey50') +\n  coord_cartesian(xlim = c(0.5, 6.5), ylim = c(0.8, 3.2))  +\n  theme_dag()\n```\n\n::: {.cell-output-display}\n![Graphical representation via DAG of the data-generating process.](ex4_simulation_files/figure-html/fig-DAG.ex4-1-1.png){#fig-DAG.ex4-1 fig-align='center' width=60%}\n:::\n:::\n\n\n\n\nThe DAG in @fig-DAG.ex4-1 can be written as:\n\n-   $M \\sim f_{M}(H)$, read as 'microbial aerosol $(\\text{M})$ is some function of relative humidity $(\\text{H})$'.\n-   $R \\sim f_{R}(H, M)$, read as 'respiratory irritation $(\\text{R})$ is some function of relative humidity $(\\text{H})$ and microbial aerosol $(\\text{M})$'.\n-   $A \\sim f_{A}(R)$, read as 'absence $(\\text{A})$ is some function of respiratory irritation $(\\text{R})$'.\n\n## Synthetic data set\n\nTo generate synthetic data, we defined the custom function `data.sim_ex4()`. This function takes as inputs the sample size `n` and generates synthetic data according to the DAG in @fig-DAG.ex4-1.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.sim_ex4 <- function(n) {\n  b_hum.resp = c(0, 0.5) #direct causal effect of H on R\n  b_micr.resp = c(0, 3) #direct causal effect of M on R\n  #Simulate relative humidity\n  H <- factor(sample(c('low', 'high'), size = n, replace = TRUE))\n  #Simulate microbial aerosol\n  M <- factor(ifelse(rbinom(n = n, size = 1, prob = plogis(ifelse(H == 'low', -1.5, 2))) == 0, 'low', 'high'))\n  #Simulate respiratory irritation\n  R <- rnorm(n = n, mean = -1 + ifelse(H == 'high', b_hum.resp[1], b_hum.resp[2]) + ifelse(M == 'low',  b_micr.resp[1],  b_micr.resp[2]), sd = 3)\n  #Simulate absence \n  A <- factor(ifelse(rbinom(n = n, size = 1, prob = plogis(0.3 + 2 * R)) == 0, 'no', 'yes'))\n  #Return tibble with simulated values\n  return(tibble(H, A, M, R))\n}\n```\n:::\n\n\n\n\nFrom this data generation mechanism, we simulated the target population, which consists of one million observations.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2025) #set random number for reproducibility\n#Simulate the population\nex4_population <- data.sim_ex4(n = 1e6)\n#Set relative humidity reference category to 'high'\nex4_population$H <- relevel(ex4_population$H, ref = 'high')\n#Set microbial aerosol reference category to 'low'\nex4_population$M <- relevel(ex4_population$M, ref = 'low')\n#Set absence reference category to 'no'\nex4_population$A <- relevel(ex4_population$A, ref = 'no')\n#View the data frame\nex4_population\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,000,000 × 4\n   H     A     M            R\n   <fct> <fct> <fct>    <dbl>\n 1 low   yes   low    5.95   \n 2 high  yes   high   9.13   \n 3 high  yes   high  -0.00136\n 4 high  no    high  -3.59   \n 5 low   no    low   -3.32   \n 6 low   yes   low    0.832  \n 7 high  yes   high   2.46   \n 8 low   no    low   -4.59   \n 9 high  yes   high   6.80   \n10 low   no    low   -4.98   \n# ℹ 999,990 more rows\n```\n\n\n:::\n:::\n\n\n\n\nFrom this population, we obtained one data set of five thousand observations using simple random sampling.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_sims <- 1e3 #number of data sets to simulate\n\n#Set random number for reproducibility\nset.seed(2025)  \n#Generate a vector of random numbers for reproducibility\nex4_random.seed <- sample(1:1e5, size = n_sims, replace = FALSE)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(ex4_random.seed[1])\n#Sample one data set of 5,000 observations\nex4_sample.random <- \n  ex4_population %>% \n  slice_sample(n = 5e3) #take a simple random sample of size 5,000 \n\n#View the data frame\nex4_sample.random\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,000 × 4\n   H     A     M          R\n   <fct> <fct> <fct>  <dbl>\n 1 high  yes   high   5.94 \n 2 low   yes   low    0.799\n 3 low   no    low   -2.45 \n 4 high  yes   high   2.25 \n 5 low   no    low   -1.24 \n 6 low   no    low   -2.90 \n 7 high  no    high  -0.279\n 8 low   no    low   -2.21 \n 9 high  no    high  -2.38 \n10 low   no    low   -4.50 \n# ℹ 4,990 more rows\n```\n\n\n:::\n:::\n\n\n\n\n## Data analysis\n\nIn this example, the target of our analysis is the total average causal effect, ACE (also known as total average treatment effect, ATE) of microbial aerosol $(\\text{M})$ on respiratory irritation $(\\text{R})$, which stands for the expected increase of $\\text{R}$ in response to a change in $\\text{M}$ from `low` to `high` due to an intervention. The causal effect of interest is visualized in @fig-DAG.ex4-2.\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(data = DAG.ex4, aes(x = x, y = y, xend = xend, yend = yend)) +\n  #visualize causal effect path\n  geom_segment(x = 1, xend = 6, y = 3, yend = 3,\n               linewidth = 14, lineend = 'round', colour = '#009E73', alpha = 0.05) +\n  geom_dag_text(aes(label = node_labels[name]),\n                parse = TRUE,\n                colour = 'black',\n                size = 10,\n                family = 'mono') +\n  geom_dag_edges(arrow_directed = grid::arrow(length = grid::unit(10, 'pt'), type = 'open'),\n                 edge_colour = 'black',\n                 family = 'mono',\n                 fontface = 'bold') +\n  annotate('text', x = 1, y = 3.3, label = 'microbial aerosol', \n           size = 4, hjust = 0.5, colour = 'grey50') +\n  annotate('text', x = 3.5, y = 1.7, label = 'relative humidity', \n           size = 4, hjust = 0.5, colour = 'grey50') +\n  annotate('text', x = 6, y = 3.3, label = 'respiratory irritation', \n           size = 4, hjust = 0.7, colour = 'grey50') +\n  annotate('text', x = 6, y = 0.7, label = 'absence', \n           size = 4, hjust = 0.6, colour = 'grey50') +\n  #causal effect number\n  annotate('text', x = 3.5, y = 3.2, label = '3', \n           size = 4.5, hjust = 0.5, colour = 'black', parse = TRUE) +\n  coord_cartesian(xlim = c(0.5, 6.5), ylim = c(0.8, 3.2))  +\n  theme_dag()\n```\n\n::: {.cell-output-display}\n![Graphical representation via DAG of the data-generating process. The green line indicates the causal question of interest, and the number on the path indicates the total average causal effect.](ex4_simulation_files/figure-html/fig-DAG.ex4-2-1.png){#fig-DAG.ex4-2 fig-align='center' width=60%}\n:::\n:::\n\n\n\n\n### Identification\n\nThe first step to answer the causal question of interest is identification. Identification answers a ‘theoretical’ question by determining whether a causal effect can, in principle, be estimated from observed data. The backdoor criterion and its generalization, the adjustment criterion, allow us to understand whether our causal effect of interest can be identified and, if so, which variables we should (or should not) statistically adjust for (i.e., the adjustment set) to estimate the causal effect from the data.\n\nGiven its simplicity, we will first apply the backdoor criterion to identify valid adjustment sets to estimate the causal effect of interest. If the backdoor criterion is not applicable, we will apply its generalization, the adjustment criterion.\n\n#### Backdoor criterion\n\nApplying the adjustment criterion revealed the existence of a backdoor path (i.e., a non-causal path) from microbial aerosol $(\\text{M})$ to respiratory irritation $(\\text{R})$. Specifically, the backdoor path is $\\text{M} \\leftarrow \\text{H} \\rightarrow \\text{R}$. Since relative humidity $(\\text{H})$ is a common cause of $\\text{M}$ and $\\text{R}$, association can flow from $\\text{M}$ to $\\text{R}$ through $\\text{H}$. As a result, there is confounding. To close this backdoor path we need to adjust for $\\text{H}$.\n\nGiven the DAG in @fig-DAG.ex4-2, we can use the `adjustmentSets()` function to identify the adjustment set algorithmically. It is essential to note that this function applies the adjustment criterion and not the backdoor criterion. As such, the `adjustmentSets()` function can find adjustment sets even when the backdoor criterion is not applicable.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nadjustmentSets(DAG.ex4,\n               exposure = 'M', #microbial aerosol\n               outcome = 'R', #respiratory irritation\n               type = 'all', \n               effect = 'total', \n               max.results = Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{ H }\n```\n\n\n:::\n:::\n\n\n\n\nAs expected, the resulting adjustment set includes $\\text{H}$. Therefore, to get the correct estimate of the total average causal effect, we need to adjust for $\\text{H}$; failing to do so will lead to bias.\n\n### Estimation\n\nFollowing the identification step is the estimation step. This step addresses a statistical question by determining how the causal effect identified in the previous step can be estimated. To perform this step, we used a parametric (model-based) estimator, specifically, linear regression. This was possible because we designed the illustrative examples to be simple and with a linear relationship between the variables. This way, we limited the complexity of the examples themselves and shifted the focus to the application of the backdoor criterion to define 'correct' adjustment sets.\n\nFor transparency and understanding, all (implicit) assumptions used for this illustrative example are (explicitly) provided in @tbl-summary.ex4.\n\n\n\n\n::: {#tbl-summary.ex4 .cell tbl-cap='Summary description of the simulation example'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"pefclyqint\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#pefclyqint table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#pefclyqint thead, #pefclyqint tbody, #pefclyqint tfoot, #pefclyqint tr, #pefclyqint td, #pefclyqint th {\n  border-style: none;\n}\n\n#pefclyqint p {\n  margin: 0;\n  padding: 0;\n}\n\n#pefclyqint .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#pefclyqint .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#pefclyqint .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#pefclyqint .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#pefclyqint .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pefclyqint .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pefclyqint .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pefclyqint .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#pefclyqint .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#pefclyqint .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#pefclyqint .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#pefclyqint .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#pefclyqint .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#pefclyqint .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#pefclyqint .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#pefclyqint .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#pefclyqint .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#pefclyqint .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#pefclyqint .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pefclyqint .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#pefclyqint .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#pefclyqint .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#pefclyqint .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pefclyqint .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#pefclyqint .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#pefclyqint .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pefclyqint .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pefclyqint .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#pefclyqint .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pefclyqint .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#pefclyqint .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pefclyqint .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pefclyqint .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pefclyqint .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pefclyqint .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pefclyqint .gt_left {\n  text-align: left;\n}\n\n#pefclyqint .gt_center {\n  text-align: center;\n}\n\n#pefclyqint .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#pefclyqint .gt_font_normal {\n  font-weight: normal;\n}\n\n#pefclyqint .gt_font_bold {\n  font-weight: bold;\n}\n\n#pefclyqint .gt_font_italic {\n  font-style: italic;\n}\n\n#pefclyqint .gt_super {\n  font-size: 65%;\n}\n\n#pefclyqint .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#pefclyqint .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#pefclyqint .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#pefclyqint .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#pefclyqint .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#pefclyqint .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#pefclyqint .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#pefclyqint .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#pefclyqint div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" style=\"table-layout:fixed;\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <colgroup>\n    <col style=\"width:22%;\"/>\n    <col/>\n  </colgroup>\n  \n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"vertical-align: top; font-weight: bold; background-color: #FFFFFF;\">Research question</td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Total average total causal effect (ACE) of microbial aerosol (M) on respiratory irritation (R).</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"vertical-align: top; font-weight: bold; background-color: #FFFFFF;\">Assumptions</td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Random sample (simple random sampling): everyone in the population has an equal chance of being selected into the sample.</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Limited random variability: large sample size.</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Independence of observations: each observation represents independent bits of information.</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">No confounding: the DAG includes all shared causes among the variables.</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">No model error: perfect functional form specification.</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">No measurement error: all variables are measured perfectly.</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"vertical-align: top; font-weight: bold; background-color: #FFFFFF;\">Variables</td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Relative humidity (H): categorical variable ['low'; 'high']</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Microbial aerosol (M): categorical variable ['low'; 'high']</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Absence (A): categorical variable ['no'; 'yes']</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Respiratory irritation (R): continuous variable [unit: -]</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nTo carry out the estimation step, we utilized linear regression within both the frequentist and Bayesian frameworks. Specifically, we will run three regression models:\n\n-   `Model.1` will include microbial aerosol $(\\text{M})$, relative humidity $(\\text{H})$ and absence $(\\text{A})$ as predictor;\n-   `Model.2` will include microbial aerosol $(\\text{M})$ and relative humidity $(\\text{H})$ as predictors.\n\nThe results of the fitted statistical models (i.e., `Model.1` and `Model.2`) are presented here.\n\n#### Frequentist framework\n\n<details>\n\n<summary>Click to expand</summary>\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Fit the linear regression model with M, H, A and R (Model 1)\nex4_Model.1 <-\n  lm(formula = R ~ M + H + A,\n     data = ex4_sample.random)\n#View of the model summary\nsummary(ex4_Model.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = R ~ M + H + A, data = ex4_sample.random)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-9.725 -1.386 -0.043  1.365  7.905 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -2.95007    0.08678  -33.99  < 2e-16 ***\nMhigh        1.37308    0.08360   16.42  < 2e-16 ***\nHlow         0.32211    0.08114    3.97 7.29e-05 ***\nAyes         4.63997    0.06148   75.47  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.013 on 4996 degrees of freedom\nMultiple R-squared:  0.606,\tAdjusted R-squared:  0.6058 \nF-statistic:  2562 on 3 and 4996 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Fit the linear regression model with M, H and R (Model 2)\nex4_Model.2 <-\n  lm(formula = R ~ M + H,\n     data = ex4_sample.random)\n#View of the model summary\nsummary(ex4_Model.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = R ~ M + H, data = ex4_sample.random)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11.8867  -1.9861   0.0083   2.0066   9.2993 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -0.9769     0.1210  -8.071 8.69e-16 ***\nMhigh         2.8811     0.1187  24.262  < 2e-16 ***\nHlow          0.5111     0.1186   4.309 1.67e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.944 on 4997 degrees of freedom\nMultiple R-squared:  0.1569,\tAdjusted R-squared:  0.1565 \nF-statistic: 464.9 on 2 and 4997 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nThe estimated coefficients for the two models are then plotted in @fig-DAG.ex4-estimate.\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nb_micr.resp = 3\n\ndata.frame(model = c('Model.1', 'Model.2'),\n           estimate = c(coef(ex4_Model.1)['Mhigh'], \n                        coef(ex4_Model.2)['Mhigh']),\n           lower.95.CI = c(confint(ex4_Model.1, level = 0.95, type = 'Wald')['Mhigh', 1],\n                           confint(ex4_Model.2, level = 0.95, type = 'Wald')['Mhigh', 1]),\n           upper.95.CI = c(confint(ex4_Model.1, level = 0.95, type = 'Wald')['Mhigh', 2],\n                           confint(ex4_Model.2, level = 0.95, type = 'Wald')['Mhigh', 2])) %>%\n  \nggplot(aes(x = estimate, y = model, xmin = lower.95.CI, xmax = upper.95.CI)) + \n  geom_vline(xintercept = b_micr.resp, alpha = 0.8, linetype = 'dashed', colour = 'blue') + \n  geom_linerange() +\n  geom_point(shape = 21, size = 2, fill = 'white', stroke = 1) +\n  scale_x_continuous('Estimate', \n                     breaks = seq(from = -5, to = 5, by = 0.5),\n                     limits = c(0.5, 3.5)) +\n  theme(panel.grid = element_blank(),\n        panel.background = element_blank(),\n        panel.border = element_rect(colour = 'black', fill = NA),\n        axis.title.y = element_blank())\n```\n\n::: {.cell-output-display}\n![Estimates of the microbial aerosol coefficient for the two models. The white dots represent the point estimate, and the black lines represent the 95% confidence intervals. The blue dashed line represents the parameter used to generate the data.](ex4_simulation_files/figure-html/fig-DAG.ex4-estimate-1.png){#fig-DAG.ex4-estimate fig-align='center' width=5400}\n:::\n:::\n\n\n\n\n@fig-DAG.ex4-estimate shows the estimates (point estimate and 95% confidence interval) of the coefficient for microbial aerosol for `Model.1` and `Model.2`.\n\nFor `Model.1` we found a positive coefficient between microbial aerosol $(\\text{M})$ and respiratory irritation $(\\text{R})$ equal to 1.373 with 95% CI \\[1.209, 1.537\\]. Since the 95% CI excludes zero, the regression coefficient is statistically significantly different from zero at the 0.05 level (p-value = 4.47e-59). Moreover, since the 95% CI does not include the data-generating parameter for microbial aerosol (i.e., `b_micr.resp = 3`), we can deduce that the estimated coefficient for microbial aerosol is statistically significantly different from 3 at the 0.05 level. We can test this more formally by using the `linearHypothesis()` function. Specifically,\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Test for M = 3\ncar::linearHypothesis(ex4_Model.1, 'Mhigh = 3') # car:: access the function from the car package without loading it in the environment \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLinear hypothesis test:\nMhigh = 3\n\nModel 1: restricted model\nModel 2: R ~ M + H + A\n\n  Res.Df   RSS Df Sum of Sq      F    Pr(>F)    \n1   4997 21775                                  \n2   4996 20240  1    1534.2 378.69 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\nThe resulting p-value is 2.31e-81, which indicates that we can reject the null hypothesis (i.e., `M = 3`) at the 0.05 level. This result suggests that the regression coefficient for microbial aerosol (i.e., 1.373) is statistically significantly different from 3. Since the estimated causal effect from `Model.1` is biased, we would erroneously conclude that changing microbial aerosol from `low` to `high` causes an increase in lung infection by 1.373 units (95% CI \\[1.209, 1.537\\]).\n\nFor `Model.2` we found a positive coefficient between microbial aerosol $(\\text{M})$ and respiratory irritation $(\\text{R})$ equal to 2.881 with 95% CI \\[2.648, 3.114\\]. Since the 95% CI excludes zero, the regression coefficient is statistically significantly different from zero at the 0.05 level (p-value = 5.01e-123). Additionally, since the 95% CI includes the data-generating parameter for microbial aerosol (i.e., `b_micr.resp = 3`), we can deduce that the estimated coefficient for microbial aerosol is not statistically significantly different from 3 at the 0.05 level (although this will be the case for all numbers within the 95% confidence interval). We can test this more formally by using the `linearHypothesis()` function. Specifically,\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Test for M = 3\ncar::linearHypothesis(ex4_Model.2, 'Mhigh = 3') # car:: access the function from the car package without loading it in the environment \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLinear hypothesis test:\nMhigh = 3\n\nModel 1: restricted model\nModel 2: R ~ M + H\n\n  Res.Df   RSS Df Sum of Sq      F Pr(>F)\n1   4998 43324                           \n2   4997 43315  1    8.6974 1.0034 0.3165\n```\n\n\n:::\n:::\n\n\n\n\nThe resulting p-value is 0.317, which indicates that we fail to reject the null hypothesis (i.e., `M = 3`) at the 0.05 level. This result suggests that the regression coefficient for microbial aerosol (i.e., 2.881) is not statistically significantly different from 3. Since the estimated causal effect from `Model.2` is unbiased, we would correctly conclude that changing microbial aerosol from `low` to `high` causes an increase in lung infection by 2.881 units (95% CI \\[2.648, 3.114\\]).\n\nImportantly, for `Model.1` and `Model.2`, the 95% confidence interval means that if we were to repeat the sampling process and calculate the interval many times, 95% of those calculated intervals would contain the true population parameter. To highlight this, we can repeat the analysis by fitting the two models to one thousand data sets randomly selected from our population.\n\nThe for-loop shown in the code below performs the following operations. First, sample (using simple random sample) a data set of 5,000 observations from the target population. Subsequently, perform linear regression using `Model.1` and `Model.2` and store the estimated coefficients for `microbial aerosol`, its standard error and 95% confidence interval in the data frame `coefs_ex4`. This operation is repeated a thousand times, resulting in the data frame `coefs_ex4` containing the estimates (point estimate, standard error and confidence interval) of a thousand random samples of size 5,000 using `Model.1` and `Model.2`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_model <- c('mod.1', 'mod.2')     \n\nn_row <- n_sims*length(n_model)\n\n#Create an empty data frame\nempty.df <- data.frame(matrix(NA, nrow = n_row, ncol = 7))\n#Rename the data frame columns\ncolnames(empty.df) <- c('sim.id', 'estimate', 'se', 'CI_2.5', 'CI_97.5',\n                        'model', 'coverage')\n\n#Sample a thousand data sets of 5,000 observations and perform linear regression \ncoefs_ex4 <- empty.df #assign the empty data frame\nk = 1\nfor (i in 1:n_sims){\n  set.seed(ex4_random.seed[i]) #set unique seed for each simulation \n#Sample data set from population   \n  sample.random <- \n    ex4_population %>% \n    slice_sample(n = 5e3) #take a simple random sample of size 5,000\n#Fit models\n  for (j in 1:length(n_model)){\n    if (n_model[j] == 'mod.1'){\n      fit <- lm(formula = R ~ M + H + A,\n                data = sample.random)\n    } else {\n      fit <- lm(formula = R ~ M + H,\n                data = sample.random)\n    }  \n#Compile matrix  \n  coefs_ex4[k, 1] <- i #simulation ID\n  coefs_ex4[k, 2] <- coef(fit)['Mhigh'] #point estimate\n  coefs_ex4[k, 3] <- summary(fit)$coef['Mhigh','Std. Error'] #standard error\n  coefs_ex4[k, 4:5] <- confint(fit, level = 0.95, type = 'Wald')['Mhigh', ] #confidence interval (Wald)\n  coefs_ex4[k, 6] <- n_model[j] #sample size\n  k = k + 1\n  }\n}\ncoefs_ex4 <- as_tibble(coefs_ex4)\n#View the data frame\ncoefs_ex4\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2,000 × 7\n   sim.id estimate     se CI_2.5 CI_97.5 model coverage\n    <int>    <dbl>  <dbl>  <dbl>   <dbl> <chr> <lgl>   \n 1      1     1.37 0.0836   1.21    1.54 mod.1 NA      \n 2      1     2.88 0.119    2.65    3.11 mod.2 NA      \n 3      2     1.30 0.0874   1.13    1.47 mod.1 NA      \n 4      2     2.89 0.122    2.65    3.13 mod.2 NA      \n 5      3     1.38 0.0881   1.21    1.56 mod.1 NA      \n 6      3     3.11 0.123    2.87    3.35 mod.2 NA      \n 7      4     1.47 0.0844   1.31    1.64 mod.1 NA      \n 8      4     3.12 0.118    2.89    3.35 mod.2 NA      \n 9      5     1.33 0.0841   1.17    1.50 mod.1 NA      \n10      5     2.99 0.118    2.76    3.22 mod.2 NA      \n# ℹ 1,990 more rows\n```\n\n\n:::\n:::\n\n\n\n\nThe `coverage` is defined by setting its value to `1` if the confidence interval overlaps the data-generating parameter for `microbial aerosol` (i.e., `b_micr.resp = 3`) and `0` otherwise.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculate coverage\ncoefs_ex4 <-\n  coefs_ex4 %>%\n  mutate(coverage = case_when(CI_2.5 > b_micr.resp | CI_97.5 < b_micr.resp ~ 0,\n                              CI_2.5 <= b_micr.resp & CI_97.5 >= b_micr.resp ~ 1,\n                              .default = NA))\n#View the data frame\ncoefs_ex4\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2,000 × 7\n   sim.id estimate     se CI_2.5 CI_97.5 model coverage\n    <int>    <dbl>  <dbl>  <dbl>   <dbl> <chr>    <dbl>\n 1      1     1.37 0.0836   1.21    1.54 mod.1        0\n 2      1     2.88 0.119    2.65    3.11 mod.2        1\n 3      2     1.30 0.0874   1.13    1.47 mod.1        0\n 4      2     2.89 0.122    2.65    3.13 mod.2        1\n 5      3     1.38 0.0881   1.21    1.56 mod.1        0\n 6      3     3.11 0.123    2.87    3.35 mod.2        1\n 7      4     1.47 0.0844   1.31    1.64 mod.1        0\n 8      4     3.12 0.118    2.89    3.35 mod.2        1\n 9      5     1.33 0.0841   1.17    1.50 mod.1        0\n10      5     2.99 0.118    2.76    3.22 mod.2        1\n# ℹ 1,990 more rows\n```\n\n\n:::\n:::\n\n\n\n\nThe results are then plotted in @fig-DAG.ex4-CI.\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nmodel_names <- c('mod.1' = 'Model.1', \n                 'mod.2' = 'Model.2')\n\nggplot(data = subset(coefs_ex4, sim.id <= 2e2), aes(x = sim.id, y = estimate, ymin = CI_2.5, ymax = CI_97.5, colour = as.factor(coverage))) + \n  geom_hline(yintercept = b_micr.resp, alpha = 0.8, linetype = 'dashed', colour = 'blue') + \n  geom_linerange() +\n  geom_point(shape = 21, size = 1, fill = 'white', stroke = 0.5) +\n  scale_colour_manual('', values = c('black', '#FF4040'),\n                      breaks = c('1','0')) +\n  scale_y_continuous('Estimate',\n                     breaks = seq(from = -3, to = 3, by = 0.5)) +\n  scale_x_continuous('Simulation ID') +\n  facet_wrap(model~., \n             labeller = labeller(model = model_names),\n             nrow = 3,\n             scales = 'fixed') +\n  theme(legend.position = 'none', \n        panel.grid = element_blank(),\n        panel.background = element_blank(),\n        panel.border = element_rect(colour = 'black', fill = NA),\n        axis.title.y = element_blank())\n```\n\n::: {.cell-output-display}\n![Estimates of the microbial aerosol coefficient (only the first hundreds of the thousand simulations are shown). The white dots represent the point estimate, and the black lines represent the 95% confidence intervals. In red are highlighted the confidence intervals that do not overlap the parameter used to generate the data (dashed blue line).](ex4_simulation_files/figure-html/fig-DAG.ex4-CI-1.png){#fig-DAG.ex4-CI fig-align='center' width=5400}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n@fig-DAG.ex4-CI shows the first 200 estimates (point estimate and confidence interval) of the coefficient for microbial aerosol for `Model.1` and `Model.2`. If all the thousand simulations are considered, the frequency of the coverage of the calculated confidence intervals (i.e., how many times the confidence intervals overlap the data-generating parameter) is 0.0% and 95.3% for `Model.1` and `Model.2`, respectively. Since the estimate of the causal effect for `Model.1` are biased, the calculated confidence intervals for this model do not have the expected coverage. In fact, confidence intervals only quantify the uncertainty due to random error (i.e., sample variability), not systematic error (i.e., bias). Instead, the estimate from `Model.2` are unbiased and the calculated 95% confidence intervals have the expected coverage (i.e., overlap the data-generating parameter 95% of the times).\n\nWe can also visualize all the 1,000 estimates of the coefficient for microbial aerosol for `Model.1` and `Model.2` (the estimates were shown as white dots in @fig-DAG.ex4-CI).\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(data = coefs_ex4, aes(x = estimate, y = ifelse(after_stat(count) > 0, after_stat(count), NA))) +\n  geom_histogram(binwidth = 0.05, fill = 'white', colour = 'grey50') +\n  geom_vline(xintercept = b_micr.resp, colour = 'blue', linetype = 'dashed') +\n  scale_x_continuous('Estimate', \n                     breaks = seq(from = -5, to = 5, by = 0.5),\n                     limits = c(0.9, 3.5)) +\n  facet_grid(model~., \n             labeller = labeller(model = model_names),\n             scales = 'fixed') +\n  theme(axis.title.y = element_blank(), \n        axis.text.y = element_blank(), \n        axis.ticks.y = element_blank(),\n        panel.grid = element_blank(),\n        panel.background = element_blank(),\n        panel.border = element_rect(colour = 'black', fill = NA))\n```\n\n::: {.cell-output-display}\n![Histogram of the 1,000 estimates of the microbial aerosol coefficient for the two models. The blue dashed line represents the parameter used to generate the data.](ex4_simulation_files/figure-html/fig-DAG.ex4-mean-estimate-1.png){#fig-DAG.ex4-mean-estimate fig-align='center' width=5400}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\nIn @fig-DAG.ex4-mean-estimate, the estimated coefficients are visualized through a histogram. Here, we can see that the estimates for `Model.1` are not clustered around the data-generating parameter (blue dashed line) having a mean estimate of 1.334 (with 0.086 standard deviation). In contrast, the estimates for `Model.2` having a mean estimate of 2.999 (with 0.120 standard deviation) are centered around the data-generating parameter.\n\nAs expected, adjusting for relative humidity $(\\text{H})$ (i.e., using `Model.2`) leads to the correct estimate of the total average causal effect of microbial aerosol $(\\text{M})$ on respiratory irritation $(\\text{R})$. However, when adjusting for both relative humidity $(\\text{H})$ and absence $(\\text{A})$ (i.e., using `Model.1`) the estimates are biased. This happened because absence $(\\text{A})$ is a descendant of respiratory irritation $(\\text{R})$, which is collider. Adjusting for a descendant of a collider is akin to adjusting for the collider itself, and, therefore, can introduce a similar bias.\n\nTo better explain this bias, we can plot the magnified DAG that shows that causes of all variables.\n\n\n\n\n::: {#fig-DAG.ex4-3 .cell .fig-cap-location-bottom layout-nrow=\"2\" layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\ndag_coords.ex4.3 <-\n  data.frame(name = c('M', 'H', 'A', 'R', 'UA', 'UH', 'UM', 'UR'),\n             x = c(1, 3.5, 6, 6, 8, 3.5, 1, 8),\n             y = c(3, 2, 1, 3, 1, 1, 2, 3))\n\nDAG.ex4.3 <-\n  dagify(M ~ H + UM,\n         H ~ UH,\n         R ~ H + M + UR,\n         A ~ R + UA,\n         coords = dag_coords.ex4.3)\n\nnode_labels <- c(\n  M = 'bold(M)', \n  H = 'bold(H)', \n  A = 'bold(A)', \n  R = 'bold(R)', \n  UA = 'bold(UA)', \n  UH = 'bold(UH)', \n  UM = 'bold(UM)', \n  UR = 'bold(UR)'\n)\n\nggplot(data = DAG.ex4.3, aes(x = x, y = y, xend = xend, yend = yend)) +\n  #visualize causal effect path\n  geom_segment(x = 1, xend = 8, y = 3, yend = 3,\n               linewidth = 8, lineend = 'square', colour = '#0072B2', alpha = 0.05, linetype = 'solid') +\n  geom_point(x = 8, y = 3, shape = 1, size = 18, stroke = 0.9, color = 'black') +\n  geom_point(x = 8, y = 1, shape = 1, size = 18, stroke = 0.9, color = 'black') +\n  geom_point(x = 3.5, y = 1, shape = 1, size = 18, stroke = 0.9, color = 'black') +\n  geom_point(x = 1, y = 2, shape = 1, size = 18, stroke = 0.9, color = 'black') +\n  geom_dag_text(aes(label = node_labels[name]),\n                parse = TRUE,\n                colour = 'black',\n                size = 10,\n                family = 'mono') +\n  geom_dag_edges(arrow_directed = grid::arrow(length = grid::unit(10, 'pt'), type = 'open'),\n                 edge_colour = 'black',\n                 family = 'mono',\n                 fontface = 'bold') +\n  coord_cartesian(xlim = c(0.5, 8.5), ylim = c(0.8, 3.2))  +\n  theme_dag()\n\nggplot(data = DAG.ex4.3, aes(x = x, y = y, xend = xend, yend = yend)) +\n  #visualize causal effect path\n  geom_segment(x = 1, xend = 8.2, y = 3, yend = 3,\n               linewidth = 8, lineend = 'square', colour = '#D55E00', alpha = 0.05, linetype = '12') +\n  #latent variable\n  geom_point(x = 8, y = 3, shape = 1, size = 18, stroke = 0.9, color = 'black') +\n  geom_point(x = 8, y = 1, shape = 1, size = 18, stroke = 0.9, color = 'black') +\n  geom_point(x = 3.5, y = 1, shape = 1, size = 18, stroke = 0.9, color = 'black') +\n  geom_point(x = 1, y = 2, shape = 1, size = 18, stroke = 0.9, color = 'black') +\n  #adjusted variable\n  geom_point(x = 6, y = 1, shape = 22, size = 14, stroke = 0.9, fill = 'grey80', colour = 'black') +\n  geom_dag_text(aes(label = node_labels[name]),\n                parse = TRUE,\n                colour = 'black',\n                size = 10,\n                family = 'mono') +\n  geom_dag_edges(arrow_directed = grid::arrow(length = grid::unit(10, 'pt'), type = 'open'),\n                 edge_colour = 'black',\n                 family = 'mono',\n                 fontface = 'bold') +\n  coord_cartesian(xlim = c(0.5, 8.5), ylim = c(0.8, 3.2))  +\n  theme_dag()\n```\n\n::: {.cell-output-display}\n![](ex4_simulation_files/figure-html/fig-DAG.ex4-3-1.png){#fig-DAG.ex4-3-1 fig-align='center' width=80%}\n:::\n\n::: {.cell-output-display}\n![](ex4_simulation_files/figure-html/fig-DAG.ex4-3-2.png){#fig-DAG.ex4-3-2 fig-align='center' width=80%}\n:::\n\nMagnified graphical representation via a DAG of the causal structure. The circle represents unobserved variables; the grey-filled box indicates statistical adjustment; the solid light blue line indicates a closed path, and the dashed orange line indicates a partially open path.\n:::\n\n\n\n\n@fig-DAG.ex4-3 shows the magnified DAG with the causes for all variables. Here the causes only affect one variable (i.e., they are not shared) and are circled because they are considered unobserved. Consequently, they are generally omitted in a DAG. This structure implies that, for example, respiratory irritation $(\\text{R})$ is a function of microbial aerosol $(\\text{M})$, relative humidity $(\\text{H})$, and some unobserved influence $(\\text{u}_\\text{R})$. This unobserved influence (or set of influences) can be thought of as variations around the expected value of $\\text{R}$ for each $\\text{M}$ and $\\text{H}$.\n\nFrom @fig-DAG.ex4-3, it is clear that respiratory irritation $(\\text{R})$ is a virtual collider on the path $\\text{M} \\rightarrow \\text{R} \\leftarrow \\text{u}_\\text{R}$. This path is closed (@fig-DAG.ex4-3 (a)), but conditioning on absence $\\text{A}$ partially opens it (@fig-DAG.ex4-3 (b)). This happens because $\\text{A}$ is a descendant of $\\text{R}$, and adjusting for $\\text{A}$ is similar to adjusting for $\\text{R}$. Consequently, the non-causal path $\\text{M} \\rightarrow \\text{R} \\leftarrow \\text{u}_\\text{R}$ is now partially open, creating a spurious association between $\\text{M}$ and $\\text{u}_\\text{R}$ that distorts the estimate of the causal effect of $\\text{M}$ on $\\text{R}$. This is why the estimates from `Model.1` are biased. Following the backdoor criterion, we should not adjust for any descendant of the cause of interest. Since `Model.2` does not include absence, which is a descendant of microbial aerosol (i.e., $\\text{M} \\rightarrow \\text{R} \\rightarrow \\text{A}$), the estimates from this model are unbiased.\n\n</details>\n\n#### Bayesian framework\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Fit the linear regression model with M, H, A and R (Model 1)\nex4_Model.1 <- stan_glm(formula = R ~ M + H + A,\n                        family = gaussian(),\n                        data = ex4_sample.random,\n                        #Prior coefficients\n                        prior = normal(location = c(0, 0, 0), scale = c(6, 1, 4)),\n                        #Prior intercept\n                        prior_intercept = normal(location = 0, scale = 2),\n                        #Prior sigma\n                        prior_aux = exponential(rate = 0.5),\n                        iter = 4000, warmup = 1000, \n                        save_warmup = TRUE,\n                        chains = 4, cores = 4,\n                        seed = 2025) #for reproducibility\n#View of the model\nex4_Model.1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstan_glm\n family:       gaussian [identity]\n formula:      R ~ M + H + A\n observations: 5000\n predictors:   4\n------\n            Median MAD_SD\n(Intercept) -2.9    0.1  \nMhigh        1.4    0.1  \nHlow         0.3    0.1  \nAyes         4.6    0.1  \n\nAuxiliary parameter(s):\n      Median MAD_SD\nsigma 2.0    0.0   \n\n------\n* For help interpreting the printed output see ?print.stanreg\n* For info on the priors used see ?prior_summary.stanreg\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Fit the linear regression model with M, H and R (Model 2)\nex4_Model.2 <- stan_glm(formula = R ~ M + H,\n                        family = gaussian(),\n                        data = ex4_sample.random,\n                        #Prior coefficients\n                        prior = normal(location = c(0, 0), scale = c(6, 1)),\n                        #Prior intercept\n                        prior_intercept = normal(location = 0, scale = 2),\n                        #Prior sigma\n                        prior_aux = exponential(rate = 0.5),\n                        iter = 4000, warmup = 1000, \n                        save_warmup = TRUE,\n                        chains = 4, cores = 4,\n                        seed = 2025) #for reproducibility \n#View of the model\nex4_Model.2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstan_glm\n family:       gaussian [identity]\n formula:      R ~ M + H\n observations: 5000\n predictors:   3\n------\n            Median MAD_SD\n(Intercept) -1.0    0.1  \nMhigh        2.9    0.1  \nHlow         0.5    0.1  \n\nAuxiliary parameter(s):\n      Median MAD_SD\nsigma 2.9    0.0   \n\n------\n* For help interpreting the printed output see ?print.stanreg\n* For info on the priors used see ?prior_summary.stanreg\n```\n\n\n:::\n:::\n\n\n\n\nIn Bayesian analysis, there are important diagnostics that have to be carried out in order to assess the convergence and efficiency of the Markov Chains. This is done by using the `monitor()` function which computes summaries of MCMC (Markov Chain Monte Carlo) draws and monitor convergence. Specifically, we will look at `Rhat`, `Bulk_ESS` and `Tail_ESS` metrics.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Diagnostics for model 1\nmonitor(ex4_Model.1$stanfit)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInference for the input samples (4 chains: each with iter = 4000; warmup = 0):\n\n                    Q5      Q50      Q95     Mean  SD  Rhat Bulk_ESS Tail_ESS\n(Intercept)       -3.1     -2.9     -2.8     -2.9 0.1     1     8175     7548\nMhigh              1.2      1.4      1.5      1.4 0.1     1     7316     7632\nHlow               0.2      0.3      0.5      0.3 0.1     1     7483     8012\nAyes               4.5      4.6      4.7      4.6 0.1     1    11050     7932\nsigma              2.0      2.0      2.0      2.0 0.0     1    12676     9141\nmean_PPD           0.7      0.8      0.9      0.8 0.0     1    12106    11301\nlog-posterior -10602.1 -10598.7 -10597.1 -10599.0 1.6     1     5391     7209\n\nFor each parameter, Bulk_ESS and Tail_ESS are crude measures of \neffective sample size for bulk and tail quantities respectively (an ESS > 100 \nper chain is considered good), and Rhat is the potential scale reduction \nfactor on rank normalized split chains (at convergence, Rhat <= 1.05).\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Diagnostics for model 2\nmonitor(ex4_Model.2$stanfit) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInference for the input samples (4 chains: each with iter = 4000; warmup = 0):\n\n                    Q5      Q50      Q95     Mean  SD  Rhat Bulk_ESS Tail_ESS\n(Intercept)       -1.2     -1.0     -0.8     -1.0 0.1     1     6384     7117\nMhigh              2.7      2.9      3.1      2.9 0.1     1     6823     7134\nHlow               0.3      0.5      0.7      0.5 0.1     1     7009     7386\nsigma              2.9      2.9      3.0      2.9 0.0     1     9718     8191\nmean_PPD           0.7      0.8      0.9      0.8 0.1     1    10639    10331\nlog-posterior -12501.9 -12498.9 -12497.6 -12499.2 1.4     1     5257     6747\n\nFor each parameter, Bulk_ESS and Tail_ESS are crude measures of \neffective sample size for bulk and tail quantities respectively (an ESS > 100 \nper chain is considered good), and Rhat is the potential scale reduction \nfactor on rank normalized split chains (at convergence, Rhat <= 1.05).\n```\n\n\n:::\n:::\n\n\n\n\n`Rhat` is a metric used to assess the convergence of Markov Chain Monte Carlo (MCMC) simulations. It helps determine if the MCMC chains have adequately explored the target posterior distribution. Specifically, it compares the between- and within-chain estimates for model parameters: If chains have not mixed well (i.e., the between- and within-chain estimates do not agree), R-hat is larger than 1. A general rule of thumb is to use the sample only if R-hat is less than 1.05; a larger value suggests that the chains have not mixed well, and the results might not be reliable. In our two models, all `Rhat` are equal to 1 indicating that the chains have mixed well and have adequately explored the target posterior distribution.\n\n`Bulk_ESS` and `Tail_ESS` stand for 'Bulk Effective Sample Size' and 'Tail Effective Sample Size,' respectively. Since MCMC samples are not truly independent (they are correlated), these metrics assess the sampling efficiencies, that is, they help evaluating how efficiently the MCMC sampler is exploring the parameters space.\n\n-   `Bulk_ESS` is a useful measure for sampling efficiency in the bulk (center) of the distribution (e.g., efficiency of mean and median estimates);\n-   `Tail_ESS` is a useful measure for sampling efficiency in the tails of the distribution (e.g., efficiency of variance and tail quantile estimates). A general rule of thumb is that both `Bulk-ESS` and `Tail-ESS` should be at least 100 (approximately) per Markov Chain in order to be reliable and indicate that estimates of respective posterior quantiles are reliable. In our two models, all `Bulk-ESS` and `Tail-ESS` are well above 400 (i.e., 100 multiplied by 4, the number of chains we used) indicating that estimates of posterior quantiles are reliable.\n\nSince we have established that the posteriors are reliable, we can now explore the model estimates. The estimated coefficients for the two models are then plotted in @fig-DAG.ex4-estimate-Bayesian.\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#Extract draws from model 1 \npost_ex4_Model.1 <-\n  ex4_Model.1 %>% \n  spread_draws(Mhigh) %>% #extract draws from the fitted model\n  mutate(model = 'Model.1') #add a new column to specify that the model\n\n#Extract draws from model 2\npost_ex4_Model.2 <-\n  ex4_Model.2 %>% \n  spread_draws(Mhigh) %>% #extract draws from the fitted model\n  mutate(model = 'Model.2') #add a new column to specify that the model\n\n#Combine draws\nplot.post <- rbind(post_ex4_Model.1, post_ex4_Model.2)\n\n# Plot\nplot.post  %>%\n  ggplot(aes(y = model, x = Mhigh)) +\n  stat_slabinterval(point_interval = 'mean_hdi',\n                    .width = c(.95)) +\n  geom_vline(xintercept = b_micr.resp, alpha = 0.8, linetype = 'dashed', colour = 'blue') + \n  scale_x_continuous('Estimate', \n                     breaks = seq(from = -5, to = 5, by = 0.5),\n                     limits = c(0.5, 3.5)) +\n  theme(panel.grid = element_blank(),\n        panel.background = element_blank(),\n        panel.border = element_rect(colour = 'black', fill = NA),\n        axis.title.y = element_blank())\n```\n\n::: {.cell-output-display}\n![Posterior distribution of the microbial aerosol coefficient for the two models. The black line and dot at the bottom of each distribution represent the highest density interval (HDI) and the mean, respectively.](ex4_simulation_files/figure-html/fig-DAG.ex4-estimate-Bayesian-1.png){#fig-DAG.ex4-estimate-Bayesian fig-align='center' width=5400}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n@fig-DAG.ex4-estimate-Bayesian shows the estimates (mean and 95% HDI) of the coefficient for microbial aerosol for `Model.1`, and `Model.2`.\n\nFor `Model.1` we found a positive coefficient between microbial aerosol $(\\text{M})$ and respiratory irritation $(\\text{R})$ (mean = 1.372, 95% HDI \\[1.203, 1.533\\]). The estimated causal effect is biased, leading to the wrong conclusion that changing microbial aerosol from `low` to `high` causes an increase in lung infection by 1.372 units, on average.\n\nFor `Model.2` we found a positive coefficient between microbial aerosol $(\\text{M})$ and respiratory irritation $(\\text{R})$ (mean = 2.875, 95% HDI \\[2.640, 3.101\\]). The estimated causal effect is unbiased, leading to the correct conclusion that changing microbial aerosol from `low` to `high` causes an increase in lung infection by 2.875 units, on average.\n\nImportantly, for both `Model.1` and `Model.1`, the 95% HDI is the range of parameter values within which the most credible 95% of the posterior distribution falls. Unlike frequentist confidence interval, the Bayesian 95% HDI has a direct probabilistic meaning: every point inside the HDI has a higher probability density than any point outside the interval. Therefore, given the model, the prior and the data, we can say that there is a 95% probability that the data-generating parameter (i.e., `b_micr.resp = 3`) lies within the HDI. However, since `Model.1` leads to a biased estimate, we will reach the wrong conclusion by stating that there is a 95% probability that the data-generating parameter lies within the \\[1.203, 1.533\\] interval. This probability is 0%.\n\nAs expected, adjusting for relative humidity $(\\text{H})$ (i.e., using `Model.2`) leads to the correct estimate of the total average causal effect of microbial aerosol $(\\text{M})$ on respiratory irritation $(\\text{R})$. However, when adjusting for both relative humidity $(\\text{H})$ and absence $(\\text{A})$ (i.e., using `Model.1`) the estimates are biased. This happened because absence $(\\text{A})$ is a descendant of respiratory irritation $(\\text{R})$, which is collider. Adjusting for a descendant of a collider is akin to adjusting for the collider itself, and, therefore, can introduce a similar bias.\n\nTo better explain this bias, we can plot the magnified DAG that shows that causes of all variables.\n\n\n\n\n::: {#fig-DAG.ex4-3-Bayesian .cell .fig-cap-location-bottom layout-nrow=\"2\" layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\ndag_coords.ex4.3 <-\n  data.frame(name = c('M', 'H', 'A', 'R', 'UA', 'UH', 'UM', 'UR'),\n             x = c(1, 3.5, 6, 6, 8, 3.5, 1, 8),\n             y = c(3, 2, 1, 3, 1, 1, 2, 3))\n\nDAG.ex4.3 <-\n  dagify(M ~ H + UM,\n         H ~ UH,\n         R ~ H + M + UR,\n         A ~ R + UA,\n         coords = dag_coords.ex4.3)\n\nnode_labels <- c(\n  M = 'bold(M)', \n  H = 'bold(H)', \n  A = 'bold(A)', \n  R = 'bold(R)', \n  UA = 'bold(UA)', \n  UH = 'bold(UH)', \n  UM = 'bold(UM)', \n  UR = 'bold(UR)'\n)\n\nggplot(data = DAG.ex4.3, aes(x = x, y = y, xend = xend, yend = yend)) +\n  #visualize causal effect path\n  geom_segment(x = 1, xend = 8, y = 3, yend = 3,\n               linewidth = 8, lineend = 'square', colour = '#0072B2', alpha = 0.05, linetype = 'solid') +\n  geom_point(x = 8, y = 3, shape = 1, size = 18, stroke = 0.9, color = 'black') +\n  geom_point(x = 8, y = 1, shape = 1, size = 18, stroke = 0.9, color = 'black') +\n  geom_point(x = 3.5, y = 1, shape = 1, size = 18, stroke = 0.9, color = 'black') +\n  geom_point(x = 1, y = 2, shape = 1, size = 18, stroke = 0.9, color = 'black') +\n  geom_dag_text(aes(label = node_labels[name]),\n                parse = TRUE,\n                colour = 'black',\n                size = 10,\n                family = 'mono') +\n  geom_dag_edges(arrow_directed = grid::arrow(length = grid::unit(10, 'pt'), type = 'open'),\n                 edge_colour = 'black',\n                 family = 'mono',\n                 fontface = 'bold') +\n  coord_cartesian(xlim = c(0.5, 8.5), ylim = c(0.8, 3.2))  +\n  theme_dag()\n\nggplot(data = DAG.ex4.3, aes(x = x, y = y, xend = xend, yend = yend)) +\n  #visualize causal effect path\n  geom_segment(x = 1, xend = 8.2, y = 3, yend = 3,\n               linewidth = 8, lineend = 'square', colour = '#D55E00', alpha = 0.05, linetype = '12') +\n  #latent variable\n  geom_point(x = 8, y = 3, shape = 1, size = 18, stroke = 0.9, color = 'black') +\n  geom_point(x = 8, y = 1, shape = 1, size = 18, stroke = 0.9, color = 'black') +\n  geom_point(x = 3.5, y = 1, shape = 1, size = 18, stroke = 0.9, color = 'black') +\n  geom_point(x = 1, y = 2, shape = 1, size = 18, stroke = 0.9, color = 'black') +\n  #adjusted variable\n  geom_point(x = 6, y = 1, shape = 22, size = 14, stroke = 0.9, fill = 'grey80', colour = 'black') +\n  geom_dag_text(aes(label = node_labels[name]),\n                parse = TRUE,\n                colour = 'black',\n                size = 10,\n                family = 'mono') +\n  geom_dag_edges(arrow_directed = grid::arrow(length = grid::unit(10, 'pt'), type = 'open'),\n                 edge_colour = 'black',\n                 family = 'mono',\n                 fontface = 'bold') +\n  coord_cartesian(xlim = c(0.5, 8.5), ylim = c(0.8, 3.2))  +\n  theme_dag()\n```\n\n::: {.cell-output-display}\n![](ex4_simulation_files/figure-html/fig-DAG.ex4-3-Bayesian-1.png){#fig-DAG.ex4-3-Bayesian-1 fig-align='center' width=80%}\n:::\n\n::: {.cell-output-display}\n![](ex4_simulation_files/figure-html/fig-DAG.ex4-3-Bayesian-2.png){#fig-DAG.ex4-3-Bayesian-2 fig-align='center' width=80%}\n:::\n\nMagnified graphical representation via a DAG of the causal structure. The circle represents unobserved variables; the grey-filled box indicates statistical adjustment; the solid light blue line indicates a closed path, and the dashed orange line indicates a partially open path.\n:::\n\n\n\n\n@fig-DAG.ex4-3-Bayesian shows the magnified DAG with the causes for all variables. Here the causes only affect one variable (i.e., they are not shared) and are circled because they are considered unobserved. Consequently, they are generally omitted in a DAG. This structure implies that, for example, respiratory irritation $(\\text{R})$ is a function of microbial aerosol $(\\text{M})$, relative humidity $(\\text{H})$, and some unobserved influence $(\\text{u}_\\text{R})$. This unobserved influence (or set of influences) can be thought of as variations around the expected value of $\\text{R}$ for each $\\text{M}$ and $\\text{H}$.\n\nFrom @fig-DAG.ex4-3, it is clear that respiratory irritation $(\\text{R})$ is a virtual collider on the path $\\text{M} \\rightarrow \\text{R} \\leftarrow \\text{u}_\\text{R}$. This path is closed (@fig-DAG.ex4-3-Bayesian (a)), but conditioning on absence $\\text{A}$ partially opens it (@fig-DAG.ex4-3-Bayesian (b)). This happens because $\\text{A}$ is a descendant of $\\text{R}$, and adjusting for $\\text{A}$ is similar to adjusting for $\\text{R}$. Consequently, the non-causal path $\\text{M} \\rightarrow \\text{R} \\leftarrow \\text{u}_\\text{R}$ is now partially open, creating a spurious association between $\\text{M}$ and $\\text{u}_\\text{R}$ that distorts the estimate of the causal effect of $\\text{M}$ on $\\text{R}$. This is why the estimates from `Model.1` are biased. Following the backdoor criterion, we should not adjust for any descendant of the cause of interest. Since `Model.2` does not include absence, which is a descendant of microbial aerosol (i.e., $\\text{M} \\rightarrow \\text{R} \\rightarrow \\text{A}$), the estimates from this model are unbiased.\n\n## Session info {.unnumbered}\n\nVersion information about R, the OS and attached or loaded packages.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.2.3 (2023-03-15 ucrt)\nPlatform: x86_64-w64-mingw32/x64 (64-bit)\nRunning under: Windows 10 x64 (build 26200)\n\nMatrix products: default\n\nlocale:\n[1] LC_COLLATE=English_United Kingdom.utf8 \n[2] LC_CTYPE=English_United Kingdom.utf8   \n[3] LC_MONETARY=English_United Kingdom.utf8\n[4] LC_NUMERIC=C                           \n[5] LC_TIME=English_United Kingdom.utf8    \n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] rstan_2.32.7        StanHeaders_2.32.10 gt_1.1.0           \n [4] lubridate_1.9.4     forcats_1.0.1       stringr_1.6.0      \n [7] dplyr_1.1.4         purrr_1.2.0         readr_2.1.6        \n[10] tidyr_1.3.1         tibble_3.3.0        ggplot2_4.0.1      \n[13] tidyverse_2.0.0     ggdist_3.3.3        tidybayes_3.0.7    \n[16] rstanarm_2.32.2     Rcpp_1.1.0          dagitty_0.3-4      \n[19] ggdag_0.2.13       \n\nloaded via a namespace (and not attached):\n  [1] backports_1.5.0       plyr_1.8.9            igraph_2.2.1         \n  [4] splines_4.2.3         svUnit_1.0.8          crosstalk_1.2.2      \n  [7] rstantools_2.5.0      inline_0.3.21         digest_0.6.38        \n [10] htmltools_0.5.8.1     viridis_0.6.5         magrittr_2.0.4       \n [13] checkmate_2.3.3       memoise_2.0.1         tzdb_0.5.0           \n [16] graphlayouts_1.2.2    RcppParallel_5.1.11-1 matrixStats_1.5.0    \n [19] xts_0.14.1            timechange_0.3.0      colorspace_2.1-2     \n [22] ggrepel_0.9.6         rbibutils_2.4         xfun_0.54            \n [25] jsonlite_2.0.0        lme4_1.1-37           survival_3.8-3       \n [28] zoo_1.8-14            glue_1.8.0            reformulas_0.4.2     \n [31] polyclip_1.10-7       gtable_0.3.6          V8_8.0.1             \n [34] distributional_0.5.0  car_3.1-3             pkgbuild_1.4.8       \n [37] abind_1.4-8           scales_1.4.0          miniUI_0.1.2         \n [40] viridisLite_0.4.2     xtable_1.8-4          Formula_1.2-5        \n [43] stats4_4.2.3          DT_0.34.0             htmlwidgets_1.6.4    \n [46] threejs_0.3.4         arrayhelpers_1.1-0    RColorBrewer_1.1-3   \n [49] posterior_1.6.1       pkgconfig_2.0.3       loo_2.8.0            \n [52] farver_2.1.2          sass_0.4.10           utf8_1.2.6           \n [55] tidyselect_1.2.1      labeling_0.4.3        rlang_1.1.6          \n [58] reshape2_1.4.5        later_1.4.4           tools_4.2.3          \n [61] cachem_1.1.0          cli_3.6.5             generics_0.1.4       \n [64] evaluate_1.0.5        fastmap_1.2.0         yaml_2.3.10          \n [67] knitr_1.50            fs_1.6.6              tidygraph_1.3.1      \n [70] ggraph_2.2.2          nlme_3.1-168          mime_0.13            \n [73] xml2_1.5.0            compiler_4.2.3        bayesplot_1.14.0     \n [76] shinythemes_1.2.0     rstudioapi_0.17.1     curl_7.0.0           \n [79] tweenr_2.0.3          stringi_1.8.7         lattice_0.22-7       \n [82] Matrix_1.6-5          nloptr_2.2.1          markdown_2.0         \n [85] shinyjs_2.1.0         tensorA_0.36.2.1      vctrs_0.6.5          \n [88] pillar_1.11.1         lifecycle_1.0.4       Rdpack_2.6.4         \n [91] httpuv_1.6.16         QuickJSR_1.8.1        R6_2.6.1             \n [94] promises_1.5.0        gridExtra_2.3         codetools_0.2-20     \n [97] boot_1.3-32           colourpicker_1.3.0    MASS_7.3-58.2        \n[100] gtools_3.9.5          withr_3.0.2           shinystan_2.6.0      \n[103] parallel_4.2.3        hms_1.1.4             grid_4.2.3           \n[106] coda_0.19-4.1         minqa_1.2.8           rmarkdown_2.30       \n[109] S7_0.2.1              carData_3.0-5         otel_0.2.0           \n[112] ggforce_0.5.0         shiny_1.11.1          base64enc_0.1-3      \n[115] dygraphs_1.1.1.6     \n```\n\n\n:::\n:::\n",
    "supporting": [
      "ex4_simulation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}