{
  "hash": "6e87a98168150f9a02931cc2230f6d67",
  "result": {
    "engine": "knitr",
    "markdown": "# Simulation example {#sec-ex1}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Load packages\nlibrary(ggdag)\nlibrary(dagitty)\nlibrary(rstanarm)\nlibrary(tidybayes)\nlibrary(ggdist)\nlibrary(tidyverse)\nlibrary(gt)\nlibrary(rstan)\n```\n:::\n\n\n\n\n## Data-generating process\n\nThe data-generating process is described via the directed acyclic graph (DAG) in @fig-DAG.ex1-1. In this DAG, indoor air temperature $(\\text{T})$ influences productivity $(\\text{P})$ directly, while HVAC system $(\\text{H})$ influences productivity $(\\text{P})$ both directly (e.g., with air distribution and noise) and indirectly, passing through indoor air temperature $(\\text{T})$.\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\ndag_coords.ex1 <-\n  data.frame(name = c('T', 'H', 'P'),\n             x = c(1, 3.5, 6),\n             y = c(1, 3, 1))\n\nDAG.ex1 <-\n  dagify(T ~ H,\n         P ~ T + H,\n         coords = dag_coords.ex1)\n\nnode_labels <- c(\n  T = 'bold(T)', \n  H = 'bold(H)', \n  P = 'bold(P)'\n)\n\n\nggplot(data = DAG.ex1, aes(x = x, y = y, xend = xend, yend = yend)) +\n  geom_dag_text(aes(label = node_labels[name]),\n                parse = TRUE,\n                colour = 'black',\n                size = 10,\n                family = 'mono') +\n  geom_dag_edges(arrow_directed = grid::arrow(length = grid::unit(10, 'pt'), type = 'open'),\n                 edge_colour = 'black',\n                 family = 'mono',\n                 fontface = 'bold') +\n  annotate('text', x = 1, y = 0.7, label = 'indoor air temperature', \n           size = 4, hjust = 0.4, colour = 'grey50') +\n  annotate('text', x = 3.5, y = 3.3, label = 'HVAC system', \n           size = 4, hjust = 0.5, colour = 'grey50') +\n  annotate('text', x = 6, y = 0.7, label = 'productivity', \n           size = 4, hjust = 0.5, colour = 'grey50') +\n  coord_cartesian(xlim = c(0.5, 6.5), ylim = c(0.8, 3.2))  +\n  theme_dag()\n```\n\n::: {.cell-output-display}\n![Graphical representation via DAG of the data-generating process.](ex1_simulation_files/figure-html/fig-DAG.ex1-1-1.png){#fig-DAG.ex1-1 fig-align='center' width=60%}\n:::\n:::\n\n\n\n\nThe DAG in @fig-DAG.ex1-1 can be written as:\n\n-   $T \\sim f_{T}(H)$, read as 'indoor air temperature $(\\text{T})$ is some function of HVAC system $(\\text{H})$'.\n-   $P \\sim f_{P}(T, H)$, read as 'productivity $(\\text{P})$ is some function of indoor air temperature $(\\text{T})$ and HVAC system $(\\text{H})$'.\n\n## Synthetic data set\n\nTo generate synthetic data, we defined the custom function `data.sim_ex1()`. This function takes as inputs the sample size `n` and generates synthetic data according to the DAG in @fig-DAG.ex1-1.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.sim_ex1 <- function(n) {\n  b_hvac.prod = c(0, 5) #direct causal effect of H on P\n  b_temp.prod = -1 #direct causal effect of T on P\n  #Simulate HVAC\n  H <- factor(sample(c('classic', 'alternative'), size = n, replace = TRUE))  \n  #Simulate indoor air temperature\n  T <- rnorm(n = n, mean = ifelse(H == 'classic', 21, 22), sd = 0.7)\n  #Simulate productivity\n  P <- rnorm(n = n, mean = ifelse(H == 'classic', 75 + b_hvac.prod[1] + b_temp.prod * T, 75 + b_hvac.prod[2] + b_temp.prod * T), sd = 2)  \n  #Return tibble with simulated values\n  return(tibble(H, T, P))\n  }\n```\n:::\n\n\n\n\nFrom this data generation mechanism, we simulated the target population, which consists of one million observations.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2025) #set random number for reproducibility\n#Simulate the population\nex1_population <- data.sim_ex1(n = 1e6)\n#Set HVAC reference category to 'classic'\nex1_population$H <- relevel(ex1_population$H, ref = 'classic')\n#View the data frame\nex1_population\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,000,000 × 3\n   H               T     P\n   <fct>       <dbl> <dbl>\n 1 classic      20.6  51.1\n 2 alternative  21.6  56.4\n 3 alternative  22.3  58.2\n 4 alternative  21.1  56.8\n 5 classic      20.6  55.7\n 6 classic      20.0  53.0\n 7 alternative  21.8  56.4\n 8 classic      21.7  53.9\n 9 alternative  21.5  55.3\n10 classic      20.5  57.4\n# ℹ 999,990 more rows\n```\n\n\n:::\n:::\n\n\n\n\nFrom this population, we obtained one data set of five thousand observations using simple random sampling.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_sims <- 1e3 #number of data sets to simulate\n\n#Set random number for reproducibility\nset.seed(2025)  \n#Generate a vector of random numbers for reproducibility\nex1_random.seed <- sample(1:1e5, size = n_sims, replace = FALSE)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(ex1_random.seed[1])\n#Sample one data set of 5,000 observations\nex1_sample.random <- \n  ex1_population %>% \n  slice_sample(n = 5e3) #take a simple random sample of size 5,000 \n\n#View the data frame\nex1_sample.random\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,000 × 3\n   H               T     P\n   <fct>       <dbl> <dbl>\n 1 alternative  22.6  54.3\n 2 classic      21.3  53.3\n 3 classic      21.5  53.7\n 4 alternative  22.5  58.2\n 5 classic      22.5  55.6\n 6 classic      21.3  52.1\n 7 alternative  21.7  60.3\n 8 classic      22.9  55.3\n 9 alternative  22.7  58.6\n10 classic      19.9  55.8\n# ℹ 4,990 more rows\n```\n\n\n:::\n:::\n\n\n\n\n## Data analysis\n\nIn this example, the target of our analysis is the total average causal effect, ACE (also known as total average treatment effect, ATE) of indoor air temperature $(\\text{T})$ on productivity $(\\text{P})$, which stands for the expected increase of $\\text{P}$ in response to a unit increase in $\\text{T}$ due to an intervention. The causal effect of interest is visualized in @fig-DAG.ex1-2.\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(data = DAG.ex1, aes(x = x, y = y, xend = xend, yend = yend)) +\n  #visualize causal effect path\n  geom_segment(x = 1, xend = 6, y = 1, yend = 1,\n               linewidth = 14, lineend = 'round', colour = '#009E73', alpha = 0.05) +\n  geom_dag_text(aes(label = node_labels[name]),\n                parse = TRUE,\n                colour = 'black',\n                size = 10,\n                family = 'mono') +\n  geom_dag_edges(arrow_directed = grid::arrow(length = grid::unit(10, 'pt'), type = 'open'),\n                 edge_colour = 'black',\n                 family = 'mono',\n                 fontface = 'bold') +\n  annotate('text', x = 1, y = 0.7, label = 'indoor air temperature', \n           size = 4, hjust = 0.4, colour = 'grey50') +\n  annotate('text', x = 3.5, y = 3.3, label = 'HVAC system', \n           size = 4, hjust = 0.5, colour = 'grey50') +\n  annotate('text', x = 6, y = 0.7, label = 'productivity', \n           size = 4, hjust = 0.5, colour = 'grey50') +\n  #causal effect number\n  annotate('text', x = 3.5, y = 1.2, label = '-1', \n           size = 4.5, hjust = 0.5, colour = 'black', parse = TRUE) +\n\n  coord_cartesian(xlim = c(0.5, 6.5), ylim = c(0.8, 3.2))  +\n  theme_dag()\n```\n\n::: {.cell-output-display}\n![Graphical representation via DAG of the data-generating process. The green line indicates the causal question of interest, and the number on the path indicates the total average causal effect.](ex1_simulation_files/figure-html/fig-DAG.ex1-2-1.png){#fig-DAG.ex1-2 fig-align='center' width=60%}\n:::\n:::\n\n\n\n\n### Identification\n\nThe first step to answer the causal question of interest is identification. Identification answers a ‘theoretical’ question by determining whether a causal effect can, in principle, be estimated from observed data. The backdoor criterion and its generalization, the adjustment criterion, allow us to understand whether our causal effect of interest can be identified and, if so, which variables we should (or should not) statistically adjust for (i.e., the adjustment set) to estimate the causal effect from the data.\n\nGiven its simplicity, we will first apply the backdoor criterion to identify valid adjustment sets to estimate the causal effect of interest. If the backdoor criterion is not applicable, we will apply its generalization, the adjustment criterion.\n\n#### Backdoor criterion\n\nApplying the backdoor criterion revealed the existence of a backdoor path (i.e., a non-causal path) from indoor air temperature $(\\text{T})$ to productivity $(\\text{P})$. Specifically, the backdoor path is $\\text{T} \\leftarrow \\text{H} \\rightarrow \\text{P}$. Since HVAC system $(\\text{H})$ is a common cause of $\\text{T}$ and $\\text{P}$, association can flow from $\\text{T}$ to $\\text{P}$ through $\\text{H}$. As a result, there is confounding. To close this backdoor path we need to adjust for $\\text{H}$.\n\nGiven the DAG in @fig-DAG.ex1-2, we can use the `adjustmentSets()` function to identify the adjustment set algorithmically. It is essential to note that this function applies the adjustment criterion and not the backdoor criterion. As such, the `adjustmentSets()` function can find adjustment sets even when the backdoor criterion is not applicable.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nadjustmentSets(DAG.ex1,\n               exposure = 'T', #indoor air temperature\n               outcome = 'P', #productivity\n               type = 'all', \n               effect = 'total', \n               max.results = Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{ H }\n```\n\n\n:::\n:::\n\n\n\n\nAs expected, the resulting adjustment set includes HVAC system $(\\text{H})$. Therefore, to get the correct estimate of the total average causal effect, we need to adjust for $\\text{H}$; failing to do so will lead to bias.\n\n### Estimation\n\nFollowing the identification step is the estimation step. This step addresses a statistical question by determining how the causal effect identified in the previous step can be estimated. To perform this step, we used a parametric (model-based) estimator, specifically, linear regression. This was possible because we designed the illustrative examples to be simple and with a linear relationship between the variables. This way, we limited the complexity of the examples themselves and shifted the focus to the application of the backdoor criterion to define 'correct' adjustment sets.\n\nFor transparency and understanding, all (implicit) assumptions used for this illustrative example are (explicitly) provided in @tbl-summary.ex1.\n\n\n\n\n::: {#tbl-summary.ex1 .cell tbl-cap='Summary description of the simulation example'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"pefclyqint\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#pefclyqint table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#pefclyqint thead, #pefclyqint tbody, #pefclyqint tfoot, #pefclyqint tr, #pefclyqint td, #pefclyqint th {\n  border-style: none;\n}\n\n#pefclyqint p {\n  margin: 0;\n  padding: 0;\n}\n\n#pefclyqint .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#pefclyqint .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#pefclyqint .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#pefclyqint .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#pefclyqint .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pefclyqint .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pefclyqint .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pefclyqint .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#pefclyqint .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#pefclyqint .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#pefclyqint .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#pefclyqint .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#pefclyqint .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#pefclyqint .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#pefclyqint .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#pefclyqint .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#pefclyqint .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#pefclyqint .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#pefclyqint .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pefclyqint .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#pefclyqint .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#pefclyqint .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#pefclyqint .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pefclyqint .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#pefclyqint .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#pefclyqint .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pefclyqint .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pefclyqint .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#pefclyqint .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pefclyqint .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#pefclyqint .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pefclyqint .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pefclyqint .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pefclyqint .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pefclyqint .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pefclyqint .gt_left {\n  text-align: left;\n}\n\n#pefclyqint .gt_center {\n  text-align: center;\n}\n\n#pefclyqint .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#pefclyqint .gt_font_normal {\n  font-weight: normal;\n}\n\n#pefclyqint .gt_font_bold {\n  font-weight: bold;\n}\n\n#pefclyqint .gt_font_italic {\n  font-style: italic;\n}\n\n#pefclyqint .gt_super {\n  font-size: 65%;\n}\n\n#pefclyqint .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#pefclyqint .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#pefclyqint .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#pefclyqint .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#pefclyqint .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#pefclyqint .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#pefclyqint .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#pefclyqint .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#pefclyqint div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" style=\"table-layout:fixed;\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <colgroup>\n    <col style=\"width:22%;\"/>\n    <col/>\n  </colgroup>\n  \n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"vertical-align: top; font-weight: bold; background-color: #FFFFFF;\">Research question</td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Total average causal effect (ACE) of indoor air temperature (T) on productivity (P).</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"vertical-align: top; font-weight: bold; background-color: #FFFFFF;\">Assumptions</td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Random sample (simple random sampling): everyone in the population has an equal chance of being selected into the sample.</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Limited random variability: large sample size.</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Independence of observations: each observation represents independent bits of information.</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">No confounding: the DAG includes all shared causes among the variables.</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">No model error: perfect functional form specification.</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">No measurement error: all variables are measured perfectly.</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"vertical-align: top; font-weight: bold; background-color: #FFFFFF;\">Variables</td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Indoor air temperature (T): continuous variable [unit: °C]</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">HVAC (H): categorical variable ['classic'; 'alternative']</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Productivity (P): continuous variable [unit: -]</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nTo carry out the estimation step, we utilized linear regression within both the frequentist and Bayesian frameworks. Specifically, we will run two regression models:\n\n-   `Model.1` will include only indoor air temperature $(\\text{T})$ as predictor;\n-   `Model.2` will include both indoor air temperature $(\\text{T})$ and HVAC system $(\\text{H})$ as predictors.\n\nThe results of the fitted statistical models (i.e., `Model.1` and `Model.2`) are presented here.\n\n#### Frequentist framework\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Fit the linear regression model with T and P (Model 1)\nex1_Model.1 <-\n  lm(formula = P ~ T,\n     data = ex1_sample.random)\n#View of the model summary\nsummary(ex1_Model.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = P ~ T, data = ex1_sample.random)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-9.7246 -2.0653  0.0144  1.9700 10.0478 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 40.56735    1.00976   40.17   <2e-16 ***\nT            0.71541    0.04693   15.24   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.869 on 4998 degrees of freedom\nMultiple R-squared:  0.04443,\tAdjusted R-squared:  0.04423 \nF-statistic: 232.4 on 1 and 4998 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Fit the linear regression model with T , H and P (Model 2)\nex1_Model.2 <-\n  lm(formula = P ~ T + H,\n     data = ex1_sample.random)\n#View of the model summary\nsummary(ex1_Model.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = P ~ T + H, data = ex1_sample.random)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-6.6805 -1.3390 -0.0401  1.3199  8.8070 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  75.15431    0.84857   88.56   <2e-16 ***\nT            -1.00927    0.04036  -25.00   <2e-16 ***\nHalternative  5.08393    0.06979   72.84   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.998 on 4997 degrees of freedom\nMultiple R-squared:  0.5365,\tAdjusted R-squared:  0.5364 \nF-statistic:  2892 on 2 and 4997 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nThe estimated coefficients for the two models are then plotted in @fig-DAG.ex1-estimate.\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nb_temp.prod = -1 \n\ndata.frame(model = c('Model.1', 'Model.2'),\n           estimate = c(coef(ex1_Model.1)['T'], coef(ex1_Model.2)['T']),\n           lower.95.CI = c(confint(ex1_Model.1, level = 0.95, type = 'Wald')['T', 1], confint(ex1_Model.2, level = 0.95, type = 'Wald')['T', 1]),\n           upper.95.CI = c(confint(ex1_Model.1, level = 0.95, type = 'Wald')['T', 2], confint(ex1_Model.2, level = 0.95, type = 'Wald')['T', 2])) %>%\n  \nggplot(aes(x = estimate, y = model, xmin = lower.95.CI, xmax = upper.95.CI)) + \n  geom_vline(xintercept = b_temp.prod, alpha = 0.8, linetype = 'dashed', colour = 'blue') + \n  geom_linerange() +\n  geom_point(shape = 21, size = 2, fill = 'white', stroke = 1) +\n  scale_x_continuous('Estimate', \n                     breaks = seq(from = -5, to = 5, by = 0.5),\n                     limits = c(-1.25, 1.25)) +\n  theme(panel.grid = element_blank(),\n        panel.background = element_blank(),\n        panel.border = element_rect(colour = 'black', fill = NA),\n        axis.title.y = element_blank())\n```\n\n::: {.cell-output-display}\n![Estimates of the temperature coefficient for the two models. The white dots represent the point estimate, and the black lines represent the 95% confidence intervals. The blue dashed line represents the parameter used to generate the data.](ex1_simulation_files/figure-html/fig-DAG.ex1-estimate-1.png){#fig-DAG.ex1-estimate fig-align='center' width=5400}\n:::\n:::\n\n\n\n\n@fig-DAG.ex1-estimate shows the estimates (point estimate and 95% confidence interval) of the coefficient for temperature for `Model.1` and `Model.2`.\n\nFor `Model.1` we found a positive coefficient between indoor air temperature $(\\text{T})$ and productivity $(\\text{P})$ equal to 0.715 with 95% CI \\[0.623, 0.807\\]. Since the 95% CI does not include zero, the regression coefficient is statistically significantly different from zero at the 0.05 level (p-value = 2.56e-51). Additionally, since the 95% CI does not include the data-generating parameter for indoor air temperature (i.e., `b_temp.prod = -1`), we can deduce that the estimated coefficient for indoor air temperature is statistically significantly different from -1 at the 0.05 level (although this will be the case for all numbers within the 95% confidence interval). We can test this more formally by using the `linearHypothesis()` function. Specifically,\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Test for b_temp.prod = -1\ncar::linearHypothesis(ex1_Model.1, 'T = -1') # car:: access the function from the car package without loading it in the environment \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLinear hypothesis test:\nT = - 1\n\nModel 1: restricted model\nModel 2: P ~ T\n\n  Res.Df   RSS Df Sum of Sq    F    Pr(>F)    \n1   4999 52123                                \n2   4998 41130  1     10994 1336 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\nThe resulting p-value is 1.97e-259, which indicates that we can reject the null hypothesis (i.e., `T = -1`) at the 0.05 level. This result suggests that the regression coefficient for indoor air temperature (i.e., 0.715) is statistically significantly different from -1. Since the estimated causal effect from `Model.1` is biased, we would erroneously conclude that an increase of 1°C in indoor air temperature causes an increase in productivity by 0.715 units (95% CI \\[0.623, 0.807\\]).\n\nFor `Model.2` we found a negative coefficient between indoor air temperature $(\\text{T})$ and productivity $(\\text{P})$ equal to -1.009 with 95% CI \\[-1.088, -0.930\\]. Since the 95% CI excludes zero, the regression coefficient is statistically significantly different from zero at the 0.05 level (p-value = 3.99e-130). Additionally, since the 95% CI includes the data-generating parameter for indoor air temperature (i.e., `b_temp.prod = -1`), we can deduce that the estimated coefficient for indoor air temperature is not statistically significantly different from -1 at the 0.05 level (although this will be the case for all numbers within the 95% confidence interval). We can test this more formally by using the `linearHypothesis()` function. Specifically,\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Test for T = -1\ncar::linearHypothesis(ex1_Model.2, 'T = -1') # car:: access the function from the car package without loading it in the environment \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLinear hypothesis test:\nT = - 1\n\nModel 1: restricted model\nModel 2: P ~ T + H\n\n  Res.Df   RSS Df Sum of Sq      F Pr(>F)\n1   4998 19948                           \n2   4997 19948  1   0.21046 0.0527 0.8184\n```\n\n\n:::\n:::\n\n\n\n\nThe resulting p-value is 0.818, which indicates that we fail to reject the null hypothesis (i.e., `T = -1`) at the 0.05 level. This result suggests that the regression coefficient for indoor air temperature (i.e., -1.009) is not statistically significantly different from -1. Since the estimated causal effect from `Model.2` is unbiased, we would correctly conclude that an increase of 1°C in indoor air temperature causes a decrease in productivity by -1.009 units (95% CI \\[-1.088, -0.930\\]).\n\nImportantly, for both `Model.1` and `Model.2`, the 95% confidence interval means that if we were to repeat the sampling process and calculate the interval many times, 95% of those calculated intervals would contain the true population parameter. To highlight this, we can repeat the analysis by fitting the two models to one thousand data sets randomly selected from our population.\n\nThe for-loop shown in the code below performs the following operations. First, sample (using simple random sample) a data set of 5,000 observations from the target population. Subsequently, perform linear regression using `Model.1` and `Model.2` and store the estimated coefficients for `temperature`, its standard error and 95% confidence interval in the data frame `coefs_ex1`. This operation is repeated a thousand times, resulting in the data frame `coefs_ex1` containing the estimates (point estimate, standard error and confidence interval) of a thousand random samples of size 5,000 using both `Model.1` and `Model.2`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_model <- c('mod.1', 'mod.2')     \n\nn_row <- n_sims*length(n_model)\n\n#Create an empty data frame\nempty.df <- data.frame(matrix(NA, nrow = n_row, ncol = 7))\n#Rename the data frame columns\ncolnames(empty.df) <- c('sim.id', 'estimate', 'se', 'CI_2.5', 'CI_97.5',\n                        'model', 'coverage')\n\n#Sample a thousand data sets of 5,000 observations and perform linear regression \ncoefs_ex1 <- empty.df #assign the empty data frame\nk = 1\nfor (i in 1:n_sims){\n  set.seed(ex1_random.seed[i]) #set unique seed for each simulation \n#Sample data set from population   \n  sample.random <- \n    ex1_population %>% \n    slice_sample(n = 5e3) #take a simple random sample of size 5,000\n#Fit models\n  for (j in 1:length(n_model)){\n    if (n_model[j] == 'mod.1'){\n      fit <- lm(formula = P ~ T,\n                data = sample.random)\n    } else {\n      fit <- lm(formula = P ~ T + H,\n                data = sample.random)\n    }  \n#Compile matrix  \n  coefs_ex1[k, 1] <- i #simulation ID\n  coefs_ex1[k, 2] <- coef(fit)['T'] #point estimate\n  coefs_ex1[k, 3] <- summary(fit)$coef['T','Std. Error'] #standard error\n  coefs_ex1[k, 4:5] <- confint(fit, level = 0.95, type = 'Wald')['T', ] #confidence interval (Wald)\n  coefs_ex1[k, 6] <- n_model[j] #sample size\n  k = k + 1\n  }\n}\ncoefs_ex1 <- as_tibble(coefs_ex1)\n#View the data frame\ncoefs_ex1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2,000 × 7\n   sim.id estimate     se CI_2.5 CI_97.5 model coverage\n    <int>    <dbl>  <dbl>  <dbl>   <dbl> <chr> <lgl>   \n 1      1    0.715 0.0469  0.623   0.807 mod.1 NA      \n 2      1   -1.01  0.0404 -1.09   -0.930 mod.2 NA      \n 3      2    0.706 0.0477  0.613   0.800 mod.1 NA      \n 4      2   -0.959 0.0415 -1.04   -0.878 mod.2 NA      \n 5      3    0.673 0.0472  0.581   0.766 mod.1 NA      \n 6      3   -1.02  0.0402 -1.10   -0.946 mod.2 NA      \n 7      4    0.668 0.0468  0.576   0.759 mod.1 NA      \n 8      4   -1.02  0.0405 -1.10   -0.937 mod.2 NA      \n 9      5    0.717 0.0475  0.624   0.811 mod.1 NA      \n10      5   -1.03  0.0418 -1.11   -0.949 mod.2 NA      \n# ℹ 1,990 more rows\n```\n\n\n:::\n:::\n\n\n\n\nThe `coverage` is defined by setting its value to `1` if the confidence interval overlaps the data-generating parameter for `temperature` (i.e., `b_temp.prod = -1`) and `0` otherwise.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculate coverage\ncoefs_ex1 <-\n  coefs_ex1 %>%\n  mutate(coverage = case_when(CI_2.5 > b_temp.prod | CI_97.5 < b_temp.prod ~ 0,\n                              CI_2.5 <= b_temp.prod & CI_97.5 >= b_temp.prod ~ 1,\n                              .default = NA))\n#View the data frame\ncoefs_ex1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2,000 × 7\n   sim.id estimate     se CI_2.5 CI_97.5 model coverage\n    <int>    <dbl>  <dbl>  <dbl>   <dbl> <chr>    <dbl>\n 1      1    0.715 0.0469  0.623   0.807 mod.1        0\n 2      1   -1.01  0.0404 -1.09   -0.930 mod.2        1\n 3      2    0.706 0.0477  0.613   0.800 mod.1        0\n 4      2   -0.959 0.0415 -1.04   -0.878 mod.2        1\n 5      3    0.673 0.0472  0.581   0.766 mod.1        0\n 6      3   -1.02  0.0402 -1.10   -0.946 mod.2        1\n 7      4    0.668 0.0468  0.576   0.759 mod.1        0\n 8      4   -1.02  0.0405 -1.10   -0.937 mod.2        1\n 9      5    0.717 0.0475  0.624   0.811 mod.1        0\n10      5   -1.03  0.0418 -1.11   -0.949 mod.2        1\n# ℹ 1,990 more rows\n```\n\n\n:::\n:::\n\n\n\n\nThe results are then plotted in @fig-DAG.ex1-CI.\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nmodel_names <- c('mod.1' = 'Model.1', \n                 'mod.2' = 'Model.2')\n\nggplot(data = subset(coefs_ex1, sim.id <= 2e2), aes(x = sim.id, y = estimate, ymin = CI_2.5, ymax = CI_97.5, colour = as.factor(coverage))) + \n  geom_hline(yintercept = b_temp.prod, alpha = 0.8, linetype = 'dashed', colour = 'blue') + \n  geom_linerange() +\n  geom_point(shape = 21, size = 1, fill = 'white', stroke = 0.5) +\n  scale_colour_manual('', values = c('black', '#FF4040'),\n                      breaks = c('1','0')) +\n  scale_y_continuous('Estimate') +\n  scale_x_continuous('Simulation ID') +\n  facet_wrap(model~., \n             labeller = labeller(model = model_names),\n             nrow = 2,\n             scales = 'fixed') +\n  theme(legend.position = 'none', \n        panel.grid = element_blank(),\n        panel.background = element_blank(),\n        panel.border = element_rect(colour = 'black', fill = NA),\n        axis.title.y = element_blank())\n```\n\n::: {.cell-output-display}\n![Estimates of the temperature coefficient (only the first hundreds of the thousand simulations are shown). The white dots represent the point estimate, and the black lines represent the 95% confidence intervals. In red are highlighted the confidence intervals that do not overlap the parameter used to generate the data (dashed blue line).](ex1_simulation_files/figure-html/fig-DAG.ex1-CI-1.png){#fig-DAG.ex1-CI fig-align='center' width=5400}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n@fig-DAG.ex1-CI shows the first 200 estimates (point estimate and confidence interval) of the coefficient for indoor air temperature for `Model.1` and `Model.2`. If all the thousand simulations are considered, the frequency of the coverage of the calculated confidence intervals (i.e., how many times the confidence intervals overlap the data-generating parameter) is 0.0% and 94.9% for `Model.1` and `Model.2`, respectively. Since the estimates of the causal effect for `Model.1` are biased, the calculated confidence intervals for this model do not have the expected coverage. In fact, confidence intervals only quantify the uncertainty due to random error (i.e., sample variability), not systematic error (i.e., bias). Instead, the estimates from `Model.2` are unbiased and the calculated 95% confidence intervals have the expected coverage (i.e., overlap the data-generating parameter 95% of the times).\n\nWe can also visualize all the 1,000 estimates of the coefficient for indoor air temperature for `Model.1` and `Model.2` (the estimates were shown as white dots in @fig-DAG.ex1-CI).\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(data = coefs_ex1, aes(x = estimate, y = ifelse(after_stat(count) > 0, after_stat(count), NA))) +\n  geom_histogram(binwidth = 0.05, fill = 'white', colour = 'grey50') +\n  geom_vline(xintercept = -1, colour = 'blue', linetype = 'dashed') +\n  scale_x_continuous('Estimate', \n                     breaks = seq(from = -5, to = 5, by = 0.5),\n                     limits = c(-1.5, 1.5)) +\n  facet_grid(model~., \n             labeller = labeller(model = model_names),\n             scales = 'fixed') +\n  theme(axis.title.y = element_blank(), \n        axis.text.y = element_blank(), \n        axis.ticks.y = element_blank(),\n        panel.grid = element_blank(),\n        panel.background = element_blank(),\n        panel.border = element_rect(colour = 'black', fill = NA))\n```\n\n::: {.cell-output-display}\n![Histogram of the 1,000 estimates of the temperature coefficient for the two models. The blue dashed line represents the parameter used to generate the data.](ex1_simulation_files/figure-html/fig-DAG.ex1-mean-estimate-1.png){#fig-DAG.ex1-mean-estimate fig-align='center' width=5400}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\nIn @fig-DAG.ex1-mean-estimate, the estimated coefficients are visualized through a histogram. Here, we can see that the estimates for `Model.1` are not clustered around the data-generating parameter (blue dashed line) having a mean estimate of 0.687 (with 0.043 standard deviation). In contrast, the estimates for `Model.2` having a mean estimate of -1.005 (with 0.041 standard deviation) are centered around the data-generating parameter.\n\nAs expected, the inclusion of HVAC system $(\\text{H})$ in the regression model (i.e., using `Model.2`) leads to the correct estimate of the total average causal effect, while its exclusion (i.e., using `Model.1`) leads to bias. Specifically, the estimated effect is reversed. This phenomenon is known as Simpson's Paradox. Generally, Simpson's Paradox happens when a trend that appears in different groups of data reverses (or disappears) when the groups are combined.\n\nTo better explain this apparent paradox, we can plot the data and the fitted regression lines for only the data with `HVAC = classic`, the data with `HVAC = alternative`, and the data combined (i.e., without considering the groups).\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\npred_ex1_Model.1_separete <-\n  rbind(cbind(filter(ex1_sample.random, H == 'classic'), \n              predict(lm(formula = P ~ T, data = filter(ex1_sample.random, H == 'classic')), \n                      interval = 'confidence', level = 0.95), pred = 'classic'), \n        cbind(filter(ex1_sample.random, H == 'alternative'), \n              predict(lm(formula = P ~ T, data = filter(ex1_sample.random, H == 'alternative')),\n                      interval = 'confidence', level = 0.95), pred = 'alternative'))\n\npred_ex1_Model.1 <- \n  cbind(ex1_sample.random, \n      predict(ex1_Model.1, interval = 'confidence', level = 0.95))\n\n#Plot \nex1_sample.random %>%\n  ggplot(aes(x = T, y = P)) +\n  geom_point(aes(colour = H), shape = 19, size = 2, alpha = 0.10, stroke = NA) +\n  geom_ribbon(data = pred_ex1_Model.1_separete, aes(x = T , y = fit, ymin = lwr, ymax = upr, fill = H), alpha = 0.2, show.legend = NA) +\n  geom_line(data = pred_ex1_Model.1_separete, aes(x = T , y = fit, colour = H)) + \n  geom_ribbon(data = pred_ex1_Model.1, aes(x = T , y = fit, ymin = lwr, ymax = upr, fill = 'all.data'), alpha = 0.2, show.legend = NA) +\n  geom_line(data = pred_ex1_Model.1, aes(x = T , y = fit, colour = 'all.data')) + \n  scale_colour_manual('',\n                      breaks = c('classic', 'alternative', 'all.data'),\n                      labels = c('classic', 'alternative', 'all data'),\n                      values = c('#D55E00','#0072B2', 'black')) +\n  scale_fill_manual('',\n                    breaks = c('classic', 'alternative', 'all.data'),\n                    labels = c('classic', 'alternative', 'all data'),\n                    values = c('#D55E00','#0072B2', 'black')) +\n  scale_x_continuous('Indoor air temperature') + \n  scale_y_continuous('Productivity') +\n  guides(colour = guide_legend(override.aes = list(alpha = 1))) + \n  theme(legend.position = 'bottom',\n        legend.direction = 'horizontal',\n        panel.grid = element_blank(),\n        panel.background = element_blank(),\n        panel.border = element_rect(colour = 'black', fill = NA))\n```\n\n::: {.cell-output-display}\n![Visualization of the reversed regression line direction in the total sample compared to the subgroups.](ex1_simulation_files/figure-html/fig-DAG.ex1-paradox-1.png){#fig-DAG.ex1-paradox fig-align='center' width=5400}\n:::\n:::\n\n\n\n\nIn @fig-DAG.ex1-paradox the three colored lines represent the regression lines for only the data with `HVAC = classic` (in orange), the data with `HVAC = alternative` (in blue), and the combined data (in black). The regression lines in orange and blue are obtained by fitting the following regression models:\n\n-   subset of data with `H == 'classic'`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Filter data with H == 'classic'\nex1_sample.random_classic <- filter(ex1_sample.random, H == 'classic')\n#Fit the linear regression model for only data with H == 'classic'\nex1_Model.1_classic <- lm(formula = P ~ T, data = ex1_sample.random_classic)\n#View of the model summary\nex1_Model.1_classic\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = P ~ T, data = ex1_sample.random_classic)\n\nCoefficients:\n(Intercept)            T  \n    74.1501      -0.9614  \n```\n\n\n:::\n:::\n\n\n\n\n-   subset of data with `H == 'alternative'`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Filter data with H == 'alternative'\nex1_sample.random_alternative <- filter(ex1_sample.random, H == 'alternative')\n#Fit the linear regression model for only data with H == 'alternative'\nex1_Model.1_alternative <- lm(formula = P ~ T, data = ex1_sample.random_alternative)      \n#View of the model summary\nex1_Model.1_alternative        \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = P ~ T, data = ex1_sample.random_alternative)\n\nCoefficients:\n(Intercept)            T  \n      81.36        -1.06  \n```\n\n\n:::\n:::\n\n\n\n\nWe can visualize the estimated coefficients for these new regression models and compare them with the ones estimated from `Model.1` and `Model.2`.\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#Plot\ndata.frame(model = c('Model.1', 'Model.1_classic', 'Model.1_alternative', 'Model.2'),\n           estimate = c(coef(ex1_Model.1)['T'], \n                        coef(ex1_Model.1_classic)['T'], \n                        coef(ex1_Model.1_alternative)['T'], \n                        coef(ex1_Model.2)['T']),\n           lower.95.CI = c(confint(ex1_Model.1, level = 0.95, type = 'Wald')['T', 1],\n                           confint(ex1_Model.1_classic, level = 0.95, type = 'Wald')['T', 1],\n                           confint(ex1_Model.1_alternative, level = 0.95, type = 'Wald')['T', 1],\n                           confint(ex1_Model.2, level = 0.95, type = 'Wald')['T', 1]),\n           upper.95.CI = c(confint(ex1_Model.1, level = 0.95, type = 'Wald')['T', 2], \n                           confint(ex1_Model.1_classic, level = 0.95, type = 'Wald')['T', 2], \n                           confint(ex1_Model.1_alternative, level = 0.95, type = 'Wald')['T', 2], \n                           confint(ex1_Model.2, level = 0.95, type = 'Wald')['T', 2])) %>%\n  \nggplot(aes(x = estimate, y = model, xmin = lower.95.CI, xmax = upper.95.CI)) + \n  geom_vline(xintercept = b_temp.prod, alpha = 0.8, linetype = 'dashed', colour = 'blue') + \n  geom_linerange() +\n  geom_point(shape = 21, size = 2, fill = 'white', stroke = 1) +\n  scale_x_continuous('Estimate', \n                     breaks = seq(from = -5, to = 5, by = 0.5),\n                     limits = c(-1.25, 1.25)) +\n  theme(panel.grid = element_blank(),\n        panel.background = element_blank(),\n        panel.border = element_rect(colour = 'black', fill = NA),\n        axis.title.y = element_blank())\n```\n\n::: {.cell-output-display}\n![Estimates of the temperature coefficient for the four models. The white dots represent the point estimate, and the black lines represent the 95% confidence intervals. The blue dashed line represents the parameter used to generate the data.](ex1_simulation_files/figure-html/fig-DAG.ex1-estimate2-1.png){#fig-DAG.ex1-estimate2 fig-align='center' width=5400}\n:::\n:::\n\n\n\n\n@fig-DAG.ex1-estimate2, we can see that only the estimated coefficient for `Model.1` is biased. As explained in the identification step, to identify the causal effect of indoor air temperature $(\\text{T})$ on productivity $(\\text{P})$, we need to block the backdoor path (i.e., the non-causal path) $\\text{T} \\leftarrow \\text{H} \\rightarrow \\text{P}$. Fitting a separate regression model to the subset of data with `H == 'classic'` and one to `H == 'alternative'` is equivalent to conditioning for $\\text{H}$, closing the backdoor path and allowing unbiased estimation of the causal effect of indoor air temperature $(\\text{T})$ on productivity $(\\text{P})$ (although this comes at the price of a larger standard error and consequently wider confidence intervals compared to `Model.2`, where $\\text{H}$ is added as a predictor).\n\n#### Bayesian framework\n\n<details>\n\n<summary>Click to expand</summary>\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Fit the linear regression model with T and P (Model 1)\nex1_Model.1 <- stan_glm(formula = P ~ T,\n                        family = gaussian(),\n                        data = ex1_sample.random,\n                        #Prior coefficients\n                        prior = normal(location = 0, scale = 2),\n                        #Prior intercept\n                        prior_intercept = normal(location = 56, scale = 10),\n                        #Prior sigma\n                        prior_aux = exponential(rate = 0.5),\n                        iter = 4000, warmup = 1000, \n                        save_warmup = TRUE,\n                        chains = 4, cores = 4,\n                        seed = 2025) #for reproducibility   \n#View of the model\nex1_Model.1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstan_glm\n family:       gaussian [identity]\n formula:      P ~ T\n observations: 5000\n predictors:   2\n------\n            Median MAD_SD\n(Intercept) 40.6    1.0  \nT            0.7    0.0  \n\nAuxiliary parameter(s):\n      Median MAD_SD\nsigma 2.9    0.0   \n\n------\n* For help interpreting the printed output see ?print.stanreg\n* For info on the priors used see ?prior_summary.stanreg\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Fit the linear regression model with T , H and P (Model 2)\nex1_Model.2 <- stan_glm(formula = P ~ T + H,\n                        family = gaussian(),\n                        data = ex1_sample.random,\n                        #Prior coefficients\n                        prior = normal(location = c(0, 0), scale = c(2, 5)),\n                        #Prior intercept\n                        prior_intercept = normal(location = 56, scale = 10),\n                        #Prior sigma\n                        prior_aux = exponential(rate = 0.5),\n                        iter = 4000, warmup = 1000, \n                        save_warmup = TRUE,\n                        chains = 4, cores = 4,\n                        seed = 2025) #for reproducibility\n#View of the model\nex1_Model.2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstan_glm\n family:       gaussian [identity]\n formula:      P ~ T + H\n observations: 5000\n predictors:   3\n------\n             Median MAD_SD\n(Intercept)  75.1    0.9  \nT            -1.0    0.0  \nHalternative  5.1    0.1  \n\nAuxiliary parameter(s):\n      Median MAD_SD\nsigma 2.0    0.0   \n\n------\n* For help interpreting the printed output see ?print.stanreg\n* For info on the priors used see ?prior_summary.stanreg\n```\n\n\n:::\n:::\n\n\n\n\nIn Bayesian analysis, there are important diagnostics that have to be carried out in order to assess the convergence and efficiency of the Markov Chains. This is done by using the `monitor()` function which computes summaries of MCMC (Markov Chain Monte Carlo) draws and monitor convergence. Specifically, we will look at `Rhat`, `Bulk_ESS` and `Tail_ESS` metrics.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Diagnostics for model 1\nmonitor(ex1_Model.1$stanfit)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInference for the input samples (4 chains: each with iter = 4000; warmup = 0):\n\n                    Q5      Q50      Q95     Mean  SD  Rhat Bulk_ESS Tail_ESS\n(Intercept)       39.0     40.6     42.2     40.6 1.0     1    11247     8442\nT                  0.6      0.7      0.8      0.7 0.0     1    11198     8547\nsigma              2.8      2.9      2.9      2.9 0.0     1    12436     8349\nmean_PPD          55.9     55.9     56.0     55.9 0.1     1    12083    10586\nlog-posterior -12372.2 -12369.4 -12368.4 -12369.7 1.2     1     5253     7299\n\nFor each parameter, Bulk_ESS and Tail_ESS are crude measures of \neffective sample size for bulk and tail quantities respectively (an ESS > 100 \nper chain is considered good), and Rhat is the potential scale reduction \nfactor on rank normalized split chains (at convergence, Rhat <= 1.05).\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Diagnostics for model 2\nmonitor(ex1_Model.2$stanfit) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInference for the input samples (4 chains: each with iter = 4000; warmup = 0):\n\n                    Q5      Q50      Q95     Mean  SD  Rhat Bulk_ESS Tail_ESS\n(Intercept)       73.7     75.1     76.6     75.1 0.9     1     9368     8706\nT                 -1.1     -1.0     -0.9     -1.0 0.0     1     9250     8793\nHalternative       5.0      5.1      5.2      5.1 0.1     1     9370     9269\nsigma              2.0      2.0      2.0      2.0 0.0     1    12753     7542\nmean_PPD          55.9     55.9     56.0     55.9 0.0     1    11634    11040\nlog-posterior -10565.4 -10562.3 -10561.0 -10562.6 1.4     1     5975     7387\n\nFor each parameter, Bulk_ESS and Tail_ESS are crude measures of \neffective sample size for bulk and tail quantities respectively (an ESS > 100 \nper chain is considered good), and Rhat is the potential scale reduction \nfactor on rank normalized split chains (at convergence, Rhat <= 1.05).\n```\n\n\n:::\n:::\n\n\n\n\n`Rhat` is a metric used to assess the convergence of Markov Chain Monte Carlo (MCMC) simulations. It helps determine if the MCMC chains have adequately explored the target posterior distribution. Specifically, it compares the between- and within-chain estimates for model parameters: If chains have not mixed well (i.e., the between- and within-chain estimates do not agree), R-hat is larger than 1. A general rule of thumb is to use the sample only if R-hat is less than 1.05; a larger value suggests that the chains have not mixed well, and the results might not be reliable. In our two models, all `Rhat` are equal to 1 indicating that the chains have mixed well and have adequately explored the target posterior distribution.\n\n`Bulk_ESS` and `Tail_ESS` stand for 'Bulk Effective Sample Size' and 'Tail Effective Sample Size,' respectively. Since MCMC samples are not truly independent (they are correlated), these metrics assess the sampling efficiencies, that is, they help evaluating how efficiently the MCMC sampler is exploring the parameters space.\n\n-   `Bulk_ESS` is a useful measure for sampling efficiency in the bulk (center) of the distribution (e.g., efficiency of mean and median estimates);\n-   `Tail_ESS` is a useful measure for sampling efficiency in the tails of the distribution (e.g., efficiency of variance and tail quantile estimates). A general rule of thumb is that both `Bulk-ESS` and `Tail-ESS` should be at least 100 (approximately) per Markov Chain in order to be reliable and indicate that estimates of respective posterior quantiles are reliable. In our two models, all `Bulk-ESS` and `Tail-ESS` are well above 400 (i.e., 100 multiplied by 4, the number of chains we used) indicating that estimates of posterior quantiles are reliable.\n\nSince we have established that the posteriors are reliable, we can now explore the model estimates.\n\nThe estimated coefficients for the two models are then plotted in @fig-DAG.ex1-estimate-Bayesian.\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#Extract draws from model 1 \npost_ex1_Model.1 <-\n  ex1_Model.1 %>% \n  spread_draws(T) %>% #extract draws from the fitted model\n  mutate(model = 'Model.1') #add a new column to specify that the model\n\n#Extract draws from model 2\npost_ex1_Model.2 <-\n  ex1_Model.2 %>% \n  spread_draws(T) %>% #extract draws from the fitted model\n  mutate(model = 'Model.2') #add a new column to specify that the model\n\n#Combine draws\nplot.post <- rbind(post_ex1_Model.1, post_ex1_Model.2)\n\n# Plot\nplot.post  %>%\n  ggplot(aes(y = model, x = T)) +\n  stat_slabinterval(point_interval = 'mean_hdi',\n                    .width = c(.95)) +\n  geom_vline(xintercept = b_temp.prod, alpha = 0.8, linetype = 'dashed', colour = 'blue') + \n  scale_x_continuous('Estimate', \n                     breaks = seq(from = -5, to = 5, by = 0.5),\n                     limits = c(-1.25, 1.25)) +\n  theme(panel.grid = element_blank(),\n        panel.background = element_blank(),\n        panel.border = element_rect(colour = 'black', fill = NA),\n        axis.title.y = element_blank())\n```\n\n::: {.cell-output-display}\n![Posterior distribution of the temperature coefficient for the two models. The black line and dot at the bottom of each distribution represent the highest density interval (HDI) and the mean, respectively.](ex1_simulation_files/figure-html/fig-DAG.ex1-estimate-Bayesian-1.png){#fig-DAG.ex1-estimate-Bayesian fig-align='center' width=5400}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n@fig-DAG.ex1-estimate-Bayesian shows the estimates (mean and 95% HDI) of the coefficient for temperature for `Model.1` and `Model.2`.\n\nFor `Model.1` we found a positive coefficient between indoor air temperature $(\\text{T})$ and productivity $(\\text{P})$ (mean = 0.715, 95% HDI \\[0.622, 0.802\\]). The estimated causal effect is therefore biased, leading to the wrong conclusion that an increase of 1°C in indoor air temperature causes an increase in productivity by 0.715 units, on average. In contrast, for `Model.2` we found a negative coefficient between indoor air temperature $(\\text{T})$ and productivity $(\\text{P})$ (mean = -1.009, 95% HDI \\[-1.089, -0.929\\]). The estimated causal effect is therefore unbiased, leading to the correct conclusion that an increase of 1°C in indoor air temperature causes a decrease in productivity by -1.009 units, on average.\n\nImportantly, for both `Model.1` and `Model.2`, the 95% HDI is the range of parameter values within which the most credible 95% of the posterior distribution falls. Unlike frequentist confidence interval, the Bayesian 95% HDI has a direct probabilistic meaning: every point inside the HDI has a higher probability density than any point outside the interval. Therefore, given the model, the prior and the data, we can say that there is a 95% probability that the data-generating parameter (i.e., `b_temp.prod = -1`) lies within the HDI. However, since `Model.1` leads to a biased estimate, we will reach the wrong conclusion by stating that there is a 95% probability that the data-generating parameter lies within the \\[0.622, 0.802\\] interval. This probability is 0%.\n\nAs expected, the inclusion of HVAC system $(\\text{H})$ in the regression model (i.e., using `Model.2`) leads to the correct estimate of the total average causal effect, while its exclusion (i.e., using `Model.1`) leads to bias. Specifically, the estimated effect is reversed. This phenomenon is known as Simpson's Paradox. Generally, Simpson's Paradox happens when a trend that appears in different groups of data reverses (or disappears) when the groups are combined.\n\nTo better explain this apparent paradox, we can plot the data and the fitted regression lines for only the data with `HVAC = classic`, the data with `HVAC = alternative`, and the data combined (i.e., without considering the groups).\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#Expected value of the posterior predictive distribution (epred) for model 1\nepred_ex1_Model.1 <- \n  ex1_Model.1 %>%\n  epred_draws(newdata = ex1_sample.random, \n              seed = 2025) %>%\n  group_by(T) %>%\n  mean_hdi(.epred, .width = .95) %>%\n  ungroup()\n\n#Expected value of the posterior predictive distribution (epred) for model 2\nepred_ex1_Model.2 <- \n  ex1_Model.2 %>%\n  epred_draws(newdata = ex1_sample.random, \n              seed = 2025) %>%\n  group_by(T, H) %>%\n  mean_hdi(.epred, .width = .95) %>%\n  ungroup()\n\n#Plot \nex1_sample.random %>%\n  ggplot(aes(x = T, y = P)) +\n  geom_point(aes(colour = H), shape = 19, size = 2, alpha = 0.15, stroke = NA) +\n  \n  geom_ribbon(data = epred_ex1_Model.2, aes(x = T , y = .epred, ymin = .lower, ymax = .upper, fill = H), alpha = 0.2, show.legend = NA) +\n  geom_line(data = epred_ex1_Model.2, aes(x = T , y = .epred, colour = H)) + \n  \n  geom_ribbon(data = epred_ex1_Model.1, aes(x = T , y = .epred, ymin = .lower, ymax = .upper, fill = 'all.data'), alpha = 0.2, show.legend = NA) +\n  geom_line(data = epred_ex1_Model.1, aes(x = T , y = .epred, colour = 'all.data')) + \n  scale_colour_manual('',\n                      breaks = c('classic', 'alternative', 'all.data'),\n                      labels = c('classic', 'alternative', 'all data'),\n                      values = c('#D55E00','#0072B2', 'black')) +\n  scale_fill_manual('',\n                    breaks = c('classic', 'alternative', 'all.data'),\n                    labels = c('classic', 'alternative', 'all data'),\n                    values = c('#D55E00','#0072B2', 'black')) +\n  scale_x_continuous('Indoor air temperature') + \n  scale_y_continuous('Productivity') +\n  guides(colour = guide_legend(override.aes = list(alpha = 1))) + \n  theme(legend.position = 'bottom',\n        legend.direction = 'horizontal',\n        panel.grid = element_blank(),\n        panel.background = element_blank(),\n        panel.border = element_rect(colour = 'black', fill = NA))\n```\n\n::: {.cell-output-display}\n![Visualization of the reversed regression line direction in the total sample compared to the subgroups.](ex1_simulation_files/figure-html/fig-DAG.ex1-paradox-Bayesian-1.png){#fig-DAG.ex1-paradox-Bayesian fig-align='center' width=5400}\n:::\n:::\n\n\n\n\nIn @fig-DAG.ex1-paradox-Bayesian the three colored lines represent the regression lines for only the data with `HVAC = classic` (in orange), the data with `HVAC = alternative` (in blue), and the combined data (in black). The regression lines in orange and blue are obtained by fitting the following regression models:\n\n-   subset of data with `H == 'classic'`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Filter data with H == 'classic'\nex1_sample.random_classic <- filter(ex1_sample.random, H == 'classic')\n#Fit the linear regression model for only data with H == 'classic'\nex1_Model.1_classic <- stan_glm(formula = P ~ T,\n                                    family = gaussian(),\n                                    data = ex1_sample.random_classic,\n                                    #Prior coefficients\n                                    prior = normal(location = 0, scale = 5),\n                                    #Prior intercept\n                                    prior_intercept = normal(location = 56, scale = 10),\n                                    #Prior sigma\n                                    prior_aux = exponential(rate = 0.5),\n                                    iter = 4000, warmup = 1000, \n                                    save_warmup = TRUE,\n                                    chains = 4, cores = 4,\n                                    seed = 2025) #for reproducibility\n#View of the model\nex1_Model.1_classic\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstan_glm\n family:       gaussian [identity]\n formula:      P ~ T\n observations: 2551\n predictors:   2\n------\n            Median MAD_SD\n(Intercept) 74.1    1.2  \nT           -1.0    0.1  \n\nAuxiliary parameter(s):\n      Median MAD_SD\nsigma 2.0    0.0   \n\n------\n* For help interpreting the printed output see ?print.stanreg\n* For info on the priors used see ?prior_summary.stanreg\n```\n\n\n:::\n:::\n\n\n\n\n-   subset of data with `H == 'alternative'`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Filter data with H == 'alternative'\nex1_sample.random_alternative <- filter(ex1_sample.random, H == 'alternative')\n#Fit the linear regression model for only data with H == 'alternative'\nex1_Model.1_alternative <- stan_glm(formula = P ~ T,\n                                    family = gaussian(),\n                                    data = ex1_sample.random_alternative,\n                                    #Prior coefficients\n                                    prior = normal(location = 0, scale = 5),\n                                    #Prior intercept\n                                    prior_intercept = normal(location = 56, scale = 10),\n                                    #Prior sigma\n                                    prior_aux = exponential(rate = 0.5),\n                                    iter = 4000, warmup = 1000, \n                                    save_warmup = TRUE,\n                                    chains = 4, cores = 4,\n                                    seed = 2025) #for reproducibility\n#View of the model\nex1_Model.1_alternative\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstan_glm\n family:       gaussian [identity]\n formula:      P ~ T\n observations: 2449\n predictors:   2\n------\n            Median MAD_SD\n(Intercept) 81.4    1.3  \nT           -1.1    0.1  \n\nAuxiliary parameter(s):\n      Median MAD_SD\nsigma 2.0    0.0   \n\n------\n* For help interpreting the printed output see ?print.stanreg\n* For info on the priors used see ?prior_summary.stanreg\n```\n\n\n:::\n:::\n\n\n\n\nWe can visualize the estimated coefficients for these new regression models and compared them with the one estimated from `Model.1` and `Model.2`.\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#Extract draws from model 1 \npost_ex1_Model.1_classic <-\n  ex1_Model.1_classic %>% \n  spread_draws(T) %>% #extract draws from the fitted model\n  mutate(model = 'Model.1_classic') #add a new column to specify that the model\n\n#Extract draws from model 2\npost_ex1_Model.1_alternative <-\n  ex1_Model.1_alternative %>% \n  spread_draws(T) %>% #extract draws from the fitted model\n  mutate(model = 'Model.1_alternative') #add a new column to specify that the model\n\n#Combine draws\nplot.post1 <- rbind(post_ex1_Model.1, post_ex1_Model.1_classic, post_ex1_Model.1_alternative, post_ex1_Model.2)\n\n#Plot\nplot.post1  %>%\n  ggplot(aes(y = model, x = T)) +\n  stat_slabinterval(point_interval = 'mean_hdi',\n                    .width = c(.95)) +\n  geom_vline(xintercept = b_temp.prod, alpha = 0.8, linetype = 'dashed', colour = 'blue') + \n  scale_x_continuous('Estimate', \n                     breaks = seq(from = -5, to = 5, by = 0.5),\n                     limits = c(-1.5, 1.5)) +\n  theme(panel.grid = element_blank(),\n        panel.background = element_blank(),\n        panel.border = element_rect(colour = 'black', fill = NA),\n        axis.title.y = element_blank())\n```\n\n::: {.cell-output-display}\n![Posterior distribution of the temperature coefficient for the four models. The black line and dot at the bottom of each distribution represent the highest density interval (HDI) and the mean, respectively.](ex1_simulation_files/figure-html/fig-DAG.ex1-estimate-Bayesian2-1.png){#fig-DAG.ex1-estimate-Bayesian2 fig-align='center' width=5400}\n:::\n:::\n\n\n\n\n@fig-DAG.ex1-estimate-Bayesian2, we can see that only the estimated coefficient for `Model.1` is biased. As explained in the identification step, to identify the causal effect of indoor air temperature $(\\text{T})$ on productivity $(\\text{P})$, we need to block the backdoor path (i.e., the non-causal path) $\\text{T} \\leftarrow \\text{H} \\rightarrow \\text{P}$. Fitting a separate regression model to the subset of data with `H == 'classic'` and one to `H == 'alternative'` is equivalent to conditioning for $\\text{H}$, closing the backdoor path and allowing unbiased estimation of the causal effect of indoor air temperature $(\\text{T})$ on productivity $(\\text{P})$ (although this comes at the price of a larger standard error and consequently wider credible interval compared to `Model.2`, where $\\text{H}$ is added as a predictor).\n\n</details>\n\n## Session info {.unnumbered}\n\nVersion information about R, the OS and attached or loaded packages.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.2.3 (2023-03-15 ucrt)\nPlatform: x86_64-w64-mingw32/x64 (64-bit)\nRunning under: Windows 10 x64 (build 26200)\n\nMatrix products: default\n\nlocale:\n[1] LC_COLLATE=English_United Kingdom.utf8 \n[2] LC_CTYPE=English_United Kingdom.utf8   \n[3] LC_MONETARY=English_United Kingdom.utf8\n[4] LC_NUMERIC=C                           \n[5] LC_TIME=English_United Kingdom.utf8    \n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] rstan_2.32.7        StanHeaders_2.32.10 gt_1.1.0           \n [4] lubridate_1.9.4     forcats_1.0.1       stringr_1.6.0      \n [7] dplyr_1.1.4         purrr_1.2.0         readr_2.1.6        \n[10] tidyr_1.3.1         tibble_3.3.0        ggplot2_4.0.1      \n[13] tidyverse_2.0.0     ggdist_3.3.3        tidybayes_3.0.7    \n[16] rstanarm_2.32.2     Rcpp_1.1.0          dagitty_0.3-4      \n[19] ggdag_0.2.13       \n\nloaded via a namespace (and not attached):\n  [1] backports_1.5.0       plyr_1.8.9            igraph_2.2.1         \n  [4] splines_4.2.3         svUnit_1.0.8          crosstalk_1.2.2      \n  [7] rstantools_2.5.0      inline_0.3.21         digest_0.6.38        \n [10] htmltools_0.5.8.1     viridis_0.6.5         magrittr_2.0.4       \n [13] checkmate_2.3.3       memoise_2.0.1         tzdb_0.5.0           \n [16] graphlayouts_1.2.2    RcppParallel_5.1.11-1 matrixStats_1.5.0    \n [19] xts_0.14.1            timechange_0.3.0      colorspace_2.1-2     \n [22] ggrepel_0.9.6         rbibutils_2.4         xfun_0.54            \n [25] jsonlite_2.0.0        lme4_1.1-37           survival_3.8-3       \n [28] zoo_1.8-14            glue_1.8.0            reformulas_0.4.2     \n [31] polyclip_1.10-7       gtable_0.3.6          V8_8.0.1             \n [34] distributional_0.5.0  car_3.1-3             pkgbuild_1.4.8       \n [37] abind_1.4-8           scales_1.4.0          miniUI_0.1.2         \n [40] viridisLite_0.4.2     xtable_1.8-4          Formula_1.2-5        \n [43] stats4_4.2.3          DT_0.34.0             htmlwidgets_1.6.4    \n [46] threejs_0.3.4         arrayhelpers_1.1-0    RColorBrewer_1.1-3   \n [49] posterior_1.6.1       pkgconfig_2.0.3       loo_2.8.0            \n [52] farver_2.1.2          sass_0.4.10           utf8_1.2.6           \n [55] tidyselect_1.2.1      labeling_0.4.3        rlang_1.1.6          \n [58] reshape2_1.4.5        later_1.4.4           tools_4.2.3          \n [61] cachem_1.1.0          cli_3.6.5             generics_0.1.4       \n [64] evaluate_1.0.5        fastmap_1.2.0         yaml_2.3.10          \n [67] knitr_1.50            fs_1.6.6              tidygraph_1.3.1      \n [70] ggraph_2.2.2          nlme_3.1-168          mime_0.13            \n [73] xml2_1.5.0            compiler_4.2.3        bayesplot_1.14.0     \n [76] shinythemes_1.2.0     rstudioapi_0.17.1     curl_7.0.0           \n [79] tweenr_2.0.3          stringi_1.8.7         lattice_0.22-7       \n [82] Matrix_1.6-5          nloptr_2.2.1          markdown_2.0         \n [85] shinyjs_2.1.0         tensorA_0.36.2.1      vctrs_0.6.5          \n [88] pillar_1.11.1         lifecycle_1.0.4       Rdpack_2.6.4         \n [91] httpuv_1.6.16         QuickJSR_1.8.1        R6_2.6.1             \n [94] promises_1.5.0        gridExtra_2.3         codetools_0.2-20     \n [97] boot_1.3-32           colourpicker_1.3.0    MASS_7.3-58.2        \n[100] gtools_3.9.5          withr_3.0.2           shinystan_2.6.0      \n[103] parallel_4.2.3        hms_1.1.4             grid_4.2.3           \n[106] coda_0.19-4.1         minqa_1.2.8           rmarkdown_2.30       \n[109] S7_0.2.1              carData_3.0-5         otel_0.2.0           \n[112] ggforce_0.5.0         shiny_1.11.1          base64enc_0.1-3      \n[115] dygraphs_1.1.1.6     \n```\n\n\n:::\n:::\n",
    "supporting": [
      "ex1_simulation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}