{
  "hash": "6e0e63247976fc0790825a6540ccde85",
  "result": {
    "engine": "knitr",
    "markdown": "# Simulation example {#sec-ex5}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Load packages\nlibrary(ggdag)\nlibrary(dagitty)\nlibrary(rstanarm)\nlibrary(tidybayes)\nlibrary(ggdist)\nlibrary(tidyverse)\nlibrary(gt)\nlibrary(rstan)\nlibrary(bayesboot)\n```\n:::\n\n\n\n\n## Data-generating process\n\nThe data-generating process is described via the directed acyclic graph (DAG) in @fig-DAG.ex5-1. In this DAG, acoustic sensation $(\\text{C})$ is influenced directly by noise $(\\text{N})$, biological sex $(\\text{S})$ and age $(\\text{A})$. Participation $(\\text{P})$ in the survey response is affected by biological sex $(\\text{S})$ and age $(\\text{A})$.\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\ndag_coords.ex5 <-\n  data.frame(name = c('S', 'N', 'P', 'C', 'A'),\n             x = c(1, 1, 3.5, 3.5, 6),\n             y = c(2, 3, 1, 3, 2))\n\nDAG.ex5 <-\n  dagify(C ~ N + S + A,\n         P ~ S + A,\n         coords = dag_coords.ex5)\n\nnode_labels <- c(\n  S = 'bold(S)', \n  N = 'bold(N)', \n  P = 'bold(P)', \n  C = 'bold(C)', \n  A = 'bold(A)'\n)\n\nggplot(data = DAG.ex5, aes(x = x, y = y, xend = xend, yend = yend)) +\n  geom_point(x = 3.5, y = 1, shape = 0, size = 12, stroke = 0.9, color = 'black') +\n  geom_dag_text(aes(label = node_labels[name]),\n                parse = TRUE,\n                colour = 'black',\n                size = 10,\n                family = 'mono') +\n  geom_dag_edges(arrow_directed = grid::arrow(length = grid::unit(10, 'pt'), type = 'open'),\n                 edge_colour = 'black',\n                 family = 'mono',\n                 fontface = 'bold') +\n  annotate('text', x = 3.5, y = 0.68, label = 'participation', \n           size = 4, hjust = 0.5, colour = 'grey50') +\n  annotate('text', x = 3.5, y = 3.3, label = 'acoustic sensation', \n           size = 4, hjust = 0.5, colour = 'grey50') +\n  annotate('text', x = 1, y = 3.3, label = 'noise', \n           size = 4, hjust = 0.5, colour = 'grey50') +\n  annotate('text', x = 6, y = 1.7, label = 'age', \n           size = 4, hjust = 0.5, colour = 'grey50') +\n  annotate('text', x = 1, y = 1.7, label = 'sex', \n           size = 4, hjust = 0.5, colour = 'grey50') +\n  coord_cartesian(xlim = c(0.5, 6.5), ylim = c(0.8, 3.2))  +\n  theme_dag()\n```\n\n::: {.cell-output-display}\n![Graphical representation via DAG of the data-generating process. The box around P indicates that the sample is conditioned on participation.](ex5_simulation_files/figure-html/fig-DAG.ex5-1-1.png){#fig-DAG.ex5-1 fig-align='center' width=60%}\n:::\n:::\n\n\n\n\nThe DAG in @fig-DAG.ex5-1 can be written as:\n\n-   $C \\sim f_{C}(N, S, A)$, read as 'acoustic sensation $(\\text{C})$ is some function of noise $(\\text{N})$, biological sex $(\\text{S})$ and age $(\\text{A})$'.\n-   $P \\sim f_{P}(S, A)$, read as 'participation $(\\text{P})$ is some function of biological sex $(\\text{S})$ and age $(\\text{A})$'.\n\n## Synthetic data set\n\nTo generate synthetic data, we defined the custom function `data.sim_ex5()`. This function takes as inputs the sample size `n` and generates synthetic data according to the DAG in @fig-DAG.ex5-1.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.sim_ex5 <- function(n) {\n  b_age.conf = 0.3 #direct causal effect of A on C 1 or 0.2\n  b_sex.conf = c(0, -1) #direct causal effect of S on C\n  b_noise.conf = 0.7 #direct causal effect of N on C\n  #Simulate age\n  A <- sample(18:59, size = n, replace = TRUE)\n  #Simulate biological sex\n  S <- factor(sample(c('male', 'female'), size = n, replace = TRUE)) \n  #Simulate noise\n  N <- rnorm(n = n, mean = 45, sd = 4)\n  #Simulate acoustic sensation\n  C <- rnorm(n = n, mean = ifelse(S == 'male', 10 + b_sex.conf[1] + b_noise.conf * N + b_age.conf * A, 10 + b_sex.conf[2] + b_noise.conf * N + b_age.conf * A), sd = 3)\n  #Simulate participation\n  P <- rbinom(n = n, size = 1, prob = plogis(ifelse(S == 'male', +23 -15.6 - 0.25 * A, +23 -13.5 - 0.25 * A)))\n  #Return tibble with simulated values\n  return(tibble(A, S, N, C, P))\n  }\n```\n:::\n\n\n\n\nFrom this data generation mechanism, we simulated the target population, which consists of one million observations.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2025) #set random number for reproducibility\n#Simulate the population\nex5_population <- data.sim_ex5(n = 1e6)\n#Set biological sex reference category to 'male'\nex5_population$S <- relevel(ex5_population$S, ref = 'male')\n#View the data frame\nex5_population\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,000,000 × 5\n       A S          N     C     P\n   <int> <fct>  <dbl> <dbl> <int>\n 1    30 male    46.2  53.3     1\n 2    29 female  47.5  47.4     1\n 3    53 male    44.3  57.7     0\n 4    43 female  40.3  52.4     0\n 5    18 male    37.4  39.9     1\n 6    40 female  36.2  48.1     0\n 7    27 female  46.2  55.9     1\n 8    30 female  48.2  52.7     1\n 9    29 female  47.6  51.3     1\n10    21 female  36.2  42.8     1\n# ℹ 999,990 more rows\n```\n\n\n:::\n:::\n\n\n\n\nFrom this population, we obtained two data sets of five thousand observations each: one using simple random sampling and the other using non-random sampling.\n\nThe first sample (i.e., `ex5_sample.random`) will use simple random sampling, whereas the second one (i.e., `ex5_sample.bias`) will use non-random sampling. In this case, we will first select only the observations with `P == 1` and subsequently sampling randomly from them. As a result, the sample obtained is biased.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_sims <- 1e3 #number of data sets to simulate\n\n#Set random number for reproducibility\nset.seed(2025)  \n#Generate a vector of random numbers for reproducibility\nex5_random.seed <- sample(1:1e5, size = n_sims, replace = FALSE)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(ex5_random.seed[1])\n#Sample one data set of 5,000 observations\nex5_sample.random <- \n  ex5_population %>% \n  slice_sample(n = 5e3) #take a simple random sample of size 5,000\n\nset.seed(ex5_random.seed[1])\n#Sample one data set of 5,000 observations\nex5_sample.bias <- \n  ex5_population %>% \n  filter(P == 1) %>% slice_sample(n = 5e3) #take a biased sample of size 5,000 \n```\n:::\n\n\n\n\nA summary of descriptive statistics for all variables in the data sets is given below.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ex5_sample.random)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       A              S              N               C               P        \n Min.   :18.00   male  :2544   Min.   :31.27   Min.   :34.81   Min.   :0.000  \n 1st Qu.:28.00   female:2456   1st Qu.:42.25   1st Qu.:48.85   1st Qu.:0.000  \n Median :39.00                 Median :44.90   Median :52.72   Median :0.000  \n Mean   :38.75                 Mean   :44.92   Mean   :52.62   Mean   :0.373  \n 3rd Qu.:49.00                 3rd Qu.:47.66   3rd Qu.:56.58   3rd Qu.:1.000  \n Max.   :59.00                 Max.   :60.65   Max.   :69.52   Max.   :1.000  \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(ex5_sample.bias)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       A              S              N               C               P    \n Min.   :18.00   male  :1869   Min.   :30.84   Min.   :33.79   Min.   :1  \n 1st Qu.:22.00   female:3131   1st Qu.:42.41   1st Qu.:46.10   1st Qu.:1  \n Median :26.00                 Median :45.04   Median :49.16   Median :1  \n Mean   :27.48                 Mean   :45.04   Mean   :49.17   Mean   :1  \n 3rd Qu.:32.00                 3rd Qu.:47.79   3rd Qu.:52.28   3rd Qu.:1  \n Max.   :59.00                 Max.   :62.38   Max.   :65.06   Max.   :1  \n```\n\n\n:::\n:::\n\n\n\n\n## Data analysis\n\nIn this example, the target of our analysis is the total average causal effect, ACE (also known as total average treatment effect, ATE) of biological sex $(\\text{S})$ on acoustic sensation $(\\text{C})$, which stands for the expected increase of $\\text{C}$ in response to a change from male to female in $\\text{S}$ due to an intervention. The causal effect of interest is visualized in @fig-DAG.ex5-2.\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(data = DAG.ex5, aes(x = x, y = y, xend = xend, yend = yend)) +\n  #visualize causal effect path\n  geom_segment(x = 1, xend = 3.5, y = 2, yend = 3,\n               linewidth = 14, lineend = 'round', colour = '#009E73', alpha = 0.05) +\n  geom_point(x = 3.5, y = 1, shape = 0, size = 12, stroke = 0.9, color = 'black') +\n  geom_dag_text(aes(label = node_labels[name]),\n                parse = TRUE,\n                colour = 'black',\n                size = 10,\n                family = 'mono') +\n  geom_dag_edges(arrow_directed = grid::arrow(length = grid::unit(10, 'pt'), type = 'open'),\n                 edge_colour = 'black',\n                 family = 'mono',\n                 fontface = 'bold') +\n  annotate('text', x = 3.5, y = 0.68, label = 'participation', \n           size = 4, hjust = 0.5, colour = 'grey50') +\n  annotate('text', x = 3.5, y = 3.3, label = 'acoustic sensation', \n           size = 4, hjust = 0.5, colour = 'grey50') +\n  annotate('text', x = 1, y = 3.3, label = 'noise', \n           size = 4, hjust = 0.5, colour = 'grey50') +\n  annotate('text', x = 6, y = 1.7, label = 'age', \n           size = 4, hjust = 0.5, colour = 'grey50') +\n  annotate('text', x = 1, y = 1.7, label = 'sex', \n           size = 4, hjust = 0.5, colour = 'grey50') +\n  #causal effect number\n  annotate('text', x = 1.9, y = 2.6, label = '-1', \n           size = 4.5, hjust = 0.5, colour = 'black', parse = TRUE) +\n  coord_cartesian(xlim = c(0.5, 6.5), ylim = c(0.8, 3.2))  +\n  theme_dag()\n```\n\n::: {.cell-output-display}\n![Graphical representation via DAG of the data-generating process. The box around P indicates that the sample is conditioned on participation. The green line indicates the causal question of interest, and the number on the path indicates the total average causal effect.](ex5_simulation_files/figure-html/fig-DAG.ex5-2-1.png){#fig-DAG.ex5-2 fig-align='center' width=60%}\n:::\n:::\n\n\n\n\n### Identification\n\nThe first step to answer the causal question of interest is identification. Identification answers a ‘theoretical’ question by determining whether a causal effect can, in principle, be estimated from observed data. The backdoor criterion and its generalization, the adjustment criterion, allow us to understand whether our causal effect of interest can be identified and, if so, which variables we should (or should not) statistically adjust for (i.e., the adjustment set) to estimate the causal effect from the data.\n\nGiven its simplicity, we will first apply the backdoor criterion to identify valid adjustment sets to estimate the causal effect of interest. If the backdoor criterion is not applicable, we will apply its generalization, the adjustment criterion.\n\n#### Backdoor criterion\n\nApplying the backdoor criterion, we found no backdoor paths since no arrows enter into biological sex. However, we noticed that participation $(\\text{P})$ is a descendant of biological sex $(\\text{S})$ and is selected. Although selection and adjustment are conceptually distinct, both are forms of conditioning. Since the sample is implicitly conditioned on $\\text{P}$, a descendant of $\\text{S}$, the conditions required to apply the backdoor criterion are not met. We then apply the adjustment criterion.\n\n#### Adjustment criterion\n\nWith the adjustment criterion, conditioning on $\\text{P}$ is allowed because $\\text{P}$ is not on the causal path from $\\text{S}$ to $\\text{C}$, but we also need to check that all the non-causal paths from $\\text{S}$ to $\\text{C}$ are closed. Since participation $(\\text{P})$ is a collider (i.e., common effect) of biological sex $(\\text{S})$ and age $(\\text{A})$, as females and older individuals are more likely to participate in the experiment, the non-causal path $\\text{S} \\rightarrow \\text{P} \\leftarrow \\text{A} \\rightarrow \\text{C}$ is open. As a result, there is a spurious association between sex $(\\text{S})$ and acoustic sensation $(\\text{C})$.\n\nGiven the DAG in @fig-DAG.ex5-1, we can use the `adjustmentSets()` function to identify the adjustment set algorithmically. Unfortunately, `adjustmentSets()` does not allow to find the adjustment set(s) when there is selection bias (i.e., a variable is conditioned on in the DAG). Nevertheless, for this example there is a work around. We can still use `adjustmentSets()` to get the adjustment set(s) but then only select the one(s) that includes $\\text{P}$.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nadjustmentSets(DAG.ex5,\n               exposure = 'S', #biological sex\n               outcome = 'C', #acoustic sensation\n               type = 'all', \n               effect = 'total', \n               max.results = Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n {}\n{ A }\n{ N }\n{ A, N }\n{ A, P }\n{ A, N, P }\n```\n\n\n:::\n:::\n\n\n\n\nThe resulting adjustment sets that include participation $(\\text{P})$ are only two: adjust for age $(\\text{A})$ or adjust for age $(\\text{A})$ and noise $(\\text{N})$; failing to do so will lead to bias.\n\n### Estimation\n\nFollowing the identification step is the estimation step. This step addresses a statistical question by determining how the causal effect identified in the previous step can be estimated. To perform this step, we used a parametric (model-based) estimator, specifically, linear regression. This was possible because we designed the illustrative examples to be simple and with a linear relationship between the variables. This way, we limited the complexity of the examples themselves and shifted the focus to the application of the backdoor criterion to define 'correct' adjustment sets.\n\nFor transparency and understanding, all (implicit) assumptions used for this illustrative example are (explicitly) provided in @tbl-summary.ex5.\n\n\n\n\n::: {#tbl-summary.ex5 .cell tbl-cap='Summary description of the simulation example'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"djomyqdgnp\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#djomyqdgnp table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#djomyqdgnp thead, #djomyqdgnp tbody, #djomyqdgnp tfoot, #djomyqdgnp tr, #djomyqdgnp td, #djomyqdgnp th {\n  border-style: none;\n}\n\n#djomyqdgnp p {\n  margin: 0;\n  padding: 0;\n}\n\n#djomyqdgnp .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#djomyqdgnp .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#djomyqdgnp .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#djomyqdgnp .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#djomyqdgnp .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#djomyqdgnp .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#djomyqdgnp .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#djomyqdgnp .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#djomyqdgnp .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#djomyqdgnp .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#djomyqdgnp .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#djomyqdgnp .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#djomyqdgnp .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#djomyqdgnp .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#djomyqdgnp .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#djomyqdgnp .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#djomyqdgnp .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#djomyqdgnp .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#djomyqdgnp .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#djomyqdgnp .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#djomyqdgnp .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#djomyqdgnp .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#djomyqdgnp .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#djomyqdgnp .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#djomyqdgnp .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#djomyqdgnp .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#djomyqdgnp .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#djomyqdgnp .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#djomyqdgnp .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#djomyqdgnp .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#djomyqdgnp .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#djomyqdgnp .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#djomyqdgnp .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#djomyqdgnp .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#djomyqdgnp .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#djomyqdgnp .gt_left {\n  text-align: left;\n}\n\n#djomyqdgnp .gt_center {\n  text-align: center;\n}\n\n#djomyqdgnp .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#djomyqdgnp .gt_font_normal {\n  font-weight: normal;\n}\n\n#djomyqdgnp .gt_font_bold {\n  font-weight: bold;\n}\n\n#djomyqdgnp .gt_font_italic {\n  font-style: italic;\n}\n\n#djomyqdgnp .gt_super {\n  font-size: 65%;\n}\n\n#djomyqdgnp .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#djomyqdgnp .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#djomyqdgnp .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#djomyqdgnp .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#djomyqdgnp .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#djomyqdgnp .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#djomyqdgnp .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#djomyqdgnp .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#djomyqdgnp div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" style=\"table-layout:fixed;\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <colgroup>\n    <col style=\"width:22%;\"/>\n    <col/>\n  </colgroup>\n  \n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"vertical-align: top; font-weight: bold; background-color: #FFFFFF;\">Research question</td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Total average causal effect (ACE) of biological sex (S) on acoustic sensation (C).</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"vertical-align: top; font-weight: bold; background-color: #FFFFFF;\">Assumptions</td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Limited random variability: large sample size.</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Independence of observations: each observation represents independent bits of information.</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">No confounding: the DAG includes all shared causes among the variables.</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">No model error: perfect functional form specification.</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">No measurement error: all variables are measured perfectly.</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"vertical-align: top; font-weight: bold; background-color: #FFFFFF;\">Variables</td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Noise (N): continuous variable [unit: dB(A)]</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Biological sex (S): categorical variable ['male'; 'female']</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Age (A): discrete (count) variable [unit: years]</td></tr>\n    <tr><td headers=\"colA\" class=\"gt_row gt_left\" style=\"border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF;\"></td>\n<td headers=\"colB\" class=\"gt_row gt_left\" style=\"vertical-align: top;\">Acoustic sensation (C): continuous variable [unit: -]</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nTo carry out the estimation step, we utilized linear regression within both the frequentist and Bayesian frameworks. Specifically, we will run three regression models:\n\n-   `Model.1` will include only biological sex $(\\text{S})$ as predictor;\n-   `Model.2` will include biological sex $(\\text{S})$ and age $(\\text{A})$ as predictors.\n-   `Model.3` will include biological sex $(\\text{S})$ and noise $(\\text{N})$ as predictors.\n\nThe results of the fitted statistical models (i.e., `Model.1`, `Model.2` and `Model.3`) are presented here.\n\n#### Frequentist framework\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Fit the linear regression model with S and C (Model 1)\nex5_Model.1 <-\n  lm(formula = C ~ S,\n     data = ex5_sample.bias)\n#View of the model summary\nsummary(ex5_Model.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = C ~ S, data = ex5_sample.bias)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-15.4275  -3.0739  -0.0302   3.1096  15.9110 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 49.21609    0.10604 464.114   <2e-16 ***\nSfemale     -0.07153    0.13401  -0.534    0.594    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.584 on 4998 degrees of freedom\nMultiple R-squared:  5.701e-05,\tAdjusted R-squared:  -0.0001431 \nF-statistic: 0.2849 on 1 and 4998 DF,  p-value: 0.5935\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Fit the linear regression model with S, A and C (Model 2)\nex5_Model.2 <-\n  lm(formula = C ~ S + A,\n     data = ex5_sample.bias)\n#View of the model summary\nsummary(ex5_Model.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = C ~ S + A, data = ex5_sample.bias)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-14.456  -2.763   0.013   2.757  15.015 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 41.956227   0.231256 181.428  < 2e-16 ***\nSfemale     -1.001084   0.123454  -8.109 6.37e-16 ***\nA            0.285392   0.008283  34.457  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.121 on 4997 degrees of freedom\nMultiple R-squared:  0.192,\tAdjusted R-squared:  0.1917 \nF-statistic: 593.8 on 2 and 4997 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Fit the linear regression model with S, N and C (Model 3)\nex5_Model.3 <-\n  lm(formula = C ~ S + N,\n     data = ex5_sample.bias)\n#View of the model summary\nsummary(ex5_Model.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = C ~ S + N, data = ex5_sample.bias)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-12.545  -2.523  -0.049   2.505  14.146 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 18.18180    0.59013  30.810   <2e-16 ***\nSfemale     -0.01190    0.10713  -0.111    0.912    \nN            0.68816    0.01295  53.140   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.665 on 4997 degrees of freedom\nMultiple R-squared:  0.3611,\tAdjusted R-squared:  0.3608 \nF-statistic:  1412 on 2 and 4997 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nThe estimated coefficients for the three models are then plotted in @fig-DAG.ex5-estimate.\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nb_sex.conf = c(0, -1)\n\ndata.frame(model = c('Model.1', 'Model.2', 'Model.3'),\n           estimate = c(coef(ex5_Model.1)['Sfemale'], \n                        coef(ex5_Model.2)['Sfemale'],\n                        coef(ex5_Model.3)['Sfemale']),\n           lower.95.CI = c(confint(ex5_Model.1, level = 0.95, type = 'Wald')['Sfemale', 1], \n                           confint(ex5_Model.2, level = 0.95, type = 'Wald')['Sfemale', 1],\n                           confint(ex5_Model.3, level = 0.95, type = 'Wald')['Sfemale', 1]),\n           upper.95.CI = c(confint(ex5_Model.1, level = 0.95, type = 'Wald')['Sfemale', 2], \n                           confint(ex5_Model.2, level = 0.95, type = 'Wald')['Sfemale', 2],\n                           confint(ex5_Model.3, level = 0.95, type = 'Wald')['Sfemale', 2])) %>%\n  \nggplot(aes(x = estimate, y = model, xmin = lower.95.CI, xmax = upper.95.CI)) + \n  geom_vline(xintercept = b_sex.conf[2], alpha = 0.8, linetype = 'dashed', colour = 'blue') + \n  geom_linerange() +\n  geom_point(shape = 21, size = 2, fill = 'white', stroke = 1) +\n  scale_x_continuous('Estimate', \n                     breaks = seq(from = -10, to = 10, by = 0.25),\n                     limits = c(-1.55, 0.55)\n                     ) +\n  theme(panel.grid = element_blank(),\n        panel.background = element_blank(),\n        panel.border = element_rect(colour = 'black', fill = NA),\n        axis.title.y = element_blank())\n```\n\n::: {.cell-output-display}\n![Estimates of the biological sex coefficient for the three models. The white dots represent the point estimate, and the black lines represent the 95% confidence intervals. The blue dashed line represents the parameter used to generate the data.](ex5_simulation_files/figure-html/fig-DAG.ex5-estimate-1.png){#fig-DAG.ex5-estimate fig-align='center' width=5400}\n:::\n:::\n\n\n\n\n@fig-DAG.ex5-estimate shows the estimates (point estimate and 95% confidence interval) of the coefficient for biological sex for `Model.1`, `Model.2`and `Model.3`.\n\nFor `Model.1` we found a negative coefficient between biological sex $(\\text{S})$ and acoustic sensation $(\\text{C})$ equal to -0.072 with 95% CI \\[-0.334, 0.191\\]. Since the 95% CI includes zero, the regression coefficient is not statistically significantly different from zero at the 0.05 level (p-value = 0.594). The observed data are consistent with zero, but also consistent with other non-zero values (i.e., all numbers within the 95% confidence interval). Additionally, since the 95% CI does not include the data-generating parameter for sex (i.e., `b_sex.conf = -1`), we can deduce that the estimated coefficient for sex is statistically significantly different from -1 at the 0.05 level. We can test this more formally by using the `linearHypothesis()` function. Specifically,\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Test for Sfemale = -1\ncar::linearHypothesis(ex5_Model.1, 'Sfemale = -1') # car:: access the function from the car package without loading it in the environment \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLinear hypothesis test:\nSfemale = - 1\n\nModel 1: restricted model\nModel 2: C ~ S\n\n  Res.Df    RSS Df Sum of Sq      F    Pr(>F)    \n1   4999 106053                                  \n2   4998 105044  1    1008.9 48.004 4.791e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\nThe resulting p-value is 4.79e-12, which indicates that we can reject the null hypothesis (i.e., `Sfemale = -1`) at the 0.05 level. This result suggests that the regression coefficient for sex (i.e., -0.072) is statistically significantly different from -1. Since the estimated causal effect from `Model.1` is biased, we would erroneously conclude that changing biological sex from `male` to `female` causes a decrease in acoustic sensation by -0.072 units (95% CI \\[-0.334, 0.191\\]).\n\nFor `Model.2` we found a negative coefficient between biological sex $(\\text{S})$ and acoustic sensation $(\\text{C})$ equal to -1.001 with 95% CI \\[-1.243, -0.759\\]. Since the 95% CI excludes zero, the regression coefficient is statistically significantly different from zero at the 0.05 level (p-value = 6.37e-16). Additionally, since the 95% CI includes the data-generating parameter for sex (i.e., `b_sex.conf = -1`), we can deduce that the estimated coefficient for sex is not statistically significantly different from -1 at the 0.05 level (although this will be the case for all numbers within the 95% confidence interval). We can test this more formally by using the `linearHypothesis()` function. Specifically,\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Test for Sfemale = -1\ncar::linearHypothesis(ex5_Model.2, 'Sfemale = -1') # car:: access the function from the car package without loading it in the environment \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLinear hypothesis test:\nSfemale = - 1\n\nModel 1: restricted model\nModel 2: C ~ S + A\n\n  Res.Df   RSS Df Sum of Sq     F Pr(>F)\n1   4998 84877                          \n2   4997 84877  1 0.0013098 1e-04  0.993\n```\n\n\n:::\n:::\n\n\n\n\nThe resulting p-value is 0.993, which indicates that we fail to reject the null hypothesis (i.e., `Sfemale = -1`) at the 0.05 level. This result suggests that the regression coefficient for sex (i.e., -1.001) is not statistically significantly different from -1. Since the estimated causal effect from `Model.2` is unbiased, we would correctly conclude that changing biological sex from `male` to `female` causes a decrease in acoustic sensation by -1.001 units (95% CI \\[-1.243, -0.759\\]).\n\nFor `Model.3` we found a negative coefficient between biological sex $(\\text{S})$ and acoustic sensation $(\\text{C})$ equal to -0.012 with 95% CI \\[-0.222, 0.198\\]. Since the 95% CI includes zero, the regression coefficient is not statistically significantly different from zero at the 0.05 level (p-value = 0.912). The observed data are consistent with zero, but also consistent with other non-zero values (i.e., all numbers within the 95% confidence interval). Additionally, since the 95% CI does not include the data-generating parameter for sex (i.e., `b_sex.conf = -1`), we can deduce that the estimated coefficient for sex is statistically significantly different from -1 at the 0.05 level. We can test this more formally by using the `linearHypothesis()` function. Specifically,\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Test for Sfemale = -1\ncar::linearHypothesis(ex5_Model.3, 'Sfemale = -1') # car:: access the function from the car package without loading it in the environment \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLinear hypothesis test:\nSfemale = - 1\n\nModel 1: restricted model\nModel 2: C ~ S + N\n\n  Res.Df   RSS Df Sum of Sq      F    Pr(>F)    \n1   4998 68259                                  \n2   4997 67116  1    1142.5 85.066 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\nThe resulting p-value is 4.16e-20, which indicates that we can reject the null hypothesis (i.e., `Sfemale = -1`) at the 0.05 level. This result suggests that the regression coefficient for sex (i.e., -0.012) is statistically significantly different from -1. Since the estimated causal effect from `Model.1` is biased, we would erroneously conclude that changing biological sex from `male` to `female` causes a decrease in acoustic sensation by -0.012 units (95% CI \\[-0.222, 0.198\\]).\n\nImportantly, for `Model.1`, `Model.2` and `Model.3`, the 95% confidence interval means that if we were to repeat the sampling process and calculate the interval many times, 95% of those calculated intervals would contain the true population parameter. To highlight this, we can repeat the analysis by fitting the two models to one thousand data sets randomly selected from our population.\n\nThe for-loop shown in the code below performs the following operations. First, sample (using simple random sample) a data set of 5,000 observations from the target population. Subsequently, perform linear regression using `Model.1`, `Model.2` and `Model.3` and store the estimated coefficients for `sex`, its standard error and 95% confidence interval in the data frame `coefs_ex5`. This operation is repeated a thousand times, resulting in the data frame `coefs_ex5` containing the estimates (point estimate, standard error and confidence interval) of a thousand random samples of size 5,000 using both `Model.1`, `Model.2` and `Model.3`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_model <- c('mod.1', 'mod.2', 'mod.3')     \n\nn_row <- n_sims*length(n_model)\n\n#Create an empty data frame\nempty.df <- data.frame(matrix(NA, nrow = n_row, ncol = 7))\n#Rename the data frame columns\ncolnames(empty.df) <- c('sim.id', 'estimate', 'se', 'CI_2.5', 'CI_97.5',\n                        'model', 'coverage')\n\n#Sample a thousand data sets of 5,000 observations and perform linear regression \ncoefs_ex5 <- empty.df #assign the empty data frame\nk = 1\nfor (i in 1:n_sims){\n  set.seed(ex5_random.seed[i]) #set unique seed for each simulation \n#Sample data set from population   \n  sample.bias <- \n    ex5_population %>% \n    filter(P == 1) %>% \n    slice_sample(n = 5e3) #take a simple random sample of size 5,000\n#Fit models\n  for (j in 1:length(n_model)){\n    if (n_model[j] == 'mod.1'){\n      fit <- lm(formula = C ~ S,\n                data = sample.bias)\n    } else if (n_model[j] == 'mod.2'){\n      fit <- lm(formula = C ~ S + A,\n                data = sample.bias)  \n    } else {\n      fit <- lm(formula = C ~ S + N,\n                data = sample.bias)\n    }  \n#Compile matrix  \n  coefs_ex5[k, 1] <- i #simulation ID\n  coefs_ex5[k, 2] <- coef(fit)['Sfemale'] #point estimate\n  coefs_ex5[k, 3] <- summary(fit)$coef['Sfemale','Std. Error'] #standard error\n  coefs_ex5[k, 4:5] <- confint(fit, level = 0.95, type = 'Wald')['Sfemale', ] #confidence interval (Wald)\n  coefs_ex5[k, 6] <- n_model[j] #sample size\n  k = k + 1\n  }\n}\ncoefs_ex5 <- as_tibble(coefs_ex5)\n#View the data frame\ncoefs_ex5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,000 × 7\n   sim.id estimate    se CI_2.5 CI_97.5 model coverage\n    <int>    <dbl> <dbl>  <dbl>   <dbl> <chr> <lgl>   \n 1      1  -0.0715 0.134 -0.334   0.191 mod.1 NA      \n 2      1  -1.00   0.123 -1.24   -0.759 mod.2 NA      \n 3      1  -0.0119 0.107 -0.222   0.198 mod.3 NA      \n 4      2   0.0547 0.136 -0.211   0.321 mod.1 NA      \n 5      2  -0.973  0.125 -1.22   -0.727 mod.2 NA      \n 6      2   0.0312 0.108 -0.180   0.243 mod.3 NA      \n 7      3  -0.0387 0.137 -0.306   0.229 mod.1 NA      \n 8      3  -1.08   0.125 -1.32   -0.831 mod.2 NA      \n 9      3   0.0386 0.108 -0.173   0.250 mod.3 NA      \n10      4  -0.0152 0.136 -0.282   0.252 mod.1 NA      \n# ℹ 2,990 more rows\n```\n\n\n:::\n:::\n\n\n\n\nThe `coverage` is defined by setting its value to `1` if the confidence interval overlaps the data-generating parameter for `sex` (i.e., `b_sex.conf = -1`) and `0` otherwise.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculate coverage\ncoefs_ex5 <-\n  coefs_ex5 %>%\n  mutate(coverage = case_when(CI_2.5 > b_sex.conf[2] | CI_97.5 < b_sex.conf[2] ~ 0,\n                              CI_2.5 <= b_sex.conf[2] & CI_97.5 >= b_sex.conf[2] ~ 1,\n                              .default = NA))\n#View the data frame\ncoefs_ex5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,000 × 7\n   sim.id estimate    se CI_2.5 CI_97.5 model coverage\n    <int>    <dbl> <dbl>  <dbl>   <dbl> <chr>    <dbl>\n 1      1  -0.0715 0.134 -0.334   0.191 mod.1        0\n 2      1  -1.00   0.123 -1.24   -0.759 mod.2        1\n 3      1  -0.0119 0.107 -0.222   0.198 mod.3        0\n 4      2   0.0547 0.136 -0.211   0.321 mod.1        0\n 5      2  -0.973  0.125 -1.22   -0.727 mod.2        1\n 6      2   0.0312 0.108 -0.180   0.243 mod.3        0\n 7      3  -0.0387 0.137 -0.306   0.229 mod.1        0\n 8      3  -1.08   0.125 -1.32   -0.831 mod.2        1\n 9      3   0.0386 0.108 -0.173   0.250 mod.3        0\n10      4  -0.0152 0.136 -0.282   0.252 mod.1        0\n# ℹ 2,990 more rows\n```\n\n\n:::\n:::\n\n\n\n\nThe results are then plotted in @fig-DAG.ex5-CI.\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nmodel_names <- c('mod.1' = 'Model.1', \n                 'mod.2' = 'Model.2',\n                 'mod.3' = 'Model.3')\n\nggplot(data = subset(coefs_ex5, sim.id <= 2e2), aes(x = sim.id, y = estimate, ymin = CI_2.5, ymax = CI_97.5, colour = as.factor(coverage))) + \n  geom_hline(yintercept = b_sex.conf[2], alpha = 0.8, linetype = 'dashed', colour = 'blue') + \n  geom_linerange() +\n  geom_point(shape = 21, size = 1, fill = 'white', stroke = 0.5) +\n  scale_colour_manual('', \n                      values = c('black', '#FF4040'),\n                      breaks = c('1','0')) +\n  scale_y_continuous('Estimate', \n                     breaks = seq(from = -10, to = 10, by = 0.5),\n                     limits = c(-1.75, 1)) +\n  scale_x_continuous('Simulation ID') +\n  facet_wrap(model~., \n             labeller = labeller(model = model_names),\n             nrow = 3,\n             scales = 'fixed') +\n  theme(legend.position = 'none', \n        panel.grid = element_blank(),\n        panel.background = element_blank(),\n        panel.border = element_rect(colour = 'black', fill = NA),\n        axis.title.y = element_blank())\n```\n\n::: {.cell-output-display}\n![Estimates of the biological sex coefficient (only the first hundreds of the thousand simulations are shown). The white dots represent the point estimate, and the black lines represent the 95% confidence intervals. In red are highlighted the confidence intervals that do not overlap the parameter used to generate the data (dashed blue line).](ex5_simulation_files/figure-html/fig-DAG.ex5-CI-1.png){#fig-DAG.ex5-CI fig-align='center' width=5400}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n@fig-DAG.ex5-CI shows the first 200 estimates (point estimate and confidence interval) of the coefficient for biological sex for `Model.1`, `Model.2` and `Model.3`. If all the thousand simulations are considered, the frequency of the coverage of the calculated confidence intervals (i.e., how many times the confidence intervals overlap the data-generating parameter) is 0.0%, 95.7% and 0.0% for `Model.1`, `Model.2` and `Model.3`, respectively. Since the estimates of the causal effect for `Model.1` and `Model.3` are biased, the calculated confidence intervals for these models do not have the expected coverage. In fact, confidence intervals only quantify the uncertainty due to random error (i.e., sample variability), not systematic error (i.e., bias). Instead, the estimates from `Model.2` are unbiased and the calculated 95% confidence intervals have the expected coverage (i.e., overlap the data-generating parameter 95% of the times).\n\nWe can also visualize all the 1,000 estimates of the coefficient for biological sex for `Model.1`, `Model.2` and `Model.3` (the estimates were shown as white dots in @fig-DAG.ex5-CI).\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(data = coefs_ex5, aes(x = estimate, y = ifelse(after_stat(count) > 0, after_stat(count), NA))) +\n  geom_histogram(binwidth = 0.05, fill = 'white', colour = 'grey50') +\n  geom_vline(xintercept = b_sex.conf[2], colour = 'blue', linetype = 'dashed') +\n  scale_x_continuous('Estimate', \n                     breaks = seq(from = -10, to = 10, by = 0.25),\n                     limits = c(-1.55, 0.55)) +\n  facet_grid(model~., \n             labeller = labeller(model = model_names),\n             scales = 'fixed') +\n  theme(axis.title.y = element_blank(), \n        axis.text.y = element_blank(), \n        axis.ticks.y = element_blank(),\n        panel.grid = element_blank(),\n        panel.background = element_blank(),\n        panel.border = element_rect(colour = 'black', fill = NA))\n```\n\n::: {.cell-output-display}\n![Histogram of the 1,000 estimates of the biological sex coefficient for the three models. The blue dashed line represents the parameter used to generate the data.](ex5_simulation_files/figure-html/fig-DAG.ex5-mean-estimate-1.png){#fig-DAG.ex5-mean-estimate fig-align='center' width=5400}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\nIn @fig-DAG.ex5-mean-estimate, the estimated coefficients are visualized through a histogram. Here, we can see that the estimates for `Model.1` and `Model.3`are not clustered around the data-generating parameter (blue dashed line) having a mean estimate of 0.024 (with 0.135 standard deviation) and 0.027 (with 0.104 standard deviation), respectively. In contrast, the estimates for `Model.2` having a mean estimate of -0.998 (with 0.122 standard deviation) are centered around the data-generating parameter.\n\nAs expected, the inclusion of age $(\\text{A})$ in the regression model (i.e., using `Model.2`) leads to the correct estimate of the total average causal effect, while its exclusion (i.e., using `Model.1` and `Model.3`) leads to bias.\n\nThe bias occurs because there is selection bias. Generally, selection bias takes place when the participants selected for a study, are not representative of the larger population intended to be analyzed. In our example, participation is not random but influenced by variables that also affect the outcome, specifically, biological sex $(\\text{S})$ and age $(\\text{A})$. As a result, biological sex $(\\text{S})$ and age $(\\text{A})$ are associated in the biased sample, while they are not in the population (and consequently the random sample).\n\nTo better explain this bias, we visualize the relationship between biological sex $(\\text{S})$ and age $(\\text{A})$ in the biased and random sample.\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\ntruth.data.sim_ex5 <- function(n) {\n  b_age.conf = 0.3 #direct causal effect of A on C 1 or 0.2\n  b_sex.conf = c(0, -1) #direct causal effect of S on C\n  b_noise.conf = 0.7 #direct causal effect of N on C\n\n  A <- rep(18:59, length.out = n)\n  S <- c(rep('male', times = 84/2), rep('female', times = 84/2))\n  N <- 45\n  #Simulate acoustic sensation\n  C <- ifelse(S == 'male', 10 + b_sex.conf[1] + b_noise.conf * N + b_age.conf * A, 10 + b_sex.conf[2] + b_noise.conf * N + b_age.conf * A)\n  #Return tibble with simulated values\n  return(tibble(A, S, N, C))\n  }\n\ntruth <- truth.data.sim_ex5(84) %>%\n                    mutate(sample = 'population')\n\n\nex5_plot <- rbind(ex5_sample.random %>%\n                    mutate(sample = 'random'),\n                  ex5_sample.bias %>%\n                    mutate(sample = 'biased'))\n\n\n#Plot\nmean_val <- \n  ex5_plot %>% \n  group_by(S, sample) %>% \n  summarise(A = mean(A)) \n\nline_val <- \n  ex5_plot %>% \n  group_by(S, sample) %>% \n  summarise(A = mean(A)) %>%\n  pivot_wider(names_from = S, values_from = A)\n\ntruth_line <-\n  truth %>% \n  summarise(A = mean(A))\n\nex5_plot %>%\n  ggplot(aes(x = as.numeric(S), y = A)) +\n  geom_jitter(aes(fill = S, colour = S), shape = 19, size = 2, alpha = 0.1, stroke = NA, width = 0.2) + \n  geom_hline(data = truth_line, mapping = aes(yintercept = A , linetype = 'linea'), colour = 'black') +\n  geom_segment(data = line_val, aes(x = 1, y = male, xend = 2, yend = female), colour = 'black', linetype = 'solid', linewidth = 0.5) +\n  geom_point(data = mean_val, aes(fill = S, shape = '2'), colour = 'black', size = 3, stroke = 0.75) + #23\n  scale_colour_manual('',\n                      breaks = c('male', 'female', 'black'),\n                      values = c('#0072B2', '#D55E00', 'black')) +\n  scale_fill_manual('',\n                    breaks = c('male', 'female', 'black'),\n                    values = c('#0072B2', '#D55E00', NA)) +\n  scale_shape_manual('',\n                     breaks = c('2'),\n                     labels = c('mean age (sample)'),\n                     values = c(23)) +\n  scale_linetype_manual('',\n                        values = c('dashed'),\n                        breaks = c('linea'),\n                        labels = c('mean age (population)')) +\n  scale_x_continuous('Biological sex',\n                     breaks = c(1, 2),\n                     labels = c('male', 'female')) + \n  scale_y_continuous('Age', \n                     breaks = seq(from = 0, to = 100, by = 10)) +\n  guides(colour = guide_legend(override.aes = list(alpha = 1, fill = NA, size = 2), order = 1),\n         fill = 'none',\n         shape = guide_legend(override.aes = list(alpha = 1, size = 2), order = 2),\n         linetype = guide_legend(override.aes = list(alpha = 1, size = 2), order = 3)\n         ) +\n  facet_grid(.~sample) + \n  theme(legend.position = 'bottom',\n        legend.direction = 'horizontal',\n        panel.grid = element_blank(),\n        panel.background = element_blank(),\n        panel.border = element_rect(colour = 'black', fill = NA))\n```\n\n::: {.cell-output-display}\n![Visualization of the relationship between biological sex and age in the biased and random sample.](ex5_simulation_files/figure-html/fig-DAG.ex5-association-1.png){#fig-DAG.ex5-association fig-align='center' width=5400}\n:::\n:::\n\n\n\n\n@fig-DAG.ex5-association shows the relationship between biological sex $(\\text{S})$ and age $(\\text{A})$ in the biased and random sample. The horizontal dashed black line represents the average age in the population (i.e., 38.50 years) for both males and females. In the random sample biological sex $(\\text{S})$ and age $(\\text{A})$ are not associated and the average age for males (i.e., 38.66 years) and females (i.e., 38.85 years) are similar to one another with a difference of 0.20 years. However, due to selection bias, the average age for males and females in the biased sample is clearly different from the population average. Additionally, biological sex $(\\text{S})$ and age $(\\text{A})$ are associated because females are more likely to be selected than males, and older people are less likely to be selected than younger people. As a result, females in the biased sample are, on average, older than males (average of 28.70 years for females, 25.44 years for males and a difference of 3.26 years).\n\nWe can test for a difference between the average age of males and females more formally using bootstrapping. We will do so by using the custom functions `my_bootstrap()` and `summary_bootstrap()` (see code below).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n#Perform bootstrapping\nmy_bootstrap <- \n  function(data, variable, group){\n    samples <- tapply(X = data[[variable]], INDEX = data[[group]], FUN = function(x) sample(x, length(x), TRUE))\n    sapply(samples, mean)\n    }\n\n#Summarize the results from the bootstrapping\nsummary_bootstrap <-\n  function(bootstrap){\n    data.frame(t(bootstrap)) %>% \n      mutate(diff_f.m = female - male) %>%\n      mean_qi(.width = 0.95) %>%\n      rownames_to_column() %>%\n      select(-c(.width, .point, .interval)) %>%\n      pivot_longer(cols = !rowname, \n                   names_to = 'variable',\n                   values_to = 'value') %>%\n      select(-rowname) %>%\n      mutate(type = case_when(grepl('.lower', variable) ~ 'CI.lower',\n                              grepl('.upper', variable) ~ 'CI.upper',\n                              .default = 'estimate'),\n             variable = case_when(grepl('female', variable) ~ 'female',\n                                  grepl('male', variable) ~ 'male',\n                                  grepl('diff_f.m', variable) ~ 'diff_f.m',\n                                  .default = NA)) %>%\n      pivot_wider(names_from = 'type',\n                  values_from = 'value')\n    }\n```\n:::\n\n\n\n\nFirst, we define the number of times to run the `my_bootstrap()` function. We fixed the number of bootstrap samples equal to 10,000 (i.e., `n_bootstrap = 1e4`). Subsequently, we run the `my_bootstrap()` function using as input both the random and biased sample.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Number of bootstrap samples\nn_bootstrap = 1e4\nset.seed(2025) #for reproducibility\n#Bootstrap for random sample\nbootstrap_sample.random <- \n  replicate(n_bootstrap, my_bootstrap(data = ex5_sample.random, \n                                      variable = 'A', \n                                      group = 'S'))\nset.seed(2025) #for reproducibility\n#Bootstrap for biased sample\nbootstrap_sample.bias <- \n  replicate(n_bootstrap, my_bootstrap(data = ex5_sample.bias, \n                                      variable = 'A', \n                                      group = 'S'))\n```\n:::\n\n\n\n\nThe results from the bootstrapping are summarized using the `summary_bootstrap()` function.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#summarize bootstrap for random sample\nsummary_sample.random <-\n  summary_bootstrap(bootstrap_sample.random)\n#View summary\nsummary_sample.random\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  variable estimate CI.lower CI.upper\n  <chr>       <dbl>    <dbl>    <dbl>\n1 male       38.7     38.2     39.1  \n2 female     38.9     38.4     39.3  \n3 diff_f.m    0.199   -0.476    0.883\n```\n\n\n:::\n\n```{.r .cell-code}\n#summarize bootstrap for biased sample\nsummary_sample.bias <- \n  summary_bootstrap(bootstrap_sample.bias)\n#View summary\nsummary_sample.bias\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  variable estimate CI.lower CI.upper\n  <chr>       <dbl>    <dbl>    <dbl>\n1 male        25.4     25.2     25.7 \n2 female      28.7     28.4     29.0 \n3 diff_f.m     3.26     2.88     3.65\n```\n\n\n:::\n:::\n\n\n\n\nFor the random sample, the age difference between males and females is 0.20 with 95% CI \\[-0.48, 0.88\\]. Since the 95% CI includes zero, the average age of females is not statistically significantly different from the average age of males, at the 0.05 level. Instead, for the biased sample, the age difference between males and females is 3.26 with 95% CI \\[2.88, 3.65\\]. Since the 95% CI does not include zero, the average age of females is statistically significantly different from the average age of males, at the 0.05 level.\n\nHowever, once we adjust for age $(\\text{A})$ in the regression model (i.e., using `Model.2`) the bias disappears. We can visualize this in @fig-DAG.ex5-regression\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\npred_ex5_Model.2 <- cbind(ex5_sample.bias, \n                          predict(ex5_Model.2, interval = 'confidence', level = 0.95))\n\nex5_sample.bias %>%\n  ggplot(aes(x = A, y = C)) +\n  geom_point(aes(colour = S), shape = 19, size = 2, alpha = 0.07, stroke = NA) +\n  geom_ribbon(data = pred_ex5_Model.2, aes(x = A , y = fit, ymin = lwr, ymax = upr, fill = S), alpha = 0.2, show.legend = NA) +\n  geom_line(data = pred_ex5_Model.2, aes(x = A , y = fit, colour = S, linetype = 'sample', linewidth = 'sample')) + \n  geom_line(data = truth, mapping = aes(colour = S, linetype = 'pop', linewidth = 'pop')) +\nscale_colour_manual('',\n                      breaks = c('male', 'female'),\n                      values = c('#0072B2', '#D55E00')) +\n  scale_fill_manual('',\n                      breaks = c('male', 'female'),\n                      values = c('#0072B2', '#D55E00')) +\n  scale_linetype_manual('',\n                        breaks = c('pop', 'sample'),\n                        labels = c('population', 'sample'),\n                        values = c('dashed', 'solid')) +\n  scale_linewidth_manual('',\n                         breaks = c('pop', 'sample'),\n                         labels = c('population', 'sample'),\n                         values = c(1, 0.5)) +\n  scale_x_continuous('Age') + \n  scale_y_continuous('Acoustic sensation', \n                     breaks = seq(from = 0, to = 100, by = 10)) +\n  facet_grid(.~S) +\n  guides(linetype = guide_legend(override.aes = list(alpha = 1, colour = 'black', fill = NA, linewidth = 0.5))) +\n  theme(legend.position = 'bottom',\n        legend.direction = 'horizontal',\n        panel.grid = element_blank(),\n        panel.background = element_blank(),\n        panel.border = element_rect(colour = 'black', fill = NA))\n```\n\n::: {.cell-output-display}\n![Visualization of the relationship between biological sex and acoustic sensation conditioning on age.](ex5_simulation_files/figure-html/fig-DAG.ex5-regression-1.png){#fig-DAG.ex5-regression fig-align='center' width=5400}\n:::\n:::\n\n\n\n\nIn @fig-DAG.ex5-regression, we can observe that within each age level the regression lines for the biased sample for males (i.e., solid blue line) and female (i.e., solid orange line) is very similar to the population lines (i.e., dashed lines). Adjusting for age closed the backdoor path leading to the correct estimate of the total average causal effect.\n\n#### Bayesian framework\n\n<details>\n\n<summary>Click to expand</summary>\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Fit the linear regression model with S and C (Model 1)\nex5_Model.1 <- stan_glm(formula = C ~ S,\n                        family = gaussian(),\n                        data = ex5_sample.bias,\n                        #Prior coefficients\n                        prior = normal(location = c(0), scale = c(2)),\n                        #Prior intercept\n                        prior_intercept = normal(location = 10, scale = 6),\n                        #Prior sigma\n                        prior_aux = exponential(rate = 0.5),\n                        iter = 4000, warmup = 1000, \n                        save_warmup = TRUE,\n                        chains = 4, cores = 4,\n                        seed = 2025) #for reproducibility   \n#View of the model\nex5_Model.1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstan_glm\n family:       gaussian [identity]\n formula:      C ~ S\n observations: 5000\n predictors:   2\n------\n            Median MAD_SD\n(Intercept) 49.2    0.1  \nSfemale     -0.1    0.1  \n\nAuxiliary parameter(s):\n      Median MAD_SD\nsigma 4.6    0.0   \n\n------\n* For help interpreting the printed output see ?print.stanreg\n* For info on the priors used see ?prior_summary.stanreg\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Fit the linear regression model with S, A and C (Model 2)\nex5_Model.2 <- stan_glm(formula = C ~ S + A,\n                        family = gaussian(),\n                        data = ex5_sample.bias,\n                        #Prior coefficients\n                        prior = normal(location = c(0, 0), scale = c(2, 1)),\n                        #Prior intercept\n                        prior_intercept = normal(location = 10, scale = 6),\n                        #Prior sigma\n                        prior_aux = exponential(rate = 0.5),\n                        iter = 4000, warmup = 1000, \n                        save_warmup = TRUE,\n                        chains = 4, cores = 4,\n                        seed = 2025) #for reproducibility\n#View of the model\nex5_Model.2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstan_glm\n family:       gaussian [identity]\n formula:      C ~ S + A\n observations: 5000\n predictors:   3\n------\n            Median MAD_SD\n(Intercept) 42.0    0.2  \nSfemale     -1.0    0.1  \nA            0.3    0.0  \n\nAuxiliary parameter(s):\n      Median MAD_SD\nsigma 4.1    0.0   \n\n------\n* For help interpreting the printed output see ?print.stanreg\n* For info on the priors used see ?prior_summary.stanreg\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Fit the linear regression model with S, N and C (Model 3)\nex5_Model.3 <- stan_glm(formula =  C ~ S + N,\n                        family = gaussian(),\n                        data = ex5_sample.bias,\n                        #Prior coefficients\n                        prior = normal(location = c(0, 0), scale = c(2, 1.4)),\n                        #Prior intercept\n                        prior_intercept = normal(location = 10, scale = 6),\n                        #Prior sigma\n                        prior_aux = exponential(rate = 0.5),\n                        iter = 4000, warmup = 1000, \n                        save_warmup = TRUE,\n                        chains = 4, cores = 4,\n                        seed = 2025) #for reproducibility\n#View of the model\nex5_Model.3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstan_glm\n family:       gaussian [identity]\n formula:      C ~ S + N\n observations: 5000\n predictors:   3\n------\n            Median MAD_SD\n(Intercept) 18.2    0.6  \nSfemale      0.0    0.1  \nN            0.7    0.0  \n\nAuxiliary parameter(s):\n      Median MAD_SD\nsigma 3.7    0.0   \n\n------\n* For help interpreting the printed output see ?print.stanreg\n* For info on the priors used see ?prior_summary.stanreg\n```\n\n\n:::\n:::\n\n\n\n\nIn Bayesian analysis, there are important diagnostics that have to be carried out in order to assess the convergence and efficiency of the Markov Chains. This is done by using the `monitor()` function which computes summaries of MCMC (Markov Chain Monte Carlo) draws and monitor convergence. Specifically, we will look at `Rhat`, `Bulk_ESS` and `Tail_ESS` metrics.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Diagnostics for model 1\nmonitor(ex5_Model.1$stanfit)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInference for the input samples (4 chains: each with iter = 4000; warmup = 0):\n\n                    Q5      Q50      Q95     Mean  SD  Rhat Bulk_ESS Tail_ESS\n(Intercept)       49.0     49.2     49.4     49.2 0.1     1    11813     8119\nSfemale           -0.3     -0.1      0.2     -0.1 0.1     1    11714     7257\nsigma              4.5      4.6      4.7      4.6 0.0     1    11962     8118\nmean_PPD          49.0     49.2     49.3     49.2 0.1     1    12216    10407\nlog-posterior -14737.4 -14734.6 -14733.6 -14735.0 1.2     1     4766     7546\n\nFor each parameter, Bulk_ESS and Tail_ESS are crude measures of \neffective sample size for bulk and tail quantities respectively (an ESS > 100 \nper chain is considered good), and Rhat is the potential scale reduction \nfactor on rank normalized split chains (at convergence, Rhat <= 1.05).\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Diagnostics for model 2\nmonitor(ex5_Model.2$stanfit) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInference for the input samples (4 chains: each with iter = 4000; warmup = 0):\n\n                    Q5      Q50      Q95     Mean  SD  Rhat Bulk_ESS Tail_ESS\n(Intercept)       41.6     42.0     42.3     42.0 0.2     1    15502     9146\nSfemale           -1.2     -1.0     -0.8     -1.0 0.1     1    13638     7965\nA                  0.3      0.3      0.3      0.3 0.0     1    14496     8927\nsigma              4.1      4.1      4.2      4.1 0.0     1    16158     8782\nmean_PPD          49.0     49.2     49.3     49.2 0.1     1    11937    10550\nlog-posterior -14206.2 -14203.1 -14201.8 -14203.5 1.4     1     4872     6850\n\nFor each parameter, Bulk_ESS and Tail_ESS are crude measures of \neffective sample size for bulk and tail quantities respectively (an ESS > 100 \nper chain is considered good), and Rhat is the potential scale reduction \nfactor on rank normalized split chains (at convergence, Rhat <= 1.05).\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Diagnostics for model 2\nmonitor(ex5_Model.3$stanfit) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInference for the input samples (4 chains: each with iter = 4000; warmup = 0):\n\n                    Q5      Q50      Q95     Mean  SD  Rhat Bulk_ESS Tail_ESS\n(Intercept)       17.2     18.2     19.1     18.2 0.6     1    14685     8872\nSfemale           -0.2      0.0      0.2      0.0 0.1     1    15154     8110\nN                  0.7      0.7      0.7      0.7 0.0     1    14833     8453\nsigma              3.6      3.7      3.7      3.7 0.0     1    14710     8520\nmean_PPD          49.0     49.2     49.3     49.2 0.1     1    13218    10150\nlog-posterior -13619.1 -13616.0 -13614.7 -13616.4 1.4     1     5176     7062\n\nFor each parameter, Bulk_ESS and Tail_ESS are crude measures of \neffective sample size for bulk and tail quantities respectively (an ESS > 100 \nper chain is considered good), and Rhat is the potential scale reduction \nfactor on rank normalized split chains (at convergence, Rhat <= 1.05).\n```\n\n\n:::\n:::\n\n\n\n\n`Rhat` is a metric used to assess the convergence of Markov Chain Monte Carlo (MCMC) simulations. It helps determine if the MCMC chains have adequately explored the target posterior distribution. Specifically, it compares the between- and within-chain estimates for model parameters: If chains have not mixed well (i.e., the between- and within-chain estimates do not agree), R-hat is larger than 1. A general rule of thumb is to use the sample only if R-hat is less than 1.05; a larger value suggests that the chains have not mixed well, and the results might not be reliable. In our two models, all `Rhat` are equal to 1 indicating that the chains have mixed well and have adequately explored the target posterior distribution.\n\n`Bulk_ESS` and `Tail_ESS` stand for 'Bulk Effective Sample Size' and 'Tail Effective Sample Size,' respectively. Since MCMC samples are not truly independent (they are correlated), these metrics assess the sampling efficiencies, that is, they help evaluating how efficiently the MCMC sampler is exploring the parameters space.\n\n-   `Bulk_ESS` is a useful measure for sampling efficiency in the bulk (center) of the distribution (e.g., efficiency of mean and median estimates);\n-   `Tail_ESS` is a useful measure for sampling efficiency in the tails of the distribution (e.g., efficiency of variance and tail quantile estimates). A general rule of thumb is that both `Bulk-ESS` and `Tail-ESS` should be at least 100 (approximately) per Markov Chain in order to be reliable and indicate that estimates of respective posterior quantiles are reliable. In our two models, all `Bulk-ESS` and `Tail-ESS` are well above 400 (i.e., 100 multiplied by 4, the number of chains we used) indicating that estimates of posterior quantiles are reliable.\n\nSince we have established that the posteriors are reliable, we can now explore the model estimates. The estimated coefficients for the two models are then plotted in @fig-DAG.ex5-estimate-Bayesian.\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#Extract draws from model 1 \npost_ex5_Model.1 <-\n  ex5_Model.1 %>% \n  spread_draws(Sfemale) %>% #extract draws from the fitted model\n  mutate(model = 'Model.1') #add a new column to specify that the model\n\n#Extract draws from model 2\npost_ex5_Model.2 <-\n  ex5_Model.2 %>% \n  spread_draws(Sfemale) %>% #extract draws from the fitted model\n  mutate(model = 'Model.2') #add a new column to specify that the model\n\n#Extract draws from model 2\npost_ex5_Model.3 <-\n  ex5_Model.3 %>% \n  spread_draws(Sfemale) %>% #extract draws from the fitted model\n  mutate(model = 'Model.3') #add a new column to specify that the model\n\n#Combine draws\nplot.post <- rbind(post_ex5_Model.1, post_ex5_Model.2, post_ex5_Model.3)\n\n# Plot\nplot.post  %>%\n  ggplot(aes(y = model, x = Sfemale)) +\n  stat_slabinterval(point_interval = 'mean_hdi',\n                    .width = c(.95)) +\n  geom_vline(xintercept = b_sex.conf[2], alpha = 0.8, linetype = 'dashed', colour = 'blue') + \n  scale_x_continuous('Estimate', \n                     breaks = seq(from = -5, to = 5, by = 0.25),\n                     limits = c(-1.55, 0.55)\n                     ) +\n  theme(panel.grid = element_blank(),\n        panel.background = element_blank(),\n        panel.border = element_rect(colour = 'black', fill = NA),\n        axis.title.y = element_blank())\n```\n\n::: {.cell-output-display}\n![Posterior distribution of the biological sex coefficient for the three models. The black line and dot at the bottom of each distribution represent the highest density interval (HDI) and the mean, respectively.](ex5_simulation_files/figure-html/fig-DAG.ex5-estimate-Bayesian-1.png){#fig-DAG.ex5-estimate-Bayesian fig-align='center' width=5400}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n@fig-DAG.ex5-estimate-Bayesian shows the estimates (mean and 95% HDI) of the coefficient for biological sex for `Model.1`, `Model.2`, and `Model.3`.\n\nFor `Model.1` we found a negative coefficient between biological sex $(\\text{S})$ and acoustic sensation $(\\text{C})$ (mean = -0.072, 95% HDI \\[-0.337, 0.193\\]). The estimated causal effect is biased, leading to the wrong conclusion that changing biological sex from `male` to `female` causes a decrease in acoustic sensation by -0.072 units, on average.\n\nFor `Model.2` we found a negative coefficient between biological sex $(\\text{S})$ and acoustic sensation $(\\text{C})$ (mean = -0.997, 95% HDI \\[-1.233, -0.745\\]). The estimated causal effect is unbiased, leading to the correct conclusion that changing biological sex from `male` to `female` causes a decrease in acoustic sensation by -0.997 units, on average.\n\nFor `Model.3` we found a positive coefficient between biological sex $(\\text{S})$ and acoustic sensation $(\\text{C})$ (mean = -0.011, 95% HDI \\[-0.224, 0.195\\]). The estimated causal effect is biased, leading to the wrong conclusion that changing biological sex from `male` to `female` causes a decrease in acoustic sensation by -0.011 units, on average.\n\nImportantly, for both `Model.1`, `Model.2` and `Model.3`, the 95% HDI is the range of parameter values within which the most credible 95% of the posterior distribution falls. Unlike frequentist confidence interval, the Bayesian 95% HDI has a direct probabilistic meaning: every point inside the HDI has a higher probability density than any point outside the interval. Therefore, given the model, the prior and the data, we can say that there is a 95% probability that the data-generating parameter (i.e., `b_sex.conf = -1`) lies within the HDI. However, since `Model.1` and `Model.3` lead to biased estimates, we will reach the wrong conclusion by stating that there is a 95% probability that the data-generating parameter lies within the \\[-0.337, 0.193\\] and \\[-0.224, 0.195\\] intervals, for `Model.1` and `Model.3` respectively. This probability is 0%.\n\nAs expected, the inclusion of age $(\\text{A})$ in the regression model (i.e., using `Model.2`) leads to the correct estimate of the total average causal effect, while its exclusion (i.e., using `Model.1` and `Model.3`) leads to bias.\n\nThe bias occurs because there is selection bias. Generally, selection bias takes place when the participants selected for a study, are not representative of the larger population intended to be analyzed. In our example, participation is not random but influenced by variables that also affect the outcome, specifically, biological sex $(\\text{S})$ and age $(\\text{A})$. As a result, biological sex $(\\text{S})$ and age $(\\text{A})$ are associated in the biased sample, while they are not in the population (and consequently the random sample).\n\nTo better explain this bias, we visualize the relationship between biological sex $(\\text{S})$ and age $(\\text{A})$ in the biased and random sample.\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nex5_plot %>%\n  ggplot(aes(x = as.numeric(S), y = A)) +\n  geom_jitter(aes(fill = S, colour = S), shape = 19, size = 2, alpha = 0.1, stroke = NA, width = 0.2) + \n  geom_hline(data = truth_line, mapping = aes(yintercept = A , linetype = 'linea'), colour = 'black') +\n  geom_segment(data = line_val, aes(x = 1, y = male, xend = 2, yend = female), colour = 'black', linetype = 'solid', linewidth = 0.5) +\n  geom_point(data = mean_val, aes(fill = S, shape = '2'), colour = 'black', size = 3, stroke = 0.75) + \n  scale_colour_manual('',\n                      breaks = c('male', 'female', 'black'),\n                      values = c('#0072B2', '#D55E00', 'black')) +\n  scale_fill_manual('',\n                    breaks = c('male', 'female', 'black'),\n                    values = c('#0072B2', '#D55E00', NA)) +\n  scale_shape_manual('',\n                     breaks = c('2'),\n                     labels = c('mean age (sample)'),\n                     values = c(23)) +\n  scale_linetype_manual('',\n                        values = c('dashed'),\n                        breaks = c('linea'),\n                        labels = c('mean age (population)')) +\n  scale_x_continuous('Biological sex',\n                     breaks = c(1, 2),\n                     labels = c('male', 'female')) + \n  scale_y_continuous('Age', \n                     breaks = seq(from = 0, to = 100, by = 10)) +\n  guides(colour = guide_legend(override.aes = list(alpha = 1, fill = NA, size = 2), order = 1),\n         fill = 'none',\n         shape = guide_legend(override.aes = list(alpha = 1, size = 2), order = 2),\n         linetype = guide_legend(override.aes = list(alpha = 1, size = 2), order = 3)\n         ) +\n  facet_grid(.~sample) + \n  theme(legend.position = 'bottom',\n        legend.direction = 'horizontal',\n        panel.grid = element_blank(),\n        panel.background = element_blank(),\n        panel.border = element_rect(colour = 'black', fill = NA))\n```\n\n::: {.cell-output-display}\n![Visualization of the relationship between biological sex and age in the biased and random sample.](ex5_simulation_files/figure-html/fig-DAG.ex5-association-Bayesian-1.png){#fig-DAG.ex5-association-Bayesian fig-align='center' width=5400}\n:::\n:::\n\n\n\n\n@fig-DAG.ex5-association-Bayesian shows the relationship between biological sex $(\\text{S})$ and age $(\\text{A})$ in the biased and random sample. The horizontal dashed black line represents the average age in the population (i.e., 38.50 years) for both males and females. In the random sample biological sex $(\\text{S})$ and age $(\\text{A})$ are not associated and the average age for males (i.e., 38.66 years) and females (i.e., 38.85 years) are similar to one another with a difference of 0.20 years. However, due to selection bias, the average age for males and females in the biased sample is clearly different from the population average. Additionally, biological sex $(\\text{S})$ and age $(\\text{A})$ are associated because females are more likely to be selected than males, and older people are less likely to be selected than younger people. As a result, females in the biased sample are, on average, older than males (average of 28.70 years for females, 25.44 years for males and a difference of 3.26 years).\n\nWe can test for a difference between the average age of males and females more formally using Bayesian bootstrapping. We will do so by using the custom functions `my_Bayesian.bootstrap()` (see code below).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n#Perform bootstrapping\nmy_Bayesian.bootstrap <-\n  function(data, n_bootstrap, variable, group, group.level){\n    data <- as.data.frame(data)\n    bootstrap <- data.frame(c(bayesboot(data = data[ data[[group]] == group.level[1],  variable], R = n_bootstrap, weighted.mean, use.weights = TRUE) %>% pull()),\n                            c(bayesboot(data = data[ data[[group]] == group.level[2],  variable], R = n_bootstrap, weighted.mean, use.weights = TRUE) %>% pull())) \n    \n    colnames(bootstrap) <- c(group.level[1], group.level[2])\n    return(bootstrap)\n  }\n```\n:::\n\n\n\n\nFirst, we define the number of times to run the `my_Bayesian.bootstrap()` function. We fixed the number of bootstrap samples equal to 10,000 (i.e., `n_bootstrap = 1e4`). Subsequently, we run the `my_Bayesian.bootstrap()` function using as input both the random and biased sample.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2025) #for reproducibility\n#Bootstrap for random sample\nBayesian.bootstrap_sample.random <- \n  my_Bayesian.bootstrap(data = ex5_sample.random, \n                        n_bootstrap = 1e4,\n                        variable = 'A', \n                        group = 'S',\n                        group.level = c('male', 'female'))\n\nset.seed(2025) #for reproducibility\n#Bootstrap for biased sample\nBayesian.bootstrap_sample.biased <- \n  my_Bayesian.bootstrap(data = ex5_sample.bias, \n                        n_bootstrap = 1e4,\n                        variable = 'A', \n                        group = 'S',\n                        group.level = c('male', 'female'))\n```\n:::\n\n\n\n\nWe can then calculate and visualize the age difference of the posterior sample between females and males (see @fig-DAG.ex5-association2-Bayesian).\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#Extract draws from model (random sample)\npost_Bayesian.bootstrap_sample.random <-\n  Bayesian.bootstrap_sample.random %>% \n  mutate(diff = female - male,\n         sample = 'random') #add a new column to specify that the model\n\n#Extract draws from model (biased sample)\npost_Bayesian.bootstrap_sample.biased <-\n  Bayesian.bootstrap_sample.biased %>% \n    mutate(diff = female - male,\n           sample = 'biased') #add a new column to specify that the model\n\n#Combine draws\nplot.post.corr <- rbind(post_Bayesian.bootstrap_sample.random, post_Bayesian.bootstrap_sample.biased)\n\n# Plot\nplot.post.corr %>%\n  ggplot(aes(y = sample, x = diff)) +\n  stat_slabinterval(point_interval = 'mean_hdi',\n                    .width = c(.95)) +\n  geom_vline(xintercept = 0, alpha = 0.8, linetype = 'dashed', colour = 'blue') + \n  scale_x_continuous('Estimate', \n                     breaks = seq(from = -5, to = 5, by = 0.5),\n                     ) +\n  theme(panel.grid = element_blank(),\n        panel.background = element_blank(),\n        panel.border = element_rect(colour = 'black', fill = NA),\n        axis.title.y = element_blank())\n```\n\n::: {.cell-output-display}\n![Age difference between males and females in the biased and random sample.](ex5_simulation_files/figure-html/fig-DAG.ex5-association2-Bayesian-1.png){#fig-DAG.ex5-association2-Bayesian fig-align='center' width=5400}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\nFor the random sample, the age difference between males and females has a mean of 0.20 with 95% HDI \\[-0.51, 0.83\\]. Instead, for the biased sample, the age difference between males and females has a mean of 3.26 with 95% HDI \\[2.88, 3.64\\].\n\nHowever, once we adjust for age $(\\text{A})$ in the regression model (i.e., using `Model.2`) the bias disappears. We can visualize this in @fig-DAG.ex5-regression-Bayesian.\n\n\n\n\n::: {.cell .fig-cap-location-bottom layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#Expected value of the posterior predictive distribution (epred) for model 2\nepred_ex5_Model.2 <- \n  ex5_Model.2 %>%\n  epred_draws(newdata = ex5_sample.bias, \n              seed = 2025) %>%\n  group_by(A, S) %>%\n  mean_hdi(.epred, .width = .95) %>%\n  ungroup()\n\nex5_sample.bias %>%\n  ggplot(aes(x = A, y = C)) +\n  geom_point(aes(colour = S), shape = 19, size = 2, alpha = 0.07, stroke = NA) +\n  geom_ribbon(data = epred_ex5_Model.2, aes(x = A , y = .epred, ymin = .lower, ymax = .upper, fill = S), alpha = 0.2, show.legend = NA) +\n  geom_line(data = epred_ex5_Model.2, aes(x = A , y = .epred, colour = S, linetype = 'sample', linewidth = 'sample')) + \n  geom_line(data = truth, mapping = aes(colour = S, linetype = 'pop', linewidth = 'pop')) +\n\n  scale_colour_manual('',\n                      breaks = c('male', 'female'),\n                      values = c('#0072B2', '#D55E00')) +\n  scale_fill_manual('',\n                      breaks = c('male', 'female'),\n                      values = c('#0072B2', '#D55E00')) +\n  scale_linetype_manual('',\n                        breaks = c('pop', 'sample'),\n                        labels = c('population', 'sample'),\n                        values = c('dashed', 'solid')) +\n  scale_linewidth_manual('',\n                         breaks = c('pop', 'sample'),\n                         labels = c('population', 'sample'),\n                         values = c(1, 0.5)) +\n  scale_x_continuous('Age') + \n  scale_y_continuous('acoustic sensation', \n                     breaks = seq(from = 0, to = 100, by = 10)) +\n  facet_grid(.~S) + \n  guides(linetype = guide_legend(override.aes = list(alpha = 1, colour = 'black', fill = NA, linewidth = 0.5))) +\n  theme(legend.position = 'bottom',\n        legend.direction = 'horizontal',\n        panel.grid = element_blank(),\n        panel.background = element_blank(),\n        panel.border = element_rect(colour = 'black', fill = NA))\n```\n\n::: {.cell-output-display}\n![Visualization of the relationship between biological sex and acoustic sensation conditioning on age.](ex5_simulation_files/figure-html/fig-DAG.ex5-regression-Bayesian-1.png){#fig-DAG.ex5-regression-Bayesian fig-align='center' width=5400}\n:::\n:::\n\n\n\n\nIn @fig-DAG.ex5-regression-Bayesian, we can observe that within each age level the regression lines for the biased sample for males (i.e., solid blue line) and female (i.e., solid orange line) is very similar to the population lines (i.e., dashed lines). Adjusting for age closed the backdoor path leading to the correct estimate of the total average causal effect.\n\n</details>\n\n## Session info {.unnumbered}\n\nVersion information about R, the OS and attached or loaded packages.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.2.3 (2023-03-15 ucrt)\nPlatform: x86_64-w64-mingw32/x64 (64-bit)\nRunning under: Windows 10 x64 (build 26200)\n\nMatrix products: default\n\nlocale:\n[1] LC_COLLATE=English_United Kingdom.utf8 \n[2] LC_CTYPE=English_United Kingdom.utf8   \n[3] LC_MONETARY=English_United Kingdom.utf8\n[4] LC_NUMERIC=C                           \n[5] LC_TIME=English_United Kingdom.utf8    \n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] bayesboot_0.2.3     rstan_2.32.7        StanHeaders_2.32.10\n [4] gt_1.1.0            lubridate_1.9.4     forcats_1.0.1      \n [7] stringr_1.6.0       dplyr_1.1.4         purrr_1.2.0        \n[10] readr_2.1.6         tidyr_1.3.1         tibble_3.3.0       \n[13] ggplot2_4.0.1       tidyverse_2.0.0     ggdist_3.3.3       \n[16] tidybayes_3.0.7     rstanarm_2.32.2     Rcpp_1.1.0         \n[19] dagitty_0.3-4       ggdag_0.2.13       \n\nloaded via a namespace (and not attached):\n  [1] backports_1.5.0       plyr_1.8.9            igraph_2.2.1         \n  [4] splines_4.2.3         svUnit_1.0.8          crosstalk_1.2.2      \n  [7] rstantools_2.5.0      inline_0.3.21         digest_0.6.38        \n [10] htmltools_0.5.8.1     viridis_0.6.5         magrittr_2.0.4       \n [13] checkmate_2.3.3       memoise_2.0.1         tzdb_0.5.0           \n [16] graphlayouts_1.2.2    RcppParallel_5.1.11-1 matrixStats_1.5.0    \n [19] xts_0.14.1            timechange_0.3.0      colorspace_2.1-2     \n [22] ggrepel_0.9.6         rbibutils_2.4         xfun_0.54            \n [25] jsonlite_2.0.0        lme4_1.1-37           survival_3.8-3       \n [28] zoo_1.8-14            glue_1.8.0            reformulas_0.4.2     \n [31] polyclip_1.10-7       gtable_0.3.6          V8_8.0.1             \n [34] distributional_0.5.0  car_3.1-3             pkgbuild_1.4.8       \n [37] abind_1.4-8           scales_1.4.0          miniUI_0.1.2         \n [40] viridisLite_0.4.2     xtable_1.8-4          Formula_1.2-5        \n [43] stats4_4.2.3          DT_0.34.0             htmlwidgets_1.6.4    \n [46] threejs_0.3.4         arrayhelpers_1.1-0    RColorBrewer_1.1-3   \n [49] posterior_1.6.1       pkgconfig_2.0.3       loo_2.8.0            \n [52] farver_2.1.2          sass_0.4.10           utf8_1.2.6           \n [55] tidyselect_1.2.1      labeling_0.4.3        rlang_1.1.6          \n [58] reshape2_1.4.5        later_1.4.4           tools_4.2.3          \n [61] cachem_1.1.0          cli_3.6.5             generics_0.1.4       \n [64] evaluate_1.0.5        fastmap_1.2.0         yaml_2.3.10          \n [67] knitr_1.50            fs_1.6.6              tidygraph_1.3.1      \n [70] ggraph_2.2.2          nlme_3.1-168          mime_0.13            \n [73] xml2_1.5.0            compiler_4.2.3        bayesplot_1.14.0     \n [76] shinythemes_1.2.0     rstudioapi_0.17.1     curl_7.0.0           \n [79] tweenr_2.0.3          stringi_1.8.7         lattice_0.22-7       \n [82] Matrix_1.6-5          nloptr_2.2.1          markdown_2.0         \n [85] shinyjs_2.1.0         tensorA_0.36.2.1      vctrs_0.6.5          \n [88] pillar_1.11.1         lifecycle_1.0.4       Rdpack_2.6.4         \n [91] httpuv_1.6.16         QuickJSR_1.8.1        R6_2.6.1             \n [94] promises_1.5.0        gridExtra_2.3         codetools_0.2-20     \n [97] boot_1.3-32           colourpicker_1.3.0    MASS_7.3-58.2        \n[100] gtools_3.9.5          withr_3.0.2           shinystan_2.6.0      \n[103] parallel_4.2.3        hms_1.1.4             grid_4.2.3           \n[106] coda_0.19-4.1         minqa_1.2.8           rmarkdown_2.30       \n[109] S7_0.2.1              carData_3.0-5         otel_0.2.0           \n[112] ggforce_0.5.0         shiny_1.11.1          base64enc_0.1-3      \n[115] dygraphs_1.1.1.6     \n```\n\n\n:::\n:::\n",
    "supporting": [
      "ex5_simulation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}