<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.44">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>3&nbsp; Simulation example – Supplementary material</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ex4_simulation.html" rel="next">
<link href="./ex2_simulation.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ex3_simulation.html">Post-treatment bias</a></li><li class="breadcrumb-item"><a href="./ex3_simulation.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Simulation example</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Supplementary material</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Simpson’s paradox</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ex1_simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Simulation example</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">M-bias</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ex2_simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Simulation example</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Post-treatment bias</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ex3_simulation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Simulation example</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Case-control bias</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ex4_simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Simulation example</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Selection bias</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ex5_simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Simulation example</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#data-generating-process" id="toc-data-generating-process" class="nav-link active" data-scroll-target="#data-generating-process"><span class="header-section-number">3.1</span> Data-generating process</a></li>
  <li><a href="#synthetic-data-set" id="toc-synthetic-data-set" class="nav-link" data-scroll-target="#synthetic-data-set"><span class="header-section-number">3.2</span> Synthetic data set</a></li>
  <li>
<a href="#data-analysis" id="toc-data-analysis" class="nav-link" data-scroll-target="#data-analysis"><span class="header-section-number">3.3</span> Data analysis</a>
  <ul class="collapse">
<li><a href="#identification" id="toc-identification" class="nav-link" data-scroll-target="#identification"><span class="header-section-number">3.3.1</span> Identification</a></li>
  <li><a href="#estimation" id="toc-estimation" class="nav-link" data-scroll-target="#estimation"><span class="header-section-number">3.3.2</span> Estimation</a></li>
  </ul>
</li>
  <li><a href="#session-info" id="toc-session-info" class="nav-link" data-scroll-target="#session-info">Session info</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ex3_simulation.html">Post-treatment bias</a></li><li class="breadcrumb-item"><a href="./ex3_simulation.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Simulation example</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-ex3" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Simulation example</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#Load packages</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/r-causal/ggdag">ggdag</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://www.dagitty.net">dagitty</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://mc-stan.org/rstanarm/">rstanarm</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://mjskay.github.io/tidybayes/">tidybayes</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://mjskay.github.io/ggdist/">ggdist</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://gt.rstudio.com">gt</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://mc-stan.org/rstan/">rstan</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="data-generating-process" class="level2" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="data-generating-process">
<span class="header-section-number">3.1</span> Data-generating process</h2>
<p>The data-generating process is described via the directed acyclic graph (DAG) in <a href="#fig-DAG.ex3-1" class="quarto-xref">Fig.&nbsp;<span>3.1</span></a>. In this DAG, window shading <span class="math inline">\((\text{W})\)</span> influences perceived warmth <span class="math inline">\((\text{P})\)</span> both directly and indirectly, passing through daylight <span class="math inline">\((\text{D})\)</span>. Additionally, window shading <span class="math inline">\((\text{W})\)</span> also indirectly influences visual comfort <span class="math inline">\((\text{V})\)</span> through daylight <span class="math inline">\((\text{D})\)</span>.</p>
<div class="cell fig-cap-location-bottom" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb2" data-cap-location="bottom"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dag_coords.ex3</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>name <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'W'</span>, <span class="st">'D'</span>, <span class="st">'V'</span>, <span class="st">'P'</span><span class="op">)</span>,</span>
<span>             x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">3.5</span>, <span class="fl">6</span>, <span class="fl">6</span><span class="op">)</span>,</span>
<span>             y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">2</span>, <span class="fl">1</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">DAG.ex3</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://r-causal.github.io/ggdag/reference/dagify.html">dagify</a></span><span class="op">(</span><span class="va">D</span> <span class="op">~</span> <span class="va">W</span>,</span>
<span>         <span class="va">P</span> <span class="op">~</span> <span class="va">W</span> <span class="op">+</span> <span class="va">D</span>,</span>
<span>         <span class="va">V</span> <span class="op">~</span> <span class="va">D</span>,</span>
<span>         coords <span class="op">=</span> <span class="va">dag_coords.ex3</span><span class="op">)</span></span>
<span></span>
<span><span class="va">node_labels</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  W <span class="op">=</span> <span class="st">'bold(W)'</span>, </span>
<span>  D <span class="op">=</span> <span class="st">'bold(D)'</span>, </span>
<span>  V <span class="op">=</span> <span class="st">'bold(V)'</span>, </span>
<span>  P <span class="op">=</span> <span class="st">'bold(P)'</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">DAG.ex3</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>, y <span class="op">=</span> <span class="va">y</span>, xend <span class="op">=</span> <span class="va">xend</span>, yend <span class="op">=</span> <span class="va">yend</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://r-causal.github.io/ggdag/reference/geom_dag_text.html">geom_dag_text</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>label <span class="op">=</span> <span class="va">node_labels</span><span class="op">[</span><span class="va">name</span><span class="op">]</span><span class="op">)</span>,</span>
<span>                parse <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>                colour <span class="op">=</span> <span class="st">'black'</span>,</span>
<span>                size <span class="op">=</span> <span class="fl">10</span>,</span>
<span>                family <span class="op">=</span> <span class="st">'mono'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://r-causal.github.io/ggdag/reference/geom_dag_edges.html">geom_dag_edges</a></span><span class="op">(</span>arrow_directed <span class="op">=</span> <span class="fu">grid</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/r/grid/arrow.html">arrow</a></span><span class="op">(</span>length <span class="op">=</span> <span class="fu">grid</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/r/grid/unit.html">unit</a></span><span class="op">(</span><span class="fl">10</span>, <span class="st">'pt'</span><span class="op">)</span>, type <span class="op">=</span> <span class="st">'open'</span><span class="op">)</span>,</span>
<span>                 edge_colour <span class="op">=</span> <span class="st">'black'</span>,</span>
<span>                 family <span class="op">=</span> <span class="st">'mono'</span>,</span>
<span>                 fontface <span class="op">=</span> <span class="st">'bold'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/annotate.html">annotate</a></span><span class="op">(</span><span class="st">'text'</span>, x <span class="op">=</span> <span class="fl">1</span>, y <span class="op">=</span> <span class="fl">3.3</span>, label <span class="op">=</span> <span class="st">'window shading'</span>, </span>
<span>           size <span class="op">=</span> <span class="fl">4</span>, hjust <span class="op">=</span> <span class="fl">0.5</span>, colour <span class="op">=</span> <span class="st">'grey50'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/annotate.html">annotate</a></span><span class="op">(</span><span class="st">'text'</span>, x <span class="op">=</span> <span class="fl">3.5</span>, y <span class="op">=</span> <span class="fl">1.7</span>, label <span class="op">=</span> <span class="st">'daylight'</span>, </span>
<span>           size <span class="op">=</span> <span class="fl">4</span>, hjust <span class="op">=</span> <span class="fl">0.6</span>, colour <span class="op">=</span> <span class="st">'grey50'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/annotate.html">annotate</a></span><span class="op">(</span><span class="st">'text'</span>, x <span class="op">=</span> <span class="fl">6</span>, y <span class="op">=</span> <span class="fl">3.3</span>, label <span class="op">=</span> <span class="st">'perceived warmth'</span>, </span>
<span>           size <span class="op">=</span> <span class="fl">4</span>, hjust <span class="op">=</span> <span class="fl">0.6</span>, colour <span class="op">=</span> <span class="st">'grey50'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/annotate.html">annotate</a></span><span class="op">(</span><span class="st">'text'</span>, x <span class="op">=</span> <span class="fl">6</span>, y <span class="op">=</span> <span class="fl">0.7</span>, label <span class="op">=</span> <span class="st">'visual comfort'</span>, </span>
<span>           size <span class="op">=</span> <span class="fl">4</span>, hjust <span class="op">=</span> <span class="fl">0.6</span>, colour <span class="op">=</span> <span class="st">'grey50'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_cartesian.html">coord_cartesian</a></span><span class="op">(</span>xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.5</span>, <span class="fl">6.5</span><span class="op">)</span>, ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.8</span>, <span class="fl">3.2</span><span class="op">)</span><span class="op">)</span>  <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://r-causal.github.io/ggdag/reference/theme_dag_blank.html">theme_dag</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div id="fig-DAG.ex3-1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" data-cap-location="bottom">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-DAG.ex3-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ex3_simulation_files/figure-html/fig-DAG.ex3-1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-DAG.ex3-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Fig.&nbsp;3.1. Graphical representation via DAG of the data-generating process.
</figcaption></figure>
</div>
</div>
</div>
<p>The DAG in <a href="#fig-DAG.ex3-1" class="quarto-xref">Fig.&nbsp;<span>3.1</span></a> can be written as:</p>
<ul>
<li>
<span class="math inline">\(D \sim f_{D}(W)\)</span>, read as ‘daylight <span class="math inline">\((\text{D})\)</span> is some function of window shading <span class="math inline">\((\text{W})\)</span>’.</li>
<li>
<span class="math inline">\(P \sim f_{P}(W, D)\)</span>, read as ‘perceived warmth <span class="math inline">\((\text{P})\)</span> is some function of window shading <span class="math inline">\((\text{W})\)</span> and daylight <span class="math inline">\((\text{D})\)</span>’.</li>
<li>
<span class="math inline">\(V \sim f_{V}(D)\)</span>, read as ‘visual comfort <span class="math inline">\((\text{V})\)</span> is some function of daylight <span class="math inline">\((\text{D})\)</span>’.</li>
</ul></section><section id="synthetic-data-set" class="level2" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="synthetic-data-set">
<span class="header-section-number">3.2</span> Synthetic data set</h2>
<p>To generate synthetic data, we defined the custom function <code>data.sim_ex3()</code>. This function takes as inputs the sample size <code>n</code> and generates synthetic data according to the DAG in <a href="#fig-DAG.ex3-1" class="quarto-xref">Fig.&nbsp;<span>3.1</span></a>.</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">data.sim_ex3</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">n</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">b_win.day</span> <span class="op">=</span> <span class="fl">1.5</span> <span class="co">#direct causal effect of W on D</span></span>
<span>  <span class="va">b_win.per</span> <span class="op">=</span> <span class="op">-</span><span class="fl">0.7</span> <span class="co">#direct causal effect of W on P</span></span>
<span>  <span class="va">b_day.per</span> <span class="op">=</span> <span class="fl">0.8</span> <span class="co">#direct causal effect of D on P</span></span>
<span>  <span class="va">b_win</span> <span class="op">=</span> <span class="va">b_win.per</span> <span class="op">+</span> <span class="op">(</span><span class="va">b_win.day</span> <span class="op">*</span> <span class="va">b_day.per</span><span class="op">)</span> <span class="co">#total causal effect of W on P</span></span>
<span>  <span class="co">#Simulate window </span></span>
<span>  <span class="va">W</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span>n <span class="op">=</span> <span class="va">n</span>, mean <span class="op">=</span> <span class="fl">0</span>, sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> </span>
<span>  <span class="co">#Simulate daylight</span></span>
<span>  <span class="va">D</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span>n <span class="op">=</span> <span class="va">n</span>, mean <span class="op">=</span> <span class="va">b_win.day</span> <span class="op">*</span> <span class="va">W</span>, sd <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span></span>
<span>  <span class="co">#Simulate visual comfort </span></span>
<span>  <span class="va">V</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span>n <span class="op">=</span> <span class="va">n</span>, mean <span class="op">=</span> <span class="fl">1</span> <span class="op">*</span> <span class="va">D</span>, sd <span class="op">=</span> <span class="fl">0.2</span><span class="op">)</span></span>
<span>  <span class="co">#Simulate perceived warmth </span></span>
<span>  <span class="va">P</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span>n <span class="op">=</span> <span class="va">n</span>, mean <span class="op">=</span> <span class="va">b_win.per</span> <span class="op">*</span> <span class="va">W</span>  <span class="op">+</span> <span class="va">b_day.per</span> <span class="op">*</span> <span class="va">D</span>, sd <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span></span>
<span>  <span class="co">#Return tibble with simulated values</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span><span class="va">W</span>, <span class="va">D</span>, <span class="va">P</span>, <span class="va">V</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="op">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>From this data generation mechanism, we simulated the target population, which consists of one million observations.</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">2025</span><span class="op">)</span> <span class="co">#set random number for reproducibility</span></span>
<span><span class="co">#Simulate the population</span></span>
<span><span class="va">ex3_population</span> <span class="op">&lt;-</span> <span class="fu">data.sim_ex3</span><span class="op">(</span>n <span class="op">=</span> <span class="fl">1e6</span><span class="op">)</span></span>
<span><span class="co">#View the data frame</span></span>
<span><span class="va">ex3_population</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,000,000 × 4
         W       D       P      V
     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
 1  0.621   2.01    1.14    1.85 
 2  0.0356  1.24    1.62    0.875
 3  0.773   0.826  -0.716   1.06 
 4  1.27    0.978   0.241   1.05 
 5  0.371   0.0871 -0.0980 -0.384
 6 -0.163  -0.0222 -0.364   0.387
 7  0.397   0.672   0.821   0.867
 8 -0.0800 -0.801  -1.27   -0.553
 9 -0.345   0.282   1.40    0.280
10  0.702   0.306  -0.193   0.538
# ℹ 999,990 more rows</code></pre>
</div>
</div>
<p>From this population, we obtained one data set of five thousand observations using simple random sampling.</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">n_sims</span> <span class="op">&lt;-</span> <span class="fl">1e3</span> <span class="co">#number of data sets to simulate</span></span>
<span></span>
<span><span class="co">#Set random number for reproducibility</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">2025</span><span class="op">)</span>  </span>
<span><span class="co">#Generate a vector of random numbers for reproducibility</span></span>
<span><span class="va">ex3_random.seed</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">1e5</span>, size <span class="op">=</span> <span class="va">n_sims</span>, replace <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="va">ex3_random.seed</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="co">#Sample one data set of 5,000 observations</span></span>
<span><span class="va">ex3_sample.random</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">ex3_population</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_sample</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">5e3</span><span class="op">)</span> <span class="co">#take a simple random sample of size 5,000 </span></span>
<span></span>
<span><span class="co">#View the data frame</span></span>
<span><span class="va">ex3_sample.random</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5,000 × 4
          W      D       P      V
      &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
 1  0.148    0.878  0.767   0.889
 2  0.820    1.45   0.348   1.21 
 3 -1.28    -2.24  -0.939  -2.46 
 4 -0.179   -0.226 -0.331  -0.352
 5 -0.131   -0.320 -0.189  -0.284
 6 -0.990   -1.88  -0.432  -1.78 
 7 -0.522   -1.16  -0.688  -1.53 
 8 -0.00594 -0.293  0.398  -0.335
 9 -0.146   -0.950  0.0766 -0.574
10 -0.991   -2.15  -1.50   -2.12 
# ℹ 4,990 more rows</code></pre>
</div>
</div>
</section><section id="data-analysis" class="level2" data-number="3.3"><h2 data-number="3.3" class="anchored" data-anchor-id="data-analysis">
<span class="header-section-number">3.3</span> Data analysis</h2>
<p>In this example, the target of our analysis is the total average causal effect, ACE (also known as total average treatment effect, ATE) of window shading <span class="math inline">\((\text{W})\)</span> on perceived warmth <span class="math inline">\((\text{P})\)</span>, which stands for the expected increase of <span class="math inline">\(\text{P}\)</span> in response to a unit increase in <span class="math inline">\(\text{W}\)</span> due to an intervention. The causal effect of interest is visualized in <a href="#fig-DAG.ex3-2" class="quarto-xref">Fig.&nbsp;<span>3.2</span></a>.</p>
<div class="cell fig-cap-location-bottom" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb9" data-cap-location="bottom"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">DAG.ex3</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>, y <span class="op">=</span> <span class="va">y</span>, xend <span class="op">=</span> <span class="va">xend</span>, yend <span class="op">=</span> <span class="va">yend</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co">#visualize causal effect path</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_segment.html">geom_segment</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fl">1</span>, xend <span class="op">=</span> <span class="fl">6</span>, y <span class="op">=</span> <span class="fl">3</span>, yend <span class="op">=</span> <span class="fl">3</span>,</span>
<span>               linewidth <span class="op">=</span> <span class="fl">14</span>, lineend <span class="op">=</span> <span class="st">'round'</span>, colour <span class="op">=</span> <span class="st">'#009E73'</span>, alpha <span class="op">=</span> <span class="fl">0.05</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_segment.html">geom_segment</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fl">1</span>, xend <span class="op">=</span> <span class="fl">3.5</span>, y <span class="op">=</span> <span class="fl">3</span>, yend <span class="op">=</span> <span class="fl">2</span>,</span>
<span>               linewidth <span class="op">=</span> <span class="fl">14</span>, lineend <span class="op">=</span> <span class="st">'round'</span>, colour <span class="op">=</span> <span class="st">'#009E73'</span>, alpha <span class="op">=</span> <span class="fl">0.05</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_segment.html">geom_segment</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fl">3.5</span>, xend <span class="op">=</span> <span class="fl">6</span>, y <span class="op">=</span> <span class="fl">2</span>, yend <span class="op">=</span> <span class="fl">3</span>,</span>
<span>               linewidth <span class="op">=</span> <span class="fl">14</span>, lineend <span class="op">=</span> <span class="st">'round'</span>, colour <span class="op">=</span> <span class="st">'#009E73'</span>, alpha <span class="op">=</span> <span class="fl">0.05</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://r-causal.github.io/ggdag/reference/geom_dag_text.html">geom_dag_text</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>label <span class="op">=</span> <span class="va">node_labels</span><span class="op">[</span><span class="va">name</span><span class="op">]</span><span class="op">)</span>,</span>
<span>                parse <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>                colour <span class="op">=</span> <span class="st">'black'</span>,</span>
<span>                size <span class="op">=</span> <span class="fl">10</span>,</span>
<span>                family <span class="op">=</span> <span class="st">'mono'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://r-causal.github.io/ggdag/reference/geom_dag_edges.html">geom_dag_edges</a></span><span class="op">(</span>arrow_directed <span class="op">=</span> <span class="fu">grid</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/r/grid/arrow.html">arrow</a></span><span class="op">(</span>length <span class="op">=</span> <span class="fu">grid</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/r/grid/unit.html">unit</a></span><span class="op">(</span><span class="fl">10</span>, <span class="st">'pt'</span><span class="op">)</span>, type <span class="op">=</span> <span class="st">'open'</span><span class="op">)</span>,</span>
<span>                 edge_colour <span class="op">=</span> <span class="st">'black'</span>,</span>
<span>                 family <span class="op">=</span> <span class="st">'mono'</span>,</span>
<span>                 fontface <span class="op">=</span> <span class="st">'bold'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/annotate.html">annotate</a></span><span class="op">(</span><span class="st">'text'</span>, x <span class="op">=</span> <span class="fl">1</span>, y <span class="op">=</span> <span class="fl">3.3</span>, label <span class="op">=</span> <span class="st">'window shading'</span>, </span>
<span>           size <span class="op">=</span> <span class="fl">4</span>, hjust <span class="op">=</span> <span class="fl">0.5</span>, colour <span class="op">=</span> <span class="st">'grey50'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/annotate.html">annotate</a></span><span class="op">(</span><span class="st">'text'</span>, x <span class="op">=</span> <span class="fl">3.5</span>, y <span class="op">=</span> <span class="fl">1.7</span>, label <span class="op">=</span> <span class="st">'daylight'</span>, </span>
<span>           size <span class="op">=</span> <span class="fl">4</span>, hjust <span class="op">=</span> <span class="fl">0.6</span>, colour <span class="op">=</span> <span class="st">'grey50'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/annotate.html">annotate</a></span><span class="op">(</span><span class="st">'text'</span>, x <span class="op">=</span> <span class="fl">6</span>, y <span class="op">=</span> <span class="fl">3.3</span>, label <span class="op">=</span> <span class="st">'perceived warmth'</span>, </span>
<span>           size <span class="op">=</span> <span class="fl">4</span>, hjust <span class="op">=</span> <span class="fl">0.6</span>, colour <span class="op">=</span> <span class="st">'grey50'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/annotate.html">annotate</a></span><span class="op">(</span><span class="st">'text'</span>, x <span class="op">=</span> <span class="fl">6</span>, y <span class="op">=</span> <span class="fl">0.7</span>, label <span class="op">=</span> <span class="st">'visual comfort'</span>, </span>
<span>           size <span class="op">=</span> <span class="fl">4</span>, hjust <span class="op">=</span> <span class="fl">0.6</span>, colour <span class="op">=</span> <span class="st">'grey50'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  </span>
<span>  <span class="co">#causal effect number</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/annotate.html">annotate</a></span><span class="op">(</span><span class="st">'text'</span>, x <span class="op">=</span> <span class="fl">3.5</span>, y <span class="op">=</span> <span class="fl">3.2</span>, label <span class="op">=</span> <span class="st">'(-0.7)'</span>, </span>
<span>           size <span class="op">=</span> <span class="fl">4.5</span>, hjust <span class="op">=</span> <span class="fl">0.5</span>, colour <span class="op">=</span> <span class="st">'grey50'</span>, parse <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/annotate.html">annotate</a></span><span class="op">(</span><span class="st">'text'</span>, x <span class="op">=</span> <span class="fl">1.8</span>, y <span class="op">=</span> <span class="fl">2.4</span>, label <span class="op">=</span> <span class="st">'(1.5)'</span>, </span>
<span>           size <span class="op">=</span> <span class="fl">4.5</span>, hjust <span class="op">=</span> <span class="fl">0.5</span>, colour <span class="op">=</span> <span class="st">'grey50'</span>, parse <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/annotate.html">annotate</a></span><span class="op">(</span><span class="st">'text'</span>, x <span class="op">=</span> <span class="fl">5.2</span>, y <span class="op">=</span> <span class="fl">2.4</span>, label <span class="op">=</span> <span class="st">'(0.8)'</span>, </span>
<span>           size <span class="op">=</span> <span class="fl">4.5</span>, hjust <span class="op">=</span> <span class="fl">0.5</span>, colour <span class="op">=</span> <span class="st">'grey50'</span>, parse <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  </span>
<span>  <span class="co">#causal effect total number b_win = b_win.per + (b_win.day * b_day.per)</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/annotate.html">annotate</a></span><span class="op">(</span><span class="st">'text'</span>, x <span class="op">=</span> <span class="fl">3.5</span>, y <span class="op">=</span> <span class="fl">2.8</span>, label <span class="op">=</span> <span class="st">'-0.7 + (1.5 %*% 0.8) == 0.5'</span>, <span class="co"># %-&gt;% </span></span>
<span>           size <span class="op">=</span> <span class="fl">4.5</span>, hjust <span class="op">=</span> <span class="fl">0.5</span>, colour <span class="op">=</span> <span class="st">'black'</span>, parse <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_cartesian.html">coord_cartesian</a></span><span class="op">(</span>xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.5</span>, <span class="fl">6.5</span><span class="op">)</span>, ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.8</span>, <span class="fl">3.2</span><span class="op">)</span><span class="op">)</span>  <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://r-causal.github.io/ggdag/reference/theme_dag_blank.html">theme_dag</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div id="fig-DAG.ex3-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" data-cap-location="bottom">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-DAG.ex3-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ex3_simulation_files/figure-html/fig-DAG.ex3-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-DAG.ex3-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Fig.&nbsp;3.2. Graphical representation via DAG of the data-generating process. The green lines indicate the causal question of interest, and the black number indicates the total average causal effect (the grey numbers with parentheses indicate the causal effect between the two variables connected by the corresponding path).
</figcaption></figure>
</div>
</div>
</div>
<section id="identification" class="level3" data-number="3.3.1"><h3 data-number="3.3.1" class="anchored" data-anchor-id="identification">
<span class="header-section-number">3.3.1</span> Identification</h3>
<p>The first step to answer the causal question of interest is identification. Identification answers a ‘theoretical’ question by determining whether a causal effect can, in principle, be estimated from observed data. The backdoor criterion and its generalization, the adjustment criterion, allow us to understand whether our causal effect of interest can be identified and, if so, which variables we should (or should not) statistically adjust for (i.e., the adjustment set) to estimate the causal effect from the data.</p>
<p>Given its simplicity, we will first apply the backdoor criterion to identify valid adjustment sets to estimate the causal effect of interest. If the backdoor criterion is not applicable, we will apply its generalization, the adjustment criterion.</p>
<section id="backdoor-criterion" class="level4"><h4 class="anchored" data-anchor-id="backdoor-criterion">Backdoor criterion</h4>
<p>Applying the backdoor criterion revealed the absence of any backdoor path (i.e., a non-causal path) from window shading <span class="math inline">\((\text{W})\)</span> to perceived warmth <span class="math inline">\((\text{P})\)</span>. As a result, there is no confounding and no adjustment is required.</p>
<p>Given the DAG in <a href="#fig-DAG.ex3-2" class="quarto-xref">Fig.&nbsp;<span>3.2</span></a>, we can use the <code><a href="https://rdrr.io/pkg/dagitty/man/adjustmentSets.html">adjustmentSets()</a></code> function to identify the adjustment set algorithmically. It is essential to note that this function applies the adjustment criterion and not the backdoor criterion. As such, the <code><a href="https://rdrr.io/pkg/dagitty/man/adjustmentSets.html">adjustmentSets()</a></code> function can find adjustment sets even when the backdoor criterion is not applicable.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/dagitty/man/adjustmentSets.html">adjustmentSets</a></span><span class="op">(</span><span class="va">DAG.ex3</span>,</span>
<span>               exposure <span class="op">=</span> <span class="st">'W'</span>, <span class="co">#window shading</span></span>
<span>               outcome <span class="op">=</span> <span class="st">'P'</span>, <span class="co">#perceived warmth</span></span>
<span>               type <span class="op">=</span> <span class="st">'all'</span>, </span>
<span>               effect <span class="op">=</span> <span class="st">'total'</span>, </span>
<span>               max.results <span class="op">=</span> <span class="cn">Inf</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code><a href="https://rdrr.io/r/base/Paren.html"> {}</a></code></pre>
</div>
</div>
<p>As expected, the resulting adjustment set includes the empty set. Therefore, to get the correct estimate of the total average causal effect, no adjustment is required; failing to do so will lead to bias.</p>
</section></section><section id="estimation" class="level3" data-number="3.3.2"><h3 data-number="3.3.2" class="anchored" data-anchor-id="estimation">
<span class="header-section-number">3.3.2</span> Estimation</h3>
<p>Following the identification step is the estimation step. This step addresses a statistical question by determining how the causal effect identified in the previous step can be estimated. To perform this step, we used a parametric (model-based) estimator, specifically, linear regression. This was possible because we designed the illustrative examples to be simple and with a linear relationship between the variables. This way, we limited the complexity of the examples themselves and shifted the focus to the application of the backdoor criterion to define ‘correct’ adjustment sets.</p>
<p>For transparency and understanding, all (implicit) assumptions used for this illustrative example are (explicitly) provided in <a href="#tbl-summary.ex3" class="quarto-xref">Table&nbsp;<span>3.1</span></a>.</p>
<div class="cell">
<div id="tbl-summary.ex3" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summary.ex3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3.1. Summary description of the simulation example
</figcaption><div aria-describedby="tbl-summary.ex3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="pefclyqint" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#pefclyqint table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#pefclyqint thead, #pefclyqint tbody, #pefclyqint tfoot, #pefclyqint tr, #pefclyqint td, #pefclyqint th {
  border-style: none;
}

#pefclyqint p {
  margin: 0;
  padding: 0;
}

#pefclyqint .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#pefclyqint .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#pefclyqint .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#pefclyqint .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#pefclyqint .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#pefclyqint .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pefclyqint .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#pefclyqint .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#pefclyqint .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#pefclyqint .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#pefclyqint .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#pefclyqint .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#pefclyqint .gt_spanner_row {
  border-bottom-style: hidden;
}

#pefclyqint .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#pefclyqint .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#pefclyqint .gt_from_md > :first-child {
  margin-top: 0;
}

#pefclyqint .gt_from_md > :last-child {
  margin-bottom: 0;
}

#pefclyqint .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#pefclyqint .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#pefclyqint .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#pefclyqint .gt_row_group_first td {
  border-top-width: 2px;
}

#pefclyqint .gt_row_group_first th {
  border-top-width: 2px;
}

#pefclyqint .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#pefclyqint .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#pefclyqint .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#pefclyqint .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pefclyqint .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#pefclyqint .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#pefclyqint .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#pefclyqint .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#pefclyqint .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pefclyqint .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#pefclyqint .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#pefclyqint .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#pefclyqint .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#pefclyqint .gt_left {
  text-align: left;
}

#pefclyqint .gt_center {
  text-align: center;
}

#pefclyqint .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#pefclyqint .gt_font_normal {
  font-weight: normal;
}

#pefclyqint .gt_font_bold {
  font-weight: bold;
}

#pefclyqint .gt_font_italic {
  font-style: italic;
}

#pefclyqint .gt_super {
  font-size: 65%;
}

#pefclyqint .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#pefclyqint .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#pefclyqint .gt_indent_1 {
  text-indent: 5px;
}

#pefclyqint .gt_indent_2 {
  text-indent: 10px;
}

#pefclyqint .gt_indent_3 {
  text-indent: 15px;
}

#pefclyqint .gt_indent_4 {
  text-indent: 20px;
}

#pefclyqint .gt_indent_5 {
  text-indent: 25px;
}

#pefclyqint .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#pefclyqint div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 22%">
<col>
</colgroup>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="colA" style="vertical-align: top; font-weight: bold; background-color: #FFFFFF">Research question</td>
<td class="gt_row gt_left" headers="colB" style="vertical-align: top">Total average causal effect (ACE) of window shading (W) on perceived warmth (P).</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="colA" style="vertical-align: top; font-weight: bold; background-color: #FFFFFF">Assumptions</td>
<td class="gt_row gt_left" headers="colB" style="vertical-align: top">Random sample (simple random sampling): everyone in the population has an equal chance of being selected into the sample.</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="colA" style="border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF"></td>
<td class="gt_row gt_left" headers="colB" style="vertical-align: top">Limited random variability: large sample size.</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="colA" style="border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF"></td>
<td class="gt_row gt_left" headers="colB" style="vertical-align: top">Independence of observations: each observation represents independent bits of information.</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="colA" style="border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF"></td>
<td class="gt_row gt_left" headers="colB" style="vertical-align: top">No confounding: the DAG includes all shared causes among the variables.</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="colA" style="border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF"></td>
<td class="gt_row gt_left" headers="colB" style="vertical-align: top">No model error: perfect functional form specification.</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="colA" style="border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF"></td>
<td class="gt_row gt_left" headers="colB" style="vertical-align: top">No measurement error: all variables are measured perfectly.</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="colA" style="vertical-align: top; font-weight: bold; background-color: #FFFFFF">Variables</td>
<td class="gt_row gt_left" headers="colB" style="vertical-align: top">window shading (W): continuous variable [unit: -]</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="colA" style="border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF"></td>
<td class="gt_row gt_left" headers="colB" style="vertical-align: top">Daylight (D): continuous variable [unit: lux]</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="colA" style="border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF"></td>
<td class="gt_row gt_left" headers="colB" style="vertical-align: top">Perceived warmth (P): continuous variable [unit: -]</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="colA" style="border-top-width: 0px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 0px; border-bottom-style: solid; border-bottom-color: #000000; vertical-align: top; font-weight: bold; background-color: #FFFFFF"></td>
<td class="gt_row gt_left" headers="colB" style="vertical-align: top">Visual comfort (V): continuous variable [unit: -]</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</figure>
</div>
</div>
<p>To carry out the estimation step, we utilized linear regression within both the frequentist and Bayesian frameworks. Specifically, we will run three regression models:</p>
<ul>
<li>
<code>Model.1</code> will include only window shading <span class="math inline">\((\text{W})\)</span> as predictor;</li>
<li>
<code>Model.2</code> will include window shading <span class="math inline">\((\text{W})\)</span> and daylight <span class="math inline">\((\text{D})\)</span> as predictors.</li>
<li>
<code>Model.3</code> will include window shading <span class="math inline">\((\text{W})\)</span> and visual comfort <span class="math inline">\((\text{V})\)</span> as predictors.</li>
</ul>
<p>The results of the fitted statistical models (i.e., <code>Model.1</code>, <code>Model.2</code> and <code>Model.3</code>) are presented here.</p>
<section id="frequentist-framework" class="level4"><h4 class="anchored" data-anchor-id="frequentist-framework">Frequentist framework</h4>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#Fit the linear regression model with W and P (Model 1)</span></span>
<span><span class="va">ex3_Model.1</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">P</span> <span class="op">~</span> <span class="va">W</span>,</span>
<span>     data <span class="op">=</span> <span class="va">ex3_sample.random</span><span class="op">)</span></span>
<span><span class="co">#View of the model summary</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">ex3_Model.1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = P ~ W, data = ex3_sample.random)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.73804 -0.42710  0.00262  0.42714  2.35619 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.001521   0.009025  -0.169    0.866    
W            0.510180   0.008920  57.192   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6382 on 4998 degrees of freedom
Multiple R-squared:  0.3956,    Adjusted R-squared:  0.3954 
F-statistic:  3271 on 1 and 4998 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#Fit the linear regression model with W, D and P (Model 2)</span></span>
<span><span class="va">ex3_Model.2</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">P</span> <span class="op">~</span> <span class="va">W</span> <span class="op">+</span> <span class="va">D</span>,</span>
<span>     data <span class="op">=</span> <span class="va">ex3_sample.random</span><span class="op">)</span></span>
<span><span class="co">#View of the model summary</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">ex3_Model.2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = P ~ W + D, data = ex3_sample.random)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.92355 -0.33391 -0.00018  0.33940  1.68471 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.003004   0.007111   0.422    0.673    
W           -0.698074   0.022967 -30.394   &lt;2e-16 ***
D            0.800956   0.014495  55.259   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5028 on 4997 degrees of freedom
Multiple R-squared:  0.6248,    Adjusted R-squared:  0.6247 
F-statistic:  4161 on 2 and 4997 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#Fit the linear regression model with W, V and P (Model 3)</span></span>
<span><span class="va">ex3_Model.3</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">P</span> <span class="op">~</span> <span class="va">W</span> <span class="op">+</span> <span class="va">V</span>,</span>
<span>     data <span class="op">=</span> <span class="va">ex3_sample.random</span><span class="op">)</span></span>
<span><span class="co">#View of the model summary</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">ex3_Model.3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = P ~ W + V, data = ex3_sample.random)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.9264 -0.3466 -0.0032  0.3518  1.8682 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.005649   0.007426   0.761    0.447    
W           -0.522315   0.022364 -23.355   &lt;2e-16 ***
V            0.683934   0.013994  48.873   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.525 on 4997 degrees of freedom
Multiple R-squared:  0.591, Adjusted R-squared:  0.5909 
F-statistic:  3611 on 2 and 4997 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The estimated coefficients for the three models are then plotted in <a href="#fig-DAG.ex3-estimate" class="quarto-xref">Fig.&nbsp;<span>3.3</span></a>.</p>
<div class="cell fig-cap-location-bottom" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb18" data-cap-location="bottom"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span>  <span class="va">b_win.day</span> <span class="op">=</span> <span class="fl">1.5</span> <span class="co">#direct causal effect of W on D</span></span>
<span>  <span class="va">b_win.per</span> <span class="op">=</span> <span class="op">-</span><span class="fl">0.7</span> <span class="co">#direct causal effect of W on P</span></span>
<span>  <span class="va">b_day.per</span> <span class="op">=</span> <span class="fl">0.8</span> <span class="co">#direct causal effect of D on P</span></span>
<span>  </span>
<span>  <span class="va">b_win</span> <span class="op">=</span> <span class="va">b_win.per</span> <span class="op">+</span> <span class="op">(</span><span class="va">b_win.day</span> <span class="op">*</span> <span class="va">b_day.per</span><span class="op">)</span> <span class="co">#total causal effect of W on P</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>model <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'Model.1'</span>, <span class="st">'Model.2'</span>, <span class="st">'Model.3'</span><span class="op">)</span>,</span>
<span>           estimate <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">ex3_Model.1</span><span class="op">)</span><span class="op">[</span><span class="st">'W'</span><span class="op">]</span>, </span>
<span>                        <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">ex3_Model.2</span><span class="op">)</span><span class="op">[</span><span class="st">'W'</span><span class="op">]</span>, </span>
<span>                        <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">ex3_Model.3</span><span class="op">)</span><span class="op">[</span><span class="st">'W'</span><span class="op">]</span><span class="op">)</span>,</span>
<span>           lower.95.CI <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">ex3_Model.1</span>, level <span class="op">=</span> <span class="fl">0.95</span>, type <span class="op">=</span> <span class="st">'Wald'</span><span class="op">)</span><span class="op">[</span><span class="st">'W'</span>, <span class="fl">1</span><span class="op">]</span>,</span>
<span>                           <span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">ex3_Model.2</span>, level <span class="op">=</span> <span class="fl">0.95</span>, type <span class="op">=</span> <span class="st">'Wald'</span><span class="op">)</span><span class="op">[</span><span class="st">'W'</span>, <span class="fl">1</span><span class="op">]</span>,</span>
<span>                           <span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">ex3_Model.3</span>, level <span class="op">=</span> <span class="fl">0.95</span>, type <span class="op">=</span> <span class="st">'Wald'</span><span class="op">)</span><span class="op">[</span><span class="st">'W'</span>, <span class="fl">1</span><span class="op">]</span><span class="op">)</span>,</span>
<span>           upper.95.CI <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">ex3_Model.1</span>, level <span class="op">=</span> <span class="fl">0.95</span>, type <span class="op">=</span> <span class="st">'Wald'</span><span class="op">)</span><span class="op">[</span><span class="st">'W'</span>, <span class="fl">2</span><span class="op">]</span>,</span>
<span>                           <span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">ex3_Model.2</span>, level <span class="op">=</span> <span class="fl">0.95</span>, type <span class="op">=</span> <span class="st">'Wald'</span><span class="op">)</span><span class="op">[</span><span class="st">'W'</span>, <span class="fl">2</span><span class="op">]</span>,</span>
<span>                           <span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">ex3_Model.3</span>, level <span class="op">=</span> <span class="fl">0.95</span>, type <span class="op">=</span> <span class="st">'Wald'</span><span class="op">)</span><span class="op">[</span><span class="st">'W'</span>, <span class="fl">2</span><span class="op">]</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  </span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">estimate</span>, y <span class="op">=</span> <span class="va">model</span>, xmin <span class="op">=</span> <span class="va">lower.95.CI</span>, xmax <span class="op">=</span> <span class="va">upper.95.CI</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span><span class="op">(</span>xintercept <span class="op">=</span> <span class="va">b_win</span>, alpha <span class="op">=</span> <span class="fl">0.8</span>, linetype <span class="op">=</span> <span class="st">'dashed'</span>, colour <span class="op">=</span> <span class="st">'blue'</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_linerange</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>shape <span class="op">=</span> <span class="fl">21</span>, size <span class="op">=</span> <span class="fl">2</span>, fill <span class="op">=</span> <span class="st">'white'</span>, stroke <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span><span class="st">'Estimate'</span>, </span>
<span>                     breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span>from <span class="op">=</span> <span class="op">-</span><span class="fl">5</span>, to <span class="op">=</span> <span class="fl">5</span>, by <span class="op">=</span> <span class="fl">0.25</span><span class="op">)</span>,</span>
<span>                     limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">0.85</span>, <span class="fl">0.55</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>panel.grid <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>        panel.background <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>        panel.border <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_rect</a></span><span class="op">(</span>colour <span class="op">=</span> <span class="st">'black'</span>, fill <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span>,</span>
<span>        axis.title.y <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div id="fig-DAG.ex3-estimate" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" data-cap-location="bottom">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-DAG.ex3-estimate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ex3_simulation_files/figure-html/fig-DAG.ex3-estimate-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="5400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-DAG.ex3-estimate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Fig.&nbsp;3.3. Estimates of the window shading coefficient for the three models. The white dots represent the point estimate, and the black lines represent the 95% confidence intervals. The blue dashed line represents the parameter used to generate the data.
</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-DAG.ex3-estimate" class="quarto-xref">Fig.&nbsp;<span>3.3</span></a> shows the estimates (point estimate and 95% confidence interval) of the coefficient for window shading for <code>Model.1</code>, <code>Model.2</code> and <code>Model.3</code>.</p>
<p>For <code>Model.1</code> we found a positive coefficient between window shading <span class="math inline">\((\text{W})\)</span> and perceived warmth <span class="math inline">\((\text{P})\)</span> equal to 0.510 with 95% confidence interval (CI) [0.493, 0.528]. Since the 95% CI excludes zero, the regression coefficient is statistically significantly different from zero at the 0.05 level (p-value = 0). Additionally, since the 95% CI includes the data-generating parameter for window shading (i.e., <code>b_win = 0.5</code>), we can deduce that the estimated coefficient for window shading is not statistically significantly different from 0.5 at the 0.05 level (although this will be the case for all numbers within the 95% confidence interval). We can test this more formally by using the <code>linearHypothesis()</code> function. Specifically,</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#Test for W = 0.5</span></span>
<span><span class="fu">car</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">linearHypothesis</a></span><span class="op">(</span><span class="va">ex3_Model.1</span>, <span class="st">'W = 0.5'</span><span class="op">)</span> <span class="co"># car:: access the function from the car package without loading it in the environment </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Linear hypothesis test:
W = 0.5

Model 1: restricted model
Model 2: P ~ W

  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1   4999 2035.9                           
2   4998 2035.4  1   0.53037 1.3024 0.2538</code></pre>
</div>
</div>
<p>The resulting p-value is 0.254, which indicates that we fail to reject the null hypothesis (i.e., <code>W = 0.5</code>) at the 0.05 level. This result suggests that the regression coefficient for window shading (i.e., 0.510) is not statistically significantly different from 0.5. Since the estimated causal effect from <code>Model.1</code> is unbiased, we would correctly conclude that an increase of unit in the opening of window shading causes an increase in perceived warmth by 0.510 units (95% CI [0.493, 0.528]).</p>
<p>For <code>Model.2</code> we found a negative coefficient between window shading <span class="math inline">\((\text{W})\)</span> and perceived warmth <span class="math inline">\((\text{P})\)</span> equal to -0.698 with 95% CI [-0.743, -0.653]. Since the 95% CI excludes zero, the regression coefficient is statistically significantly different from zero at the 0.05 level (p-value = 2.43e-186). Additionally, since the 95% CI does not include the data-generating parameter for window shading (i.e., <code>b_win = 0.5</code>), we can deduce that the estimated coefficient for window shading is statistically significantly different from 0.5 at the 0.05 level. We can test this more formally by using the <code>linearHypothesis()</code> function. Specifically,</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#Test for W = 0.5</span></span>
<span><span class="fu">car</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">linearHypothesis</a></span><span class="op">(</span><span class="va">ex3_Model.2</span>, <span class="st">'W = 0.5'</span><span class="op">)</span> <span class="co"># car:: access the function from the car package without loading it in the environment </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Linear hypothesis test:
W = 0.5

Model 1: restricted model
Model 2: P ~ W + D

  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1   4998 1951.3                                  
2   4997 1263.4  1    687.97 2721.1 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The resulting p-value is 0, which indicates that we can reject the null hypothesis (i.e., <code>W = 0.5</code>) at the 0.05 level. This result suggests that the regression coefficient for window shading (i.e., -0.698) is statistically significantly different from 0.5. Since the estimated causal effect from <code>Model.2</code> is biased, we would erroneously conclude that an increase of unit in the opening of window shading causes a decrease in perceived warmth by -0.698 units (95% CI [-0.743, -0.653]).</p>
<p>For <code>Model.3</code> we found a negative coefficient between window shading <span class="math inline">\((\text{W})\)</span> and perceived warmth <span class="math inline">\((\text{P})\)</span> equal to -0.522 with 95% CI [-0.566, -0.478]. Since the 95% CI excludes zero, the regression coefficient is statistically significantly different from zero at the 0.05 level (p-value = 1.39e-114). Additionally, since the 95% CI does not include the data-generating parameter for window shading (i.e., <code>b_win = 0.5</code>), we can deduce that the estimated coefficient for window shading is statistically significantly different from 0.5 at the 0.05 level. We can test this more formally by using the <code>linearHypothesis()</code> function. Specifically,</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#Test for W = 0.5</span></span>
<span><span class="fu">car</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">linearHypothesis</a></span><span class="op">(</span><span class="va">ex3_Model.3</span>, <span class="st">'W = 0.5'</span><span class="op">)</span> <span class="co"># car:: access the function from the car package without loading it in the environment </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Linear hypothesis test:
W = 0.5

Model 1: restricted model
Model 2: P ~ W + V

  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1   4998 1953.0                                  
2   4997 1377.1  1    575.86 2089.6 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The resulting p-value is 0, which indicates that we can reject the null hypothesis (i.e., <code>W = 0.5</code>) at the 0.05 level. This result suggests that the regression coefficient for window shading (i.e., -0.522) is statistically significantly different from 0.5. Since the estimated causal effect from <code>Model.3</code> is biased, we would erroneously conclude that an increase of unit in the opening of window shading causes a decrease in perceived warmth by -0.522 units (95% CI [-0.566, -0.478]).</p>
<p>Importantly, for <code>Model.1</code>, <code>Model.2</code>, and <code>Model.3</code>, the 95% confidence interval means that if we were to repeat the sampling process and calculate the interval many times, 95% of those calculated intervals would contain the true population parameter. To highlight this, we can repeat the analysis by fitting the three models to one thousand data sets randomly selected from our population.</p>
<p>The for-loop shown in the code below performs the following operations. First, sample (using simple random sampling) a data set of 5,000 observations from the target population. Subsequently, perform linear regression using <code>Model.1</code>, <code>Model.2</code> and <code>Model.3</code> and store the estimated coefficients for <code>window shading</code>, its standard error and 95% confidence interval in the data frame <code>coefs_ex3</code>. This operation is repeated a thousand times, resulting in the data frame <code>coefs_ex3</code> containing the estimates (point estimate, standard error and confidence interval) of a thousand random samples of size 5,000 using <code>Model.1</code>, <code>Model.2</code> and <code>Model.3</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">n_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'mod.1'</span>, <span class="st">'mod.2'</span>, <span class="st">'mod.3'</span><span class="op">)</span>     </span>
<span></span>
<span><span class="va">n_row</span> <span class="op">&lt;-</span> <span class="va">n_sims</span><span class="op">*</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">n_model</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#Create an empty data frame</span></span>
<span><span class="va">empty.df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="cn">NA</span>, nrow <span class="op">=</span> <span class="va">n_row</span>, ncol <span class="op">=</span> <span class="fl">7</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#Rename the data frame columns</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">empty.df</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'sim.id'</span>, <span class="st">'estimate'</span>, <span class="st">'se'</span>, <span class="st">'CI_2.5'</span>, <span class="st">'CI_97.5'</span>,</span>
<span>                        <span class="st">'model'</span>, <span class="st">'coverage'</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#Sample a thousand data sets of 5,000 observations and perform linear regression </span></span>
<span><span class="va">coefs_ex3</span> <span class="op">&lt;-</span> <span class="va">empty.df</span> <span class="co">#assign the empty data frame</span></span>
<span><span class="va">k</span> <span class="op">=</span> <span class="fl">1</span></span>
<span><span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="va">n_sims</span><span class="op">)</span><span class="op">{</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="va">ex3_random.seed</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">)</span> <span class="co">#set unique seed for each simulation </span></span>
<span><span class="co">#Sample data set from population   </span></span>
<span>  <span class="va">sample.random</span> <span class="op">&lt;-</span> </span>
<span>    <span class="va">ex3_population</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice_sample</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">5e3</span><span class="op">)</span> <span class="co">#take a simple random sample of size 5,000</span></span>
<span><span class="co">#Fit models</span></span>
<span>  <span class="kw">for</span> <span class="op">(</span><span class="va">j</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">n_model</span><span class="op">)</span><span class="op">)</span><span class="op">{</span></span>
<span>    <span class="kw">if</span> <span class="op">(</span><span class="va">n_model</span><span class="op">[</span><span class="va">j</span><span class="op">]</span> <span class="op">==</span> <span class="st">'mod.1'</span><span class="op">)</span><span class="op">{</span></span>
<span>      <span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">P</span> <span class="op">~</span> <span class="va">W</span>,</span>
<span>                data <span class="op">=</span> <span class="va">sample.random</span><span class="op">)</span></span>
<span>    <span class="op">}</span> <span class="kw">else</span> <span class="kw">if</span> <span class="op">(</span><span class="va">n_model</span><span class="op">[</span><span class="va">j</span><span class="op">]</span> <span class="op">==</span> <span class="st">'mod.2'</span><span class="op">)</span><span class="op">{</span></span>
<span>      <span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">P</span> <span class="op">~</span> <span class="va">W</span> <span class="op">+</span> <span class="va">D</span>,</span>
<span>                data <span class="op">=</span> <span class="va">sample.random</span><span class="op">)</span>  </span>
<span>    <span class="op">}</span> <span class="kw">else</span> <span class="op">{</span></span>
<span>      <span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">P</span> <span class="op">~</span> <span class="va">W</span> <span class="op">+</span> <span class="va">V</span>,</span>
<span>                data <span class="op">=</span> <span class="va">sample.random</span><span class="op">)</span></span>
<span>    <span class="op">}</span>  </span>
<span><span class="co">#Compile matrix  </span></span>
<span>  <span class="va">coefs_ex3</span><span class="op">[</span><span class="va">k</span>, <span class="fl">1</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">i</span> <span class="co">#simulation ID</span></span>
<span>  <span class="va">coefs_ex3</span><span class="op">[</span><span class="va">k</span>, <span class="fl">2</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">fit</span><span class="op">)</span><span class="op">[</span><span class="st">'W'</span><span class="op">]</span> <span class="co">#point estimate</span></span>
<span>  <span class="va">coefs_ex3</span><span class="op">[</span><span class="va">k</span>, <span class="fl">3</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit</span><span class="op">)</span><span class="op">$</span><span class="va">coef</span><span class="op">[</span><span class="st">'W'</span>,<span class="st">'Std. Error'</span><span class="op">]</span> <span class="co">#standard error</span></span>
<span>  <span class="va">coefs_ex3</span><span class="op">[</span><span class="va">k</span>, <span class="fl">4</span><span class="op">:</span><span class="fl">5</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">fit</span>, level <span class="op">=</span> <span class="fl">0.95</span>, type <span class="op">=</span> <span class="st">'Wald'</span><span class="op">)</span><span class="op">[</span><span class="st">'W'</span>, <span class="op">]</span> <span class="co">#confidence interval (Wald)</span></span>
<span>  <span class="va">coefs_ex3</span><span class="op">[</span><span class="va">k</span>, <span class="fl">6</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">n_model</span><span class="op">[</span><span class="va">j</span><span class="op">]</span> <span class="co">#sample size</span></span>
<span>  <span class="va">k</span> <span class="op">=</span> <span class="va">k</span> <span class="op">+</span> <span class="fl">1</span></span>
<span>  <span class="op">}</span></span>
<span><span class="op">}</span></span>
<span><span class="va">coefs_ex3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="va">coefs_ex3</span><span class="op">)</span></span>
<span><span class="co">#View the data frame</span></span>
<span><span class="va">coefs_ex3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,000 × 7
   sim.id estimate      se CI_2.5 CI_97.5 model coverage
    &lt;int&gt;    &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;lgl&gt;   
 1      1    0.510 0.00892  0.493   0.528 mod.1 NA      
 2      1   -0.698 0.0230  -0.743  -0.653 mod.2 NA      
 3      1   -0.522 0.0224  -0.566  -0.478 mod.3 NA      
 4      2    0.488 0.00913  0.470   0.506 mod.1 NA      
 5      2   -0.710 0.0221  -0.753  -0.666 mod.2 NA      
 6      2   -0.555 0.0216  -0.597  -0.512 mod.3 NA      
 7      3    0.495 0.00903  0.478   0.513 mod.1 NA      
 8      3   -0.707 0.0220  -0.750  -0.664 mod.2 NA      
 9      3   -0.544 0.0216  -0.586  -0.502 mod.3 NA      
10      4    0.511 0.00910  0.494   0.529 mod.1 NA      
# ℹ 2,990 more rows</code></pre>
</div>
</div>
<p>The <code>coverage</code> is defined by setting its value to <code>1</code> if the confidence interval overlaps the data-generating parameter for <code>window shading</code> (i.e., <code>b_win = 0.5</code>) and <code>0</code> otherwise.</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#Calculate coverage</span></span>
<span><span class="va">coefs_ex3</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">coefs_ex3</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>coverage <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when</a></span><span class="op">(</span><span class="va">CI_2.5</span> <span class="op">&gt;</span> <span class="va">b_win</span> <span class="op">|</span> <span class="va">CI_97.5</span> <span class="op">&lt;</span> <span class="va">b_win</span> <span class="op">~</span> <span class="fl">0</span>,</span>
<span>                              <span class="va">CI_2.5</span> <span class="op">&lt;=</span> <span class="va">b_win</span> <span class="op">&amp;</span> <span class="va">CI_97.5</span> <span class="op">&gt;=</span> <span class="va">b_win</span> <span class="op">~</span> <span class="fl">1</span>,</span>
<span>                              .default <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#View the data frame</span></span>
<span><span class="va">coefs_ex3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,000 × 7
   sim.id estimate      se CI_2.5 CI_97.5 model coverage
    &lt;int&gt;    &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;
 1      1    0.510 0.00892  0.493   0.528 mod.1        1
 2      1   -0.698 0.0230  -0.743  -0.653 mod.2        0
 3      1   -0.522 0.0224  -0.566  -0.478 mod.3        0
 4      2    0.488 0.00913  0.470   0.506 mod.1        1
 5      2   -0.710 0.0221  -0.753  -0.666 mod.2        0
 6      2   -0.555 0.0216  -0.597  -0.512 mod.3        0
 7      3    0.495 0.00903  0.478   0.513 mod.1        1
 8      3   -0.707 0.0220  -0.750  -0.664 mod.2        0
 9      3   -0.544 0.0216  -0.586  -0.502 mod.3        0
10      4    0.511 0.00910  0.494   0.529 mod.1        1
# ℹ 2,990 more rows</code></pre>
</div>
</div>
<p>The results are then plotted in <a href="#fig-DAG.ex3-CI" class="quarto-xref">Fig.&nbsp;<span>3.4</span></a>.</p>
<div class="cell fig-cap-location-bottom" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb29" data-cap-location="bottom"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model_names</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'mod.1'</span> <span class="op">=</span> <span class="st">'Model.1'</span>, </span>
<span>                 <span class="st">'mod.2'</span> <span class="op">=</span> <span class="st">'Model.2'</span>,</span>
<span>                 <span class="st">'mod.3'</span> <span class="op">=</span> <span class="st">'Model.3'</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">coefs_ex3</span>, <span class="va">sim.id</span> <span class="op">&lt;=</span> <span class="fl">2e2</span><span class="op">)</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sim.id</span>, y <span class="op">=</span> <span class="va">estimate</span>, ymin <span class="op">=</span> <span class="va">CI_2.5</span>, ymax <span class="op">=</span> <span class="va">CI_97.5</span>, colour <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">coverage</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="va">b_win</span>, alpha <span class="op">=</span> <span class="fl">0.8</span>, linetype <span class="op">=</span> <span class="st">'dashed'</span>, colour <span class="op">=</span> <span class="st">'blue'</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_linerange</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>shape <span class="op">=</span> <span class="fl">21</span>, size <span class="op">=</span> <span class="fl">1</span>, fill <span class="op">=</span> <span class="st">'white'</span>, stroke <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_colour_manual</a></span><span class="op">(</span><span class="st">''</span>, values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'black'</span>, <span class="st">'#FF4040'</span><span class="op">)</span>,</span>
<span>                      breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'1'</span>,<span class="st">'0'</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_y_continuous</a></span><span class="op">(</span><span class="st">'Estimate'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span><span class="st">'Simulation ID'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="va">model</span><span class="op">~</span><span class="va">.</span>, </span>
<span>             labeller <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labeller.html">labeller</a></span><span class="op">(</span>model <span class="op">=</span> <span class="va">model_names</span><span class="op">)</span>,</span>
<span>             nrow <span class="op">=</span> <span class="fl">3</span>,</span>
<span>             scales <span class="op">=</span> <span class="st">'fixed'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">'none'</span>, </span>
<span>        panel.grid <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>        panel.background <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>        panel.border <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_rect</a></span><span class="op">(</span>colour <span class="op">=</span> <span class="st">'black'</span>, fill <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span>,</span>
<span>        axis.title.y <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div id="fig-DAG.ex3-CI" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" data-cap-location="bottom">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-DAG.ex3-CI-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ex3_simulation_files/figure-html/fig-DAG.ex3-CI-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="5400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-DAG.ex3-CI-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Fig.&nbsp;3.4. Estimates of the window shading coefficient (only the first hundreds of the thousand simulations are shown). The white dots represent the point estimate, and the black lines represent the 95% confidence intervals. In red are highlighted the confidence intervals that do not overlap the parameter used to generate the data (dashed blue line).
</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-DAG.ex3-CI" class="quarto-xref">Fig.&nbsp;<span>3.4</span></a> shows the first 200 estimates (point estimate and confidence interval) of the causal effect of window shading for <code>Model.1</code>, <code>Model.2</code> and <code>Model.3</code>. If all the thousand simulations are considered, the frequency of the coverage of the calculated confidence intervals (i.e., how many times the confidence intervals overlap the data-generating parameter) is 94.8%, 0.0% and 0.0% for <code>Model.1</code>, <code>Model.2</code> and <code>Model.3</code>, respectively. Since the estimate of the causal effect for <code>Model.2</code> and <code>Model.3</code> are biased, the calculated confidence intervals for these models do not have the expected coverage. In fact, confidence intervals only quantify the uncertainty due to random error (i.e., sample variability), not systematic error (i.e., bias). Instead, the estimates from <code>Model.1</code> are unbiased and the calculated 95% confidence intervals have the expected coverage (i.e., overlap the data-generating parameter 95% of the times).</p>
<p>We can also visualize all the 1,000 estimates of the coefficient for window shading for <code>Model.1</code>, <code>Model.2</code> and <code>Model.3</code> (the estimates were shown as white dots in <a href="#fig-DAG.ex3-CI" class="quarto-xref">Fig.&nbsp;<span>3.4</span></a>).</p>
<div class="cell fig-cap-location-bottom" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb30" data-cap-location="bottom"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">coefs_ex3</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">estimate</span>, y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes_eval.html">after_stat</a></span><span class="op">(</span><span class="va">count</span><span class="op">)</span> <span class="op">&gt;</span> <span class="fl">0</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes_eval.html">after_stat</a></span><span class="op">(</span><span class="va">count</span><span class="op">)</span>, <span class="cn">NA</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>binwidth <span class="op">=</span> <span class="fl">0.015</span>, fill <span class="op">=</span> <span class="st">'white'</span>, colour <span class="op">=</span> <span class="st">'grey50'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span><span class="op">(</span>xintercept <span class="op">=</span> <span class="va">b_win</span>, colour <span class="op">=</span> <span class="st">'blue'</span>, linetype <span class="op">=</span> <span class="st">'dashed'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span><span class="st">'Estimate'</span>, </span>
<span>                     breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span>from <span class="op">=</span> <span class="op">-</span><span class="fl">5</span>, to <span class="op">=</span> <span class="fl">5</span>, by <span class="op">=</span> <span class="fl">0.25</span><span class="op">)</span>,</span>
<span>                     limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">0.85</span>, <span class="fl">0.55</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_grid.html">facet_grid</a></span><span class="op">(</span><span class="va">model</span><span class="op">~</span><span class="va">.</span>, </span>
<span>             labeller <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labeller.html">labeller</a></span><span class="op">(</span>model <span class="op">=</span> <span class="va">model_names</span><span class="op">)</span>,</span>
<span>             scales <span class="op">=</span> <span class="st">'fixed'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.title.y <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span>, </span>
<span>        axis.text.y <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span>, </span>
<span>        axis.ticks.y <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>        panel.grid <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>        panel.background <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>        panel.border <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_rect</a></span><span class="op">(</span>colour <span class="op">=</span> <span class="st">'black'</span>, fill <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div id="fig-DAG.ex3-mean-estimate" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" data-cap-location="bottom">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-DAG.ex3-mean-estimate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ex3_simulation_files/figure-html/fig-DAG.ex3-mean-estimate-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="5400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-DAG.ex3-mean-estimate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Fig.&nbsp;3.5. Histogram of the 1,000 estimates of the window shading coefficient for the three models. The blue dashed line represents the parameter used to generate the data.
</figcaption></figure>
</div>
</div>
</div>
<p>In <a href="#fig-DAG.ex3-mean-estimate" class="quarto-xref">Fig.&nbsp;<span>3.5</span></a>, the estimated coefficients are visualized through a histogram. Here, we can see that the estimates for <code>Model.2</code> and <code>Model.3</code> are not clustered around the data-generating parameter (blue dashed line) having a mean estimate of -0.701 (with 0.022 standard deviation) and -0.535 (with 0.021 standard deviation), respectively. In contrast, the estimates for <code>Model.1</code> having a mean estimate of 0.499 (with 0.009 standard deviation) are centered around the data-generating parameter.</p>
<p>As expected, since there is no backdoor path open, regressing perceived warmth <span class="math inline">\((\text{P})\)</span> on window shading <span class="math inline">\((\text{W})\)</span> (i.e., using <code>Model.1</code>) leads to the correct estimate of the total average causal effect. However, when daylight is included as a predictor (i.e., using <code>Model.2</code>), the estimates are biased. Adjusting for daylight blocks a part of the causal effect. This happens because daylight is a mediator on the path from window shading <span class="math inline">\((\text{W})\)</span> to perceived warmth <span class="math inline">\((\text{P})\)</span>. This bias is known as post-treatment bias. Additionally, we have a biased estimate of the total average causal effect of window shading <span class="math inline">\((\text{W})\)</span> on perceived warmth <span class="math inline">\((\text{P})\)</span> when we include visual comfort <span class="math inline">\((\text{V})\)</span> as a predictor (i.e., using <code>Model.3</code>). This happens because visual comfort <span class="math inline">\((\text{V})\)</span> is a descendant of daylight <span class="math inline">\((\text{D})\)</span>; consequently, adjusting for visual comfort <span class="math inline">\((\text{V})\)</span> is akin to adjusting for daylight <span class="math inline">\((\text{D})\)</span> since the two variables share information (daylight is the cause of visual comfort).</p>
</section><section id="bayesian-framework" class="level4"><h4 class="anchored" data-anchor-id="bayesian-framework">Bayesian framework</h4>
<details><summary>
Click to expand
</summary><div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#Fit the linear regression model with W and P (Model 1)</span></span>
<span><span class="va">ex3_Model.1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">P</span> <span class="op">~</span> <span class="va">W</span>,</span>
<span>                        family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">gaussian</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>                        data <span class="op">=</span> <span class="va">ex3_sample.random</span>,</span>
<span>                        <span class="co">#Prior coefficients</span></span>
<span>                        prior <span class="op">=</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/priors.html">normal</a></span><span class="op">(</span>location <span class="op">=</span> <span class="fl">0</span>, scale <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>,</span>
<span>                        <span class="co">#Prior intercept</span></span>
<span>                        prior_intercept <span class="op">=</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/priors.html">normal</a></span><span class="op">(</span>location <span class="op">=</span> <span class="fl">0</span>, scale <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>,</span>
<span>                        <span class="co">#Prior sigma</span></span>
<span>                        prior_aux <span class="op">=</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/priors.html">exponential</a></span><span class="op">(</span>rate <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>,</span>
<span>                        iter <span class="op">=</span> <span class="fl">4000</span>, warmup <span class="op">=</span> <span class="fl">1000</span>, </span>
<span>                        save_warmup <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>                        chains <span class="op">=</span> <span class="fl">4</span>, cores <span class="op">=</span> <span class="fl">4</span>,</span>
<span>                        seed <span class="op">=</span> <span class="fl">2025</span><span class="op">)</span> <span class="co">#for reproducibility   </span></span>
<span><span class="co">#View of the model</span></span>
<span><span class="va">ex3_Model.1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>stan_glm
 family:       gaussian [identity]
 formula:      P ~ W
 observations: 5000
 predictors:   2
------
            Median MAD_SD
(Intercept) 0.0    0.0   
W           0.5    0.0   

Auxiliary parameter(s):
      Median MAD_SD
sigma 0.6    0.0   

------
* For help interpreting the printed output see ?print.stanreg
* For info on the priors used see ?prior_summary.stanreg</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#Fit the linear regression model with W, D and P (Model 2)</span></span>
<span><span class="va">ex3_Model.2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">P</span> <span class="op">~</span> <span class="va">W</span> <span class="op">+</span> <span class="va">D</span>,</span>
<span>                        family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">gaussian</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>                        data <span class="op">=</span> <span class="va">ex3_sample.random</span>,</span>
<span>                        <span class="co">#Prior coefficients</span></span>
<span>                        prior <span class="op">=</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/priors.html">normal</a></span><span class="op">(</span>location <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">0</span><span class="op">)</span>, scale <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span>,</span>
<span>                        <span class="co">#Prior intercept</span></span>
<span>                        prior_intercept <span class="op">=</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/priors.html">normal</a></span><span class="op">(</span>location <span class="op">=</span> <span class="fl">0</span>, scale <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>,</span>
<span>                        <span class="co">#Prior sigma</span></span>
<span>                        prior_aux <span class="op">=</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/priors.html">exponential</a></span><span class="op">(</span>rate <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>,</span>
<span>                        iter <span class="op">=</span> <span class="fl">4000</span>, warmup <span class="op">=</span> <span class="fl">1000</span>, </span>
<span>                        save_warmup <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>                        chains <span class="op">=</span> <span class="fl">4</span>, cores <span class="op">=</span> <span class="fl">4</span>,</span>
<span>                        seed <span class="op">=</span> <span class="fl">2025</span><span class="op">)</span> <span class="co">#for reproducibility</span></span>
<span><span class="co">#View of the model</span></span>
<span><span class="va">ex3_Model.2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>stan_glm
 family:       gaussian [identity]
 formula:      P ~ W + D
 observations: 5000
 predictors:   3
------
            Median MAD_SD
(Intercept)  0.0    0.0  
W           -0.7    0.0  
D            0.8    0.0  

Auxiliary parameter(s):
      Median MAD_SD
sigma 0.5    0.0   

------
* For help interpreting the printed output see ?print.stanreg
* For info on the priors used see ?prior_summary.stanreg</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#Fit the linear regression model with W, V and P (Model 3)</span></span>
<span><span class="va">ex3_Model.3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">P</span> <span class="op">~</span> <span class="va">W</span> <span class="op">+</span> <span class="va">V</span>,</span>
<span>                        family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">gaussian</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>                        data <span class="op">=</span> <span class="va">ex3_sample.random</span>,</span>
<span>                        <span class="co">#Prior coefficients</span></span>
<span>                        prior <span class="op">=</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/priors.html">normal</a></span><span class="op">(</span>location <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">0</span><span class="op">)</span>, scale <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span>,</span>
<span>                        <span class="co">#Prior intercept</span></span>
<span>                        prior_intercept <span class="op">=</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/priors.html">normal</a></span><span class="op">(</span>location <span class="op">=</span> <span class="fl">0</span>, scale <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>,</span>
<span>                        <span class="co">#Prior sigma</span></span>
<span>                        prior_aux <span class="op">=</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/priors.html">exponential</a></span><span class="op">(</span>rate <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>,</span>
<span>                        iter <span class="op">=</span> <span class="fl">4000</span>, warmup <span class="op">=</span> <span class="fl">1000</span>, </span>
<span>                        save_warmup <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>                        chains <span class="op">=</span> <span class="fl">4</span>, cores <span class="op">=</span> <span class="fl">4</span>,</span>
<span>                        seed <span class="op">=</span> <span class="fl">2025</span><span class="op">)</span> <span class="co">#for reproducibility</span></span>
<span><span class="co">#View of the model</span></span>
<span><span class="va">ex3_Model.3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>stan_glm
 family:       gaussian [identity]
 formula:      P ~ W + V
 observations: 5000
 predictors:   3
------
            Median MAD_SD
(Intercept)  0.0    0.0  
W           -0.5    0.0  
V            0.7    0.0  

Auxiliary parameter(s):
      Median MAD_SD
sigma 0.5    0.0   

------
* For help interpreting the printed output see ?print.stanreg
* For info on the priors used see ?prior_summary.stanreg</code></pre>
</div>
</div>
<p>In Bayesian analysis, there are important diagnostics that have to be carried out in order to assess the convergence and efficiency of the Markov Chains. This is done by using the <code><a href="https://mc-stan.org/rstan/reference/monitor.html">monitor()</a></code> function which computes summaries of MCMC (Markov Chain Monte Carlo) draws and monitor convergence. Specifically, we will look at <code>Rhat</code>, <code>Bulk_ESS</code> and <code>Tail_ESS</code> metrics.</p>
<div class="cell">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#Diagnostics for model 1</span></span>
<span><span class="fu"><a href="https://mc-stan.org/rstan/reference/monitor.html">monitor</a></span><span class="op">(</span><span class="va">ex3_Model.1</span><span class="op">$</span><span class="va">stanfit</span><span class="op">)</span>  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Inference for the input samples (4 chains: each with iter = 4000; warmup = 0):

                   Q5     Q50     Q95    Mean  SD  Rhat Bulk_ESS Tail_ESS
(Intercept)       0.0     0.0     0.0     0.0 0.0     1    12088     8622
W                 0.5     0.5     0.5     0.5 0.0     1    11533     8670
sigma             0.6     0.6     0.6     0.6 0.0     1    11793     8110
mean_PPD          0.0     0.0     0.0     0.0 0.0     1    12191    10616
log-posterior -4854.8 -4852.0 -4851.0 -4852.4 1.2     1     6031     7127

For each parameter, Bulk_ESS and Tail_ESS are crude measures of 
effective sample size for bulk and tail quantities respectively (an ESS &gt; 100 
per chain is considered good), and Rhat is the potential scale reduction 
factor on rank normalized split chains (at convergence, Rhat &lt;= 1.05).</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#Diagnostics for model 2</span></span>
<span><span class="fu"><a href="https://mc-stan.org/rstan/reference/monitor.html">monitor</a></span><span class="op">(</span><span class="va">ex3_Model.2</span><span class="op">$</span><span class="va">stanfit</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Inference for the input samples (4 chains: each with iter = 4000; warmup = 0):

                   Q5     Q50     Q95    Mean  SD  Rhat Bulk_ESS Tail_ESS
(Intercept)       0.0     0.0     0.0     0.0 0.0     1     7636     6818
W                -0.7    -0.7    -0.7    -0.7 0.0     1     4770     5567
D                 0.8     0.8     0.8     0.8 0.0     1     4796     5487
sigma             0.5     0.5     0.5     0.5 0.0     1     8255     6236
mean_PPD          0.0     0.0     0.0     0.0 0.0     1     9358    10287
log-posterior -3664.7 -3661.7 -3660.4 -3662.0 1.4     1     4692     6853

For each parameter, Bulk_ESS and Tail_ESS are crude measures of 
effective sample size for bulk and tail quantities respectively (an ESS &gt; 100 
per chain is considered good), and Rhat is the potential scale reduction 
factor on rank normalized split chains (at convergence, Rhat &lt;= 1.05).</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#Diagnostics for model 3</span></span>
<span><span class="fu"><a href="https://mc-stan.org/rstan/reference/monitor.html">monitor</a></span><span class="op">(</span><span class="va">ex3_Model.3</span><span class="op">$</span><span class="va">stanfit</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Inference for the input samples (4 chains: each with iter = 4000; warmup = 0):

                   Q5     Q50     Q95    Mean  SD  Rhat Bulk_ESS Tail_ESS
(Intercept)       0.0     0.0     0.0     0.0 0.0     1     8298     7180
W                -0.6    -0.5    -0.5    -0.5 0.0     1     4298     5085
V                 0.7     0.7     0.7     0.7 0.0     1     4334     5399
sigma             0.5     0.5     0.5     0.5 0.0     1     9060     7011
mean_PPD          0.0     0.0     0.0     0.0 0.0     1     9705    10021
log-posterior -3880.2 -3877.1 -3875.7 -3877.4 1.4     1     4575     6066

For each parameter, Bulk_ESS and Tail_ESS are crude measures of 
effective sample size for bulk and tail quantities respectively (an ESS &gt; 100 
per chain is considered good), and Rhat is the potential scale reduction 
factor on rank normalized split chains (at convergence, Rhat &lt;= 1.05).</code></pre>
</div>
</div>
<p><code>Rhat</code> is a metric used to assess the convergence of Markov Chain Monte Carlo (MCMC) simulations. It helps determine if the MCMC chains have adequately explored the target posterior distribution. Specifically, it compares the between- and within-chain estimates for model parameters: If chains have not mixed well (i.e., the between- and within-chain estimates do not agree), R-hat is larger than 1. A general rule of thumb is to use the sample only if R-hat is less than 1.05; a larger value suggests that the chains have not mixed well, and the results might not be reliable. In our three models, all <code>Rhat</code> are equal to 1 indicating that the chains have mixed well and have adequately explored the target posterior distribution.</p>
<p><code>Bulk_ESS</code> and <code>Tail_ESS</code> stand for ‘Bulk Effective Sample Size’ and ‘Tail Effective Sample Size,’ respectively. Since MCMC samples are not truly independent (they are correlated), these metrics assess the sampling efficiencies, that is, they help evaluate how efficiently the MCMC sampler is exploring the parameter space.</p>
<ul>
<li>
<code>Bulk_ESS</code> is a useful measure for sampling efficiency in the bulk (center) of the distribution (e.g., efficiency of mean and median estimates);</li>
<li>
<code>Tail_ESS</code> is a useful measure for sampling efficiency in the tails of the distribution (e.g., efficiency of variance and tail quantile estimates). A general rule of thumb is that both <code>Bulk-ESS</code> and <code>Tail-ESS</code> should be at least 100 (approximately) per Markov Chain in order to be reliable and indicate that estimates of respective posterior quantiles are reliable. In our three models, all <code>Bulk-ESS</code> and <code>Tail-ESS</code> are well above 400 (i.e., 100 multiplied by 4, the number of chains we used) indicating that estimates of posterior quantiles are reliable.</li>
</ul>
<p>Since we have established that the posteriors are reliable, we can now explore the model estimates.</p>
<p>The estimated coefficients for the three models are then plotted in <a href="#fig-DAG.ex3-estimate-Bayesian" class="quarto-xref">Fig.&nbsp;<span>3.6</span></a>.</p>
<div class="cell fig-cap-location-bottom" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb43" data-cap-location="bottom"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#Extract draws from model 1 </span></span>
<span><span class="va">post_ex3_Model.1</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">ex3_Model.1</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://mjskay.github.io/tidybayes/reference/spread_draws.html">spread_draws</a></span><span class="op">(</span><span class="va">W</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="co">#extract draws from the fitted model</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>model <span class="op">=</span> <span class="st">'Model.1'</span><span class="op">)</span> <span class="co">#add a new column to specify that the model</span></span>
<span></span>
<span><span class="co">#Extract draws from model 2</span></span>
<span><span class="va">post_ex3_Model.2</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">ex3_Model.2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://mjskay.github.io/tidybayes/reference/spread_draws.html">spread_draws</a></span><span class="op">(</span><span class="va">W</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="co">#extract draws from the fitted model</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>model <span class="op">=</span> <span class="st">'Model.2'</span><span class="op">)</span> <span class="co">#add a new column to specify that the model</span></span>
<span></span>
<span><span class="co">#Extract draws from model 3</span></span>
<span><span class="va">post_ex3_Model.3</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">ex3_Model.3</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://mjskay.github.io/tidybayes/reference/spread_draws.html">spread_draws</a></span><span class="op">(</span><span class="va">W</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="co">#extract draws from the fitted model</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>model <span class="op">=</span> <span class="st">'Model.3'</span><span class="op">)</span> <span class="co">#add a new column to specify that the model</span></span>
<span></span>
<span><span class="co">#Combine draws</span></span>
<span><span class="va">plot.post</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span><span class="va">post_ex3_Model.1</span>, <span class="va">post_ex3_Model.2</span>, <span class="va">post_ex3_Model.3</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Plot</span></span>
<span><span class="va">plot.post</span>  <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">model</span>, x <span class="op">=</span> <span class="va">W</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://mjskay.github.io/ggdist/reference/stat_slabinterval.html">stat_slabinterval</a></span><span class="op">(</span>point_interval <span class="op">=</span> <span class="st">'mean_hdi'</span>,</span>
<span>                    .width <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">.95</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span><span class="op">(</span>xintercept <span class="op">=</span> <span class="va">b_win</span>, alpha <span class="op">=</span> <span class="fl">0.8</span>, linetype <span class="op">=</span> <span class="st">'dashed'</span>, colour <span class="op">=</span> <span class="st">'blue'</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span><span class="st">'Estimate'</span>, </span>
<span>                     breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span>from <span class="op">=</span> <span class="op">-</span><span class="fl">5</span>, to <span class="op">=</span> <span class="fl">5</span>, by <span class="op">=</span> <span class="fl">0.25</span><span class="op">)</span>,</span>
<span>                     limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">0.85</span>, <span class="fl">0.55</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>panel.grid <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>        panel.background <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>        panel.border <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_rect</a></span><span class="op">(</span>colour <span class="op">=</span> <span class="st">'black'</span>, fill <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span>,</span>
<span>        axis.title.y <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div id="fig-DAG.ex3-estimate-Bayesian" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" data-cap-location="bottom">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-DAG.ex3-estimate-Bayesian-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ex3_simulation_files/figure-html/fig-DAG.ex3-estimate-Bayesian-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="5400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-DAG.ex3-estimate-Bayesian-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Fig.&nbsp;3.6. Posterior distribution of the window shading coefficient for the three models. The black line and dot at the bottom of each distribution represent the highest density interval (HDI) and the mean, respectively.
</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-DAG.ex3-estimate-Bayesian" class="quarto-xref">Fig.&nbsp;<span>3.6</span></a> shows the estimates (mean and 95% HDI) of the coefficient for window shading for <code>Model.1</code>, <code>Model.2</code> and <code>Model.3</code>.</p>
<p>For <code>Model.1</code> we found a positive coefficient between window shading <span class="math inline">\((\text{W})\)</span> and perceived warmth <span class="math inline">\((\text{P})\)</span> (mean = 0.510, 95% HDI [0.493, 0.527]). The estimated causal effect is unbiased, leading to the correct conclusion that an increase of unit in the opening of window shading causes an increase in perceived warmth by 0.510 units, on average.</p>
<p>For <code>Model.2</code> we found a negative coefficient between window shading <span class="math inline">\((\text{W})\)</span> and perceived warmth <span class="math inline">\((\text{P})\)</span> (mean = -0.698, 95% HDI [-0.745, -0.654]). The estimated causal effect is therefore biased, leading to the wrong conclusion that an increase of unit in the opening of window shading causes a decrease in perceived warmth by -0.698 units, on average.</p>
<p>For <code>Model.3</code> we found a negative coefficient between window shading <span class="math inline">\((\text{W})\)</span> and perceived warmth <span class="math inline">\((\text{P})\)</span> (mean = -0.522, 95% HDI [-0.567, -0.478]). The estimated causal effect is therefore biased, leading to the wrong conclusion that an increase of unit in the opening of window shading causes a decrease in perceived warmth by -0.522 units, on average.</p>
<p>Importantly, for both <code>Model.1</code>, <code>Model.2</code> and <code>Model.3</code>, the 95% HDI is the range of parameter values within which the most credible 95% of the posterior distribution falls. Unlike a frequentist confidence interval, the Bayesian 95% HDI has a direct probabilistic meaning: every point inside the HDI has a higher probability density than any point outside the interval. Therefore, given the model, the prior and the data, we can say that there is a 95% probability that the data-generating parameter (i.e., <code>b_win = 0.5</code>) lies within the HDI. However, since <code>Model.2</code> and <code>Model.3</code> lead to biased estimates, we will reach the wrong conclusion by stating that there is a 95% probability that the data-generating parameter lies within the [-0.745, -0.654] interval and [-0.567, -0.478], respectively. This probability is 0%.</p>
<p>As expected, since there is no backdoor path open, regressing perceived warmth <span class="math inline">\((\text{P})\)</span> on window shading <span class="math inline">\((\text{W})\)</span> (i.e., using <code>Model.1</code>) leads to the correct estimate of the total average causal effect. However, when daylight is included as a predictor (i.e., using <code>Model.2</code>) the estimates are biased. Adjusting for daylight blocks a part of the causal effect. This happens because daylight is a mediator on the path from window shading <span class="math inline">\((\text{W})\)</span> to perceived warmth <span class="math inline">\((\text{P})\)</span>. This bias is known as post-treatment bias. Additionally, we have a biased estimate of the total average causal effect of window shading <span class="math inline">\((\text{W})\)</span> on perceived warmth <span class="math inline">\((\text{P})\)</span> when we include visual comfort <span class="math inline">\((\text{V})\)</span> as a predictor (i.e., using <code>Model.3</code>). This happens because visual comfort <span class="math inline">\((\text{V})\)</span> is a descendant of daylight <span class="math inline">\((\text{D})\)</span>; consequently, adjusting for visual comfort <span class="math inline">\((\text{V})\)</span> is akin to adjusting for daylight <span class="math inline">\((\text{D})\)</span> since the two variables share information (daylight is the cause of visual comfort).</p>
</details></section></section></section><section id="session-info" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="session-info">Session info</h2>
<p>Version information about R, the OS and attached or loaded packages.</p>
<div class="cell">
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.2.3 (2023-03-15 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 26200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.utf8 
[2] LC_CTYPE=English_United Kingdom.utf8   
[3] LC_MONETARY=English_United Kingdom.utf8
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] rstan_2.32.7        StanHeaders_2.32.10 gt_1.1.0           
 [4] lubridate_1.9.4     forcats_1.0.1       stringr_1.6.0      
 [7] dplyr_1.1.4         purrr_1.2.0         readr_2.1.6        
[10] tidyr_1.3.1         tibble_3.3.0        ggplot2_4.0.1      
[13] tidyverse_2.0.0     ggdist_3.3.3        tidybayes_3.0.7    
[16] rstanarm_2.32.2     Rcpp_1.1.0          dagitty_0.3-4      
[19] ggdag_0.2.13       

loaded via a namespace (and not attached):
  [1] backports_1.5.0       plyr_1.8.9            igraph_2.2.1         
  [4] splines_4.2.3         svUnit_1.0.8          crosstalk_1.2.2      
  [7] rstantools_2.5.0      inline_0.3.21         digest_0.6.38        
 [10] htmltools_0.5.8.1     viridis_0.6.5         magrittr_2.0.4       
 [13] checkmate_2.3.3       memoise_2.0.1         tzdb_0.5.0           
 [16] graphlayouts_1.2.2    RcppParallel_5.1.11-1 matrixStats_1.5.0    
 [19] xts_0.14.1            timechange_0.3.0      colorspace_2.1-2     
 [22] ggrepel_0.9.6         rbibutils_2.4         xfun_0.54            
 [25] jsonlite_2.0.0        lme4_1.1-37           survival_3.8-3       
 [28] zoo_1.8-14            glue_1.8.0            reformulas_0.4.2     
 [31] polyclip_1.10-7       gtable_0.3.6          V8_8.0.1             
 [34] distributional_0.5.0  car_3.1-3             pkgbuild_1.4.8       
 [37] abind_1.4-8           scales_1.4.0          miniUI_0.1.2         
 [40] viridisLite_0.4.2     xtable_1.8-4          Formula_1.2-5        
 [43] stats4_4.2.3          DT_0.34.0             htmlwidgets_1.6.4    
 [46] threejs_0.3.4         arrayhelpers_1.1-0    RColorBrewer_1.1-3   
 [49] posterior_1.6.1       pkgconfig_2.0.3       loo_2.8.0            
 [52] farver_2.1.2          sass_0.4.10           utf8_1.2.6           
 [55] tidyselect_1.2.1      labeling_0.4.3        rlang_1.1.6          
 [58] reshape2_1.4.5        later_1.4.4           tools_4.2.3          
 [61] cachem_1.1.0          cli_3.6.5             generics_0.1.4       
 [64] evaluate_1.0.5        fastmap_1.2.0         yaml_2.3.10          
 [67] knitr_1.50            fs_1.6.6              tidygraph_1.3.1      
 [70] ggraph_2.2.2          nlme_3.1-168          mime_0.13            
 [73] xml2_1.5.0            compiler_4.2.3        bayesplot_1.14.0     
 [76] shinythemes_1.2.0     rstudioapi_0.17.1     curl_7.0.0           
 [79] tweenr_2.0.3          stringi_1.8.7         lattice_0.22-7       
 [82] Matrix_1.6-5          nloptr_2.2.1          markdown_2.0         
 [85] shinyjs_2.1.0         tensorA_0.36.2.1      vctrs_0.6.5          
 [88] pillar_1.11.1         lifecycle_1.0.4       Rdpack_2.6.4         
 [91] httpuv_1.6.16         QuickJSR_1.8.1        R6_2.6.1             
 [94] promises_1.5.0        gridExtra_2.3         codetools_0.2-20     
 [97] boot_1.3-32           colourpicker_1.3.0    MASS_7.3-58.2        
[100] gtools_3.9.5          withr_3.0.2           shinystan_2.6.0      
[103] parallel_4.2.3        hms_1.1.4             grid_4.2.3           
[106] coda_0.19-4.1         minqa_1.2.8           rmarkdown_2.30       
[109] S7_0.2.1              carData_3.0-5         otel_0.2.0           
[112] ggforce_0.5.0         shiny_1.11.1          base64enc_0.1-3      
[115] dygraphs_1.1.1.6     </code></pre>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-bayesboot2025" class="csl-entry" role="listitem">
Bååth, R., 2025. Bayesboot: An implementation of rubin’s (1981) bayesian bootstrap. <a href="https://doi.org/10.32614/CRAN.package.bayesboot">https://doi.org/10.32614/CRAN.package.bayesboot</a>
</div>
<div id="ref-ggdag2025" class="csl-entry" role="listitem">
Barrett, M., 2024. <a href="https://CRAN.R-project.org/package=ggdag">Ggdag: Analyze and create elegant directed acyclic graphs</a>.
</div>
<div id="ref-car2025" class="csl-entry" role="listitem">
Fox, J., Weisberg, S., 2019. <a href="https://www.john-fox.ca/Companion/">An <span>R</span> companion to applied regression</a>, Third. ed. Sage, Thousand Oaks <span>CA</span>.
</div>
<div id="ref-rstanarm2025" class="csl-entry" role="listitem">
Goodrich, B., Gabry, J., Ali, I., Brilleman, S., 2024. <a href="https://mc-stan.org/rstanarm/">Rstanarm: <span>Bayesian</span> applied regression modeling via <span>Stan</span>.</a>
</div>
<div id="ref-gt2025" class="csl-entry" role="listitem">
Iannone, R., Cheng, J., Schloerke, B., Hughes, E., Lauer, A., Seo, J., Brevoort, K., Roy, O., 2025. <a href="https://CRAN.R-project.org/package=gt">Gt: Easily create presentation-ready display tables</a>.
</div>
<div id="ref-ggdist2025b" class="csl-entry" role="listitem">
Kay, M., 2025. <span class="nocase">ggdist</span>: Visualizations of distributions and uncertainty. <a href="https://doi.org/10.5281/zenodo.3879620">https://doi.org/10.5281/zenodo.3879620</a>
</div>
<div id="ref-tidybayes2025" class="csl-entry" role="listitem">
Kay, M., 2024b. <span class="nocase">tidybayes</span>: Tidy data and geoms for <span>Bayesian</span> models. <a href="https://doi.org/10.5281/zenodo.1308151">https://doi.org/10.5281/zenodo.1308151</a>
</div>
<div id="ref-ggdist2025a" class="csl-entry" role="listitem">
Kay, M., 2024a. <span class="nocase">ggdist</span>: Visualizations of distributions and uncertainty in the grammar of graphics. IEEE Transactions on Visualization and Computer Graphics 30, 414–424. <a href="https://doi.org/10.1109/TVCG.2023.3327195">https://doi.org/10.1109/TVCG.2023.3327195</a>
</div>
<div id="ref-Rstudio2025" class="csl-entry" role="listitem">
Posit team, 2025. <a href="http://www.posit.co/">RStudio: Integrated development environment for r</a>. Posit Software, PBC, Boston, MA.
</div>
<div id="ref-R2025" class="csl-entry" role="listitem">
R Core Team, 2023. <a href="https://www.R-project.org/">R: A language and environment for statistical computing</a>. R Foundation for Statistical Computing, Vienna, Austria.
</div>
<div id="ref-rstan2025" class="csl-entry" role="listitem">
Stan Development Team, 2025. <a href="https://mc-stan.org/"><span>RStan</span>: The <span>R</span> interface to <span>Stan</span></a>.
</div>
<div id="ref-dagitty2025" class="csl-entry" role="listitem">
Textor, J., van der Zander, B., Gilthorpe, M.S., Liśkiewicz, M., Ellison, G.T., 2016. Robust causal inference using directed acyclic graphs: The <span>R</span> package ’dagitty’. International Journal of Epidemiology 45, 1887–1894. <a href="https://doi.org/10.1093/ije/dyw341">https://doi.org/10.1093/ije/dyw341</a>
</div>
<div id="ref-tidyverse2025" class="csl-entry" role="listitem">
Wickham, H., Averick, M., Bryan, J., Chang, W., McGowan, L.D., François, R., Grolemund, G., Hayes, A., Henry, L., Hester, J., Kuhn, M., Pedersen, T.L., Miller, E., Bache, S.M., Müller, K., Ooms, J., Robinson, D., Seidel, D.P., Spinu, V., Takahashi, K., Vaughan, D., Wilke, C., Woo, K., Yutani, H., 2019. Welcome to the <span class="nocase">tidyverse</span>. Journal of Open Source Software 4, 1686. <a href="https://doi.org/10.21105/joss.01686">https://doi.org/10.21105/joss.01686</a>
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./ex2_simulation.html" class="pagination-link" aria-label="Simulation example">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Simulation example</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ex4_simulation.html" class="pagination-link" aria-label="Simulation example">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Simulation example</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>This notebook was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>© 2024. <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a></p>
</div>
  </div>
</footer>


</body></html>